// AUTO-GENERATED by scripts/bake-area-map-sprites.mjs — do not edit by hand.
/** Area maps with baked trainer/item/hidden/berry layers for HoennMap. */
export interface AreaMapBakeEntry {
  width: number;
  height: number;
  counts: Record<"trainer" | "item" | "hidden" | "berry", number>;
  skippedInBase: number;
  layers: Array<"trainer" | "item" | "hidden" | "berry">;
  prebakedTrainers: boolean;
}

export const AREA_MAP_BAKE_MANIFEST: Record<string, AreaMapBakeEntry> = {
  "abandonedship-captainsoffice": {
    "width": 144,
    "height": 112,
    "counts": {
      "trainer": 0,
      "item": 1,
      "hidden": 0,
      "berry": 0
    },
    "skippedInBase": 0,
    "layers": [
      "item"
    ],
    "prebakedTrainers": false
  },
  "abandonedship-hiddenfloorrooms": {
    "width": 704,
    "height": 240,
    "counts": {
      "trainer": 0,
      "item": 4,
      "hidden": 4,
      "berry": 0
    },
    "skippedInBase": 0,
    "layers": [
      "item",
      "hidden"
    ],
    "prebakedTrainers": false
  },
  "abandonedship-room-b1f": {
    "width": 144,
    "height": 128,
    "counts": {
      "trainer": 0,
      "item": 1,
      "hidden": 0,
      "berry": 0
    },
    "skippedInBase": 0,
    "layers": [
      "item"
    ],
    "prebakedTrainers": false
  },
  "abandonedship-rooms-1f": {
    "width": 288,
    "height": 272,
    "counts": {
      "trainer": 2,
      "item": 1,
      "hidden": 0,
      "berry": 0
    },
    "skippedInBase": 0,
    "layers": [
      "trainer",
      "item"
    ],
    "prebakedTrainers": false
  },
  "abandonedship-rooms-b1f": {
    "width": 432,
    "height": 128,
    "counts": {
      "trainer": 0,
      "item": 1,
      "hidden": 0,
      "berry": 0
    },
    "skippedInBase": 0,
    "layers": [
      "item"
    ],
    "prebakedTrainers": false
  },
  "abandonedship-rooms2-1f": {
    "width": 144,
    "height": 272,
    "counts": {
      "trainer": 4,
      "item": 1,
      "hidden": 0,
      "berry": 0
    },
    "skippedInBase": 0,
    "layers": [
      "trainer",
      "item"
    ],
    "prebakedTrainers": false
  },
  "abandonedship-rooms2-b1f": {
    "width": 288,
    "height": 128,
    "counts": {
      "trainer": 0,
      "item": 1,
      "hidden": 0,
      "berry": 0
    },
    "skippedInBase": 0,
    "layers": [
      "item"
    ],
    "prebakedTrainers": false
  },
  "aquahideout-b1f": {
    "width": 816,
    "height": 384,
    "counts": {
      "trainer": 4,
      "item": 5,
      "hidden": 0,
      "berry": 0
    },
    "skippedInBase": 0,
    "layers": [
      "trainer",
      "item"
    ],
    "prebakedTrainers": false
  },
  "aquahideout-b2f": {
    "width": 544,
    "height": 384,
    "counts": {
      "trainer": 3,
      "item": 1,
      "hidden": 0,
      "berry": 0
    },
    "skippedInBase": 0,
    "layers": [
      "trainer",
      "item"
    ],
    "prebakedTrainers": false
  },
  "artisancave-1f": {
    "width": 336,
    "height": 352,
    "counts": {
      "trainer": 0,
      "item": 1,
      "hidden": 0,
      "berry": 0
    },
    "skippedInBase": 0,
    "layers": [
      "item"
    ],
    "prebakedTrainers": false
  },
  "artisancave-b1f": {
    "width": 736,
    "height": 864,
    "counts": {
      "trainer": 0,
      "item": 1,
      "hidden": 4,
      "berry": 0
    },
    "skippedInBase": 0,
    "layers": [
      "item",
      "hidden"
    ],
    "prebakedTrainers": false
  },
  "battlepyramidsquare01": {
    "width": 128,
    "height": 128,
    "counts": {
      "trainer": 4,
      "item": 3,
      "hidden": 0,
      "berry": 0
    },
    "skippedInBase": 0,
    "layers": [
      "trainer",
      "item"
    ],
    "prebakedTrainers": false
  },
  "battlepyramidsquare02": {
    "width": 128,
    "height": 128,
    "counts": {
      "trainer": 4,
      "item": 3,
      "hidden": 0,
      "berry": 0
    },
    "skippedInBase": 0,
    "layers": [
      "trainer",
      "item"
    ],
    "prebakedTrainers": false
  },
  "battlepyramidsquare03": {
    "width": 128,
    "height": 128,
    "counts": {
      "trainer": 4,
      "item": 3,
      "hidden": 0,
      "berry": 0
    },
    "skippedInBase": 0,
    "layers": [
      "trainer",
      "item"
    ],
    "prebakedTrainers": false
  },
  "battlepyramidsquare04": {
    "width": 128,
    "height": 128,
    "counts": {
      "trainer": 4,
      "item": 3,
      "hidden": 0,
      "berry": 0
    },
    "skippedInBase": 0,
    "layers": [
      "trainer",
      "item"
    ],
    "prebakedTrainers": false
  },
  "battlepyramidsquare05": {
    "width": 128,
    "height": 128,
    "counts": {
      "trainer": 4,
      "item": 3,
      "hidden": 0,
      "berry": 0
    },
    "skippedInBase": 0,
    "layers": [
      "trainer",
      "item"
    ],
    "prebakedTrainers": false
  },
  "battlepyramidsquare06": {
    "width": 128,
    "height": 128,
    "counts": {
      "trainer": 4,
      "item": 3,
      "hidden": 0,
      "berry": 0
    },
    "skippedInBase": 0,
    "layers": [
      "trainer",
      "item"
    ],
    "prebakedTrainers": false
  },
  "battlepyramidsquare07": {
    "width": 128,
    "height": 128,
    "counts": {
      "trainer": 4,
      "item": 3,
      "hidden": 0,
      "berry": 0
    },
    "skippedInBase": 0,
    "layers": [
      "trainer",
      "item"
    ],
    "prebakedTrainers": false
  },
  "battlepyramidsquare08": {
    "width": 128,
    "height": 128,
    "counts": {
      "trainer": 4,
      "item": 3,
      "hidden": 0,
      "berry": 0
    },
    "skippedInBase": 0,
    "layers": [
      "trainer",
      "item"
    ],
    "prebakedTrainers": false
  },
  "battlepyramidsquare09": {
    "width": 128,
    "height": 128,
    "counts": {
      "trainer": 4,
      "item": 3,
      "hidden": 0,
      "berry": 0
    },
    "skippedInBase": 0,
    "layers": [
      "trainer",
      "item"
    ],
    "prebakedTrainers": false
  },
  "battlepyramidsquare10": {
    "width": 128,
    "height": 128,
    "counts": {
      "trainer": 4,
      "item": 3,
      "hidden": 0,
      "berry": 0
    },
    "skippedInBase": 0,
    "layers": [
      "trainer",
      "item"
    ],
    "prebakedTrainers": false
  },
  "battlepyramidsquare11": {
    "width": 128,
    "height": 128,
    "counts": {
      "trainer": 4,
      "item": 3,
      "hidden": 0,
      "berry": 0
    },
    "skippedInBase": 0,
    "layers": [
      "trainer",
      "item"
    ],
    "prebakedTrainers": false
  },
  "battlepyramidsquare12": {
    "width": 128,
    "height": 128,
    "counts": {
      "trainer": 4,
      "item": 3,
      "hidden": 0,
      "berry": 0
    },
    "skippedInBase": 0,
    "layers": [
      "trainer",
      "item"
    ],
    "prebakedTrainers": false
  },
  "battlepyramidsquare13": {
    "width": 128,
    "height": 128,
    "counts": {
      "trainer": 4,
      "item": 3,
      "hidden": 0,
      "berry": 0
    },
    "skippedInBase": 0,
    "layers": [
      "trainer",
      "item"
    ],
    "prebakedTrainers": false
  },
  "battlepyramidsquare14": {
    "width": 128,
    "height": 128,
    "counts": {
      "trainer": 4,
      "item": 3,
      "hidden": 0,
      "berry": 0
    },
    "skippedInBase": 0,
    "layers": [
      "trainer",
      "item"
    ],
    "prebakedTrainers": false
  },
  "battlepyramidsquare15": {
    "width": 128,
    "height": 128,
    "counts": {
      "trainer": 4,
      "item": 3,
      "hidden": 0,
      "berry": 0
    },
    "skippedInBase": 0,
    "layers": [
      "trainer",
      "item"
    ],
    "prebakedTrainers": false
  },
  "battlepyramidsquare16": {
    "width": 128,
    "height": 128,
    "counts": {
      "trainer": 4,
      "item": 3,
      "hidden": 0,
      "berry": 0
    },
    "skippedInBase": 0,
    "layers": [
      "trainer",
      "item"
    ],
    "prebakedTrainers": false
  },
  "contesthall": {
    "width": 240,
    "height": 176,
    "counts": {
      "trainer": 0,
      "item": 1,
      "hidden": 0,
      "berry": 0
    },
    "skippedInBase": 0,
    "layers": [
      "item"
    ],
    "prebakedTrainers": false
  },
  "fierypath": {
    "width": 560,
    "height": 608,
    "counts": {
      "trainer": 0,
      "item": 2,
      "hidden": 0,
      "berry": 0
    },
    "skippedInBase": 0,
    "layers": [
      "item"
    ],
    "prebakedTrainers": false
  },
  "granitecave-1f": {
    "width": 672,
    "height": 240,
    "counts": {
      "trainer": 0,
      "item": 1,
      "hidden": 0,
      "berry": 0
    },
    "skippedInBase": 0,
    "layers": [
      "item"
    ],
    "prebakedTrainers": false
  },
  "granitecave-b1f": {
    "width": 512,
    "height": 416,
    "counts": {
      "trainer": 0,
      "item": 1,
      "hidden": 0,
      "berry": 0
    },
    "skippedInBase": 0,
    "layers": [
      "item"
    ],
    "prebakedTrainers": false
  },
  "granitecave-b2f": {
    "width": 512,
    "height": 416,
    "counts": {
      "trainer": 0,
      "item": 2,
      "hidden": 2,
      "berry": 0
    },
    "skippedInBase": 0,
    "layers": [
      "item",
      "hidden"
    ],
    "prebakedTrainers": false
  },
  "jaggedpass": {
    "width": 480,
    "height": 736,
    "counts": {
      "trainer": 5,
      "item": 1,
      "hidden": 2,
      "berry": 0
    },
    "skippedInBase": 0,
    "layers": [
      "trainer",
      "item",
      "hidden"
    ],
    "prebakedTrainers": false
  },
  "littleroottown-brendanshouse-2f": {
    "width": 144,
    "height": 128,
    "counts": {
      "trainer": 0,
      "item": 1,
      "hidden": 0,
      "berry": 0
    },
    "skippedInBase": 0,
    "layers": [
      "item"
    ],
    "prebakedTrainers": false
  },
  "littleroottown-mayshouse-2f": {
    "width": 144,
    "height": 128,
    "counts": {
      "trainer": 0,
      "item": 1,
      "hidden": 0,
      "berry": 0
    },
    "skippedInBase": 0,
    "layers": [
      "item"
    ],
    "prebakedTrainers": false
  },
  "littleroottown-professorbirchslab": {
    "width": 208,
    "height": 208,
    "counts": {
      "trainer": 0,
      "item": 3,
      "hidden": 0,
      "berry": 0
    },
    "skippedInBase": 0,
    "layers": [
      "item"
    ],
    "prebakedTrainers": false
  },
  "magmahideout-1f": {
    "width": 592,
    "height": 608,
    "counts": {
      "trainer": 2,
      "item": 1,
      "hidden": 0,
      "berry": 0
    },
    "skippedInBase": 0,
    "layers": [
      "trainer",
      "item"
    ],
    "prebakedTrainers": false
  },
  "magmahideout-2f-2r": {
    "width": 784,
    "height": 448,
    "counts": {
      "trainer": 4,
      "item": 2,
      "hidden": 0,
      "berry": 0
    },
    "skippedInBase": 0,
    "layers": [
      "trainer",
      "item"
    ],
    "prebakedTrainers": false
  },
  "magmahideout-3f-1r": {
    "width": 448,
    "height": 384,
    "counts": {
      "trainer": 2,
      "item": 1,
      "hidden": 0,
      "berry": 0
    },
    "skippedInBase": 0,
    "layers": [
      "trainer",
      "item"
    ],
    "prebakedTrainers": false
  },
  "magmahideout-3f-2r": {
    "width": 384,
    "height": 272,
    "counts": {
      "trainer": 1,
      "item": 1,
      "hidden": 0,
      "berry": 0
    },
    "skippedInBase": 0,
    "layers": [
      "trainer",
      "item"
    ],
    "prebakedTrainers": false
  },
  "magmahideout-3f-3r": {
    "width": 528,
    "height": 384,
    "counts": {
      "trainer": 0,
      "item": 1,
      "hidden": 0,
      "berry": 0
    },
    "skippedInBase": 0,
    "layers": [
      "item"
    ],
    "prebakedTrainers": false
  },
  "magmahideout-4f": {
    "width": 944,
    "height": 448,
    "counts": {
      "trainer": 4,
      "item": 1,
      "hidden": 0,
      "berry": 0
    },
    "skippedInBase": 0,
    "layers": [
      "trainer",
      "item"
    ],
    "prebakedTrainers": false
  },
  "meteorfalls-1f-1r": {
    "width": 480,
    "height": 672,
    "counts": {
      "trainer": 0,
      "item": 4,
      "hidden": 0,
      "berry": 0
    },
    "skippedInBase": 0,
    "layers": [
      "item"
    ],
    "prebakedTrainers": false
  },
  "meteorfalls-b1f-2r": {
    "width": 176,
    "height": 288,
    "counts": {
      "trainer": 0,
      "item": 1,
      "hidden": 0,
      "berry": 0
    },
    "skippedInBase": 0,
    "layers": [
      "item"
    ],
    "prebakedTrainers": false
  },
  "mossdeepcity-stevenshouse": {
    "width": 176,
    "height": 128,
    "counts": {
      "trainer": 0,
      "item": 1,
      "hidden": 0,
      "berry": 0
    },
    "skippedInBase": 0,
    "layers": [
      "item"
    ],
    "prebakedTrainers": false
  },
  "mtpyre-2f": {
    "width": 208,
    "height": 208,
    "counts": {
      "trainer": 5,
      "item": 1,
      "hidden": 0,
      "berry": 0
    },
    "skippedInBase": 0,
    "layers": [
      "trainer",
      "item"
    ],
    "prebakedTrainers": false
  },
  "mtpyre-3f": {
    "width": 208,
    "height": 208,
    "counts": {
      "trainer": 3,
      "item": 1,
      "hidden": 0,
      "berry": 0
    },
    "skippedInBase": 0,
    "layers": [
      "trainer",
      "item"
    ],
    "prebakedTrainers": false
  },
  "mtpyre-4f": {
    "width": 208,
    "height": 208,
    "counts": {
      "trainer": 1,
      "item": 1,
      "hidden": 0,
      "berry": 0
    },
    "skippedInBase": 0,
    "layers": [
      "trainer",
      "item"
    ],
    "prebakedTrainers": false
  },
  "mtpyre-5f": {
    "width": 208,
    "height": 208,
    "counts": {
      "trainer": 1,
      "item": 1,
      "hidden": 0,
      "berry": 0
    },
    "skippedInBase": 0,
    "layers": [
      "trainer",
      "item"
    ],
    "prebakedTrainers": false
  },
  "mtpyre-6f": {
    "width": 208,
    "height": 208,
    "counts": {
      "trainer": 2,
      "item": 1,
      "hidden": 0,
      "berry": 0
    },
    "skippedInBase": 0,
    "layers": [
      "trainer",
      "item"
    ],
    "prebakedTrainers": false
  },
  "mtpyre-exterior": {
    "width": 608,
    "height": 816,
    "counts": {
      "trainer": 0,
      "item": 2,
      "hidden": 2,
      "berry": 0
    },
    "skippedInBase": 0,
    "layers": [
      "item",
      "hidden"
    ],
    "prebakedTrainers": false
  },
  "mtpyre-summit": {
    "width": 800,
    "height": 592,
    "counts": {
      "trainer": 4,
      "item": 0,
      "hidden": 2,
      "berry": 0
    },
    "skippedInBase": 0,
    "layers": [
      "trainer",
      "hidden"
    ],
    "prebakedTrainers": false
  },
  "navelrock-top": {
    "width": 400,
    "height": 448,
    "counts": {
      "trainer": 0,
      "item": 0,
      "hidden": 1,
      "berry": 0
    },
    "skippedInBase": 0,
    "layers": [
      "hidden"
    ],
    "prebakedTrainers": false
  },
  "route104-berry-plots": {
    "width": 240,
    "height": 160,
    "counts": {
      "trainer": 0,
      "item": 0,
      "hidden": 0,
      "berry": 1
    },
    "skippedInBase": 0,
    "layers": [
      "berry"
    ],
    "prebakedTrainers": false
  },
  "newmauville-inside": {
    "width": 656,
    "height": 656,
    "counts": {
      "trainer": 0,
      "item": 8,
      "hidden": 0,
      "berry": 0
    },
    "skippedInBase": 0,
    "layers": [
      "item"
    ],
    "prebakedTrainers": false
  },
  "petalburgwoods": {
    "width": 768,
    "height": 704,
    "counts": {
      "trainer": 0,
      "item": 4,
      "hidden": 4,
      "berry": 0
    },
    "skippedInBase": 2,
    "layers": [
      "item",
      "hidden"
    ],
    "prebakedTrainers": true
  },
  "route110-trickhouseend": {
    "width": 192,
    "height": 128,
    "counts": {
      "trainer": 0,
      "item": 0,
      "hidden": 1,
      "berry": 0
    },
    "skippedInBase": 0,
    "layers": [
      "hidden"
    ],
    "prebakedTrainers": false
  },
  "route110-trickhousepuzzle1": {
    "width": 240,
    "height": 352,
    "counts": {
      "trainer": 0,
      "item": 1,
      "hidden": 0,
      "berry": 0
    },
    "skippedInBase": 3,
    "layers": [
      "item"
    ],
    "prebakedTrainers": true
  },
  "route110-trickhousepuzzle2": {
    "width": 240,
    "height": 352,
    "counts": {
      "trainer": 0,
      "item": 2,
      "hidden": 0,
      "berry": 0
    },
    "skippedInBase": 3,
    "layers": [
      "item"
    ],
    "prebakedTrainers": true
  },
  "route110-trickhousepuzzle3": {
    "width": 240,
    "height": 352,
    "counts": {
      "trainer": 0,
      "item": 2,
      "hidden": 0,
      "berry": 0
    },
    "skippedInBase": 3,
    "layers": [
      "item"
    ],
    "prebakedTrainers": true
  },
  "route110-trickhousepuzzle4": {
    "width": 240,
    "height": 352,
    "counts": {
      "trainer": 0,
      "item": 1,
      "hidden": 0,
      "berry": 0
    },
    "skippedInBase": 3,
    "layers": [
      "item"
    ],
    "prebakedTrainers": true
  },
  "route110-trickhousepuzzle6": {
    "width": 240,
    "height": 352,
    "counts": {
      "trainer": 0,
      "item": 1,
      "hidden": 0,
      "berry": 0
    },
    "skippedInBase": 3,
    "layers": [
      "item"
    ],
    "prebakedTrainers": true
  },
  "route110-trickhousepuzzle7": {
    "width": 240,
    "height": 352,
    "counts": {
      "trainer": 0,
      "item": 1,
      "hidden": 0,
      "berry": 0
    },
    "skippedInBase": 6,
    "layers": [
      "item"
    ],
    "prebakedTrainers": true
  },
  "route110-trickhousepuzzle8": {
    "width": 240,
    "height": 352,
    "counts": {
      "trainer": 0,
      "item": 1,
      "hidden": 0,
      "berry": 0
    },
    "skippedInBase": 3,
    "layers": [
      "item"
    ],
    "prebakedTrainers": true
  },
  "rusturftunnel": {
    "width": 576,
    "height": 384,
    "counts": {
      "trainer": 0,
      "item": 2,
      "hidden": 0,
      "berry": 0
    },
    "skippedInBase": 1,
    "layers": [
      "item"
    ],
    "prebakedTrainers": true
  },
  "safarizone-north": {
    "width": 640,
    "height": 640,
    "counts": {
      "trainer": 0,
      "item": 1,
      "hidden": 0,
      "berry": 0
    },
    "skippedInBase": 0,
    "layers": [
      "item"
    ],
    "prebakedTrainers": false
  },
  "safarizone-northeast": {
    "width": 640,
    "height": 640,
    "counts": {
      "trainer": 0,
      "item": 1,
      "hidden": 2,
      "berry": 0
    },
    "skippedInBase": 0,
    "layers": [
      "item",
      "hidden"
    ],
    "prebakedTrainers": false
  },
  "safarizone-northwest": {
    "width": 640,
    "height": 640,
    "counts": {
      "trainer": 0,
      "item": 1,
      "hidden": 0,
      "berry": 0
    },
    "skippedInBase": 0,
    "layers": [
      "item"
    ],
    "prebakedTrainers": false
  },
  "safarizone-southeast": {
    "width": 640,
    "height": 640,
    "counts": {
      "trainer": 0,
      "item": 1,
      "hidden": 2,
      "berry": 0
    },
    "skippedInBase": 0,
    "layers": [
      "item",
      "hidden"
    ],
    "prebakedTrainers": false
  },
  "safarizone-southwest": {
    "width": 640,
    "height": 640,
    "counts": {
      "trainer": 0,
      "item": 1,
      "hidden": 0,
      "berry": 0
    },
    "skippedInBase": 0,
    "layers": [
      "item"
    ],
    "prebakedTrainers": false
  },
  "scorchedslab": {
    "width": 240,
    "height": 320,
    "counts": {
      "trainer": 0,
      "item": 1,
      "hidden": 0,
      "berry": 0
    },
    "skippedInBase": 0,
    "layers": [
      "item"
    ],
    "prebakedTrainers": false
  },
  "seafloorcavern-room9": {
    "width": 432,
    "height": 736,
    "counts": {
      "trainer": 0,
      "item": 1,
      "hidden": 0,
      "berry": 0
    },
    "skippedInBase": 0,
    "layers": [
      "item"
    ],
    "prebakedTrainers": false
  },
  "shoalcave-lowtideentranceroom": {
    "width": 560,
    "height": 560,
    "counts": {
      "trainer": 0,
      "item": 1,
      "hidden": 0,
      "berry": 0
    },
    "skippedInBase": 0,
    "layers": [
      "item"
    ],
    "prebakedTrainers": false
  },
  "shoalcave-lowtideiceroom": {
    "width": 320,
    "height": 480,
    "counts": {
      "trainer": 0,
      "item": 2,
      "hidden": 0,
      "berry": 0
    },
    "skippedInBase": 0,
    "layers": [
      "item"
    ],
    "prebakedTrainers": false
  },
  "shoalcave-lowtideinnerroom": {
    "width": 736,
    "height": 608,
    "counts": {
      "trainer": 0,
      "item": 1,
      "hidden": 0,
      "berry": 0
    },
    "skippedInBase": 0,
    "layers": [
      "item"
    ],
    "prebakedTrainers": false
  },
  "shoalcave-lowtidestairsroom": {
    "width": 336,
    "height": 240,
    "counts": {
      "trainer": 0,
      "item": 1,
      "hidden": 0,
      "berry": 0
    },
    "skippedInBase": 0,
    "layers": [
      "item"
    ],
    "prebakedTrainers": false
  },
  "sstidallowerdeck": {
    "width": 272,
    "height": 208,
    "counts": {
      "trainer": 0,
      "item": 0,
      "hidden": 1,
      "berry": 0
    },
    "skippedInBase": 2,
    "layers": [
      "hidden"
    ],
    "prebakedTrainers": true
  },
  "underwater-route124": {
    "width": 1280,
    "height": 1280,
    "counts": {
      "trainer": 0,
      "item": 0,
      "hidden": 7,
      "berry": 0
    },
    "skippedInBase": 0,
    "layers": [
      "hidden"
    ],
    "prebakedTrainers": false
  },
  "underwater-route126": {
    "width": 1280,
    "height": 1280,
    "counts": {
      "trainer": 0,
      "item": 0,
      "hidden": 8,
      "berry": 0
    },
    "skippedInBase": 0,
    "layers": [
      "hidden"
    ],
    "prebakedTrainers": false
  },
  "underwater-route127": {
    "width": 1280,
    "height": 1280,
    "counts": {
      "trainer": 0,
      "item": 0,
      "hidden": 4,
      "berry": 0
    },
    "skippedInBase": 0,
    "layers": [
      "hidden"
    ],
    "prebakedTrainers": false
  },
  "underwater-route128": {
    "width": 1920,
    "height": 640,
    "counts": {
      "trainer": 0,
      "item": 0,
      "hidden": 2,
      "berry": 0
    },
    "skippedInBase": 0,
    "layers": [
      "hidden"
    ],
    "prebakedTrainers": false
  },
  "victoryroad-1f": {
    "width": 736,
    "height": 720,
    "counts": {
      "trainer": 5,
      "item": 2,
      "hidden": 1,
      "berry": 0
    },
    "skippedInBase": 0,
    "layers": [
      "trainer",
      "item",
      "hidden"
    ],
    "prebakedTrainers": false
  },
  "victoryroad-b1f": {
    "width": 736,
    "height": 496,
    "counts": {
      "trainer": 5,
      "item": 2,
      "hidden": 0,
      "berry": 0
    },
    "skippedInBase": 0,
    "layers": [
      "trainer",
      "item"
    ],
    "prebakedTrainers": false
  },
  "victoryroad-b2f": {
    "width": 736,
    "height": 496,
    "counts": {
      "trainer": 6,
      "item": 1,
      "hidden": 2,
      "berry": 0
    },
    "skippedInBase": 0,
    "layers": [
      "trainer",
      "item",
      "hidden"
    ],
    "prebakedTrainers": false
  }
};

export const AREA_MAP_BAKE_SPRITE_SCALE = 1;
