// AUTO-GENERATED by scripts/gen-area-map-entrances.mjs — do not edit by hand.
// Cave/dungeon entrance, exit, and ladder pins with destination labels.
import type { AreaMapMarker } from "./areaMaps";

export interface AreaEntranceMarker extends AreaMapMarker {
  category: "entrance";
  /** Shared A/B/C code pairing this connector with its other end. */
  code?: string;
  /** pokeemerald dest_map constant. */
  destMap: string;
  destWarpId: string;
}

/** Entrance markers keyed by AREA_MAPS id. */
export const AREA_MAP_ENTRANCES: Record<string, AreaEntranceMarker[]> = {
  "abandonedship-captainsoffice": [
    { id: "aen-abandonedship-captainsoffice-0", name: "Door A to Deck", category: "entrance", x: 83.33, y: 92.86, desc: "Leads to Abandoned Ship Deck. Matches Door A on Deck.", code: "A", destMap: "MAP_ABANDONED_SHIP_DECK", destWarpId: "4" },
    { id: "aen-abandonedship-captainsoffice-1", name: "Door A to Deck", category: "entrance", x: 94.44, y: 92.86, desc: "Leads to Abandoned Ship Deck.", code: "A", destMap: "MAP_ABANDONED_SHIP_DECK", destWarpId: "4" },
  ],
  "abandonedship-hiddenfloorrooms": [
    { id: "aen-abandonedship-hiddenfloorrooms-0", name: "Door D to Hidden Floor Corridors", category: "entrance", x: 14.77, y: 96.67, desc: "Leads to Abandoned Ship Hidden Floor Corridors. Matches Door D on Hidden Floor Corridors.", code: "D", destMap: "MAP_ABANDONED_SHIP_HIDDEN_FLOOR_CORRIDORS", destWarpId: "0" },
    { id: "aen-abandonedship-hiddenfloorrooms-1", name: "Door D to Hidden Floor Corridors", category: "entrance", x: 17.05, y: 96.67, desc: "Leads to Abandoned Ship Hidden Floor Corridors.", code: "D", destMap: "MAP_ABANDONED_SHIP_HIDDEN_FLOOR_CORRIDORS", destWarpId: "0" },
    { id: "aen-abandonedship-hiddenfloorrooms-2", name: "Door E to Hidden Floor Corridors", category: "entrance", x: 48.86, y: 96.67, desc: "Leads to Abandoned Ship Hidden Floor Corridors. Matches Door E on Hidden Floor Corridors.", code: "E", destMap: "MAP_ABANDONED_SHIP_HIDDEN_FLOOR_CORRIDORS", destWarpId: "1" },
    { id: "aen-abandonedship-hiddenfloorrooms-3", name: "Door E to Hidden Floor Corridors", category: "entrance", x: 51.14, y: 96.67, desc: "Leads to Abandoned Ship Hidden Floor Corridors.", code: "E", destMap: "MAP_ABANDONED_SHIP_HIDDEN_FLOOR_CORRIDORS", destWarpId: "1" },
    { id: "aen-abandonedship-hiddenfloorrooms-4", name: "Door F to Hidden Floor Corridors", category: "entrance", x: 82.95, y: 96.67, desc: "Leads to Abandoned Ship Hidden Floor Corridors. Matches Door F on Hidden Floor Corridors.", code: "F", destMap: "MAP_ABANDONED_SHIP_HIDDEN_FLOOR_CORRIDORS", destWarpId: "2" },
    { id: "aen-abandonedship-hiddenfloorrooms-5", name: "Door F to Hidden Floor Corridors", category: "entrance", x: 85.23, y: 96.67, desc: "Leads to Abandoned Ship Hidden Floor Corridors.", code: "F", destMap: "MAP_ABANDONED_SHIP_HIDDEN_FLOOR_CORRIDORS", destWarpId: "2" },
    { id: "aen-abandonedship-hiddenfloorrooms-6", name: "Door A to Hidden Floor Corridors", category: "entrance", x: 14.77, y: 10, desc: "Leads to Abandoned Ship Hidden Floor Corridors. Matches Door A on Hidden Floor Corridors.", code: "A", destMap: "MAP_ABANDONED_SHIP_HIDDEN_FLOOR_CORRIDORS", destWarpId: "3" },
    { id: "aen-abandonedship-hiddenfloorrooms-7", name: "Door B to Hidden Floor Corridors", category: "entrance", x: 48.86, y: 10, desc: "Leads to Abandoned Ship Hidden Floor Corridors. Matches Door B on Hidden Floor Corridors.", code: "B", destMap: "MAP_ABANDONED_SHIP_HIDDEN_FLOOR_CORRIDORS", destWarpId: "4" },
    { id: "aen-abandonedship-hiddenfloorrooms-8", name: "Door C to Hidden Floor Corridors", category: "entrance", x: 82.95, y: 10, desc: "Leads to Abandoned Ship Hidden Floor Corridors. Matches Door C on Hidden Floor Corridors.", code: "C", destMap: "MAP_ABANDONED_SHIP_HIDDEN_FLOOR_CORRIDORS", destWarpId: "5" },
  ],
  "abandonedship-room-b1f": [
    { id: "aen-abandonedship-room-b1f-0", name: "Door E to B1F", category: "entrance", x: 50, y: 93.75, desc: "Leads to Abandoned Ship Corridors B1F. Matches Door E on B1F.", code: "E", destMap: "MAP_ABANDONED_SHIP_CORRIDORS_B1F", destWarpId: "5" },
    { id: "aen-abandonedship-room-b1f-1", name: "Door E to B1F", category: "entrance", x: 61.11, y: 93.75, desc: "Leads to Abandoned Ship Corridors B1F.", code: "E", destMap: "MAP_ABANDONED_SHIP_CORRIDORS_B1F", destWarpId: "5" },
  ],
  "abandonedship-rooms-1f": [
    { id: "aen-abandonedship-rooms-1f-0", name: "Door I to 1F", category: "entrance", x: 25, y: 97.06, desc: "Leads to Abandoned Ship Corridors 1F. Matches Door I on 1F.", code: "I", destMap: "MAP_ABANDONED_SHIP_CORRIDORS_1F", destWarpId: "4" },
    { id: "aen-abandonedship-rooms-1f-1", name: "Door I to 1F", category: "entrance", x: 30.56, y: 97.06, desc: "Leads to Abandoned Ship Corridors 1F.", code: "I", destMap: "MAP_ABANDONED_SHIP_CORRIDORS_1F", destWarpId: "4" },
    { id: "aen-abandonedship-rooms-1f-2", name: "Door D to 1F", category: "entrance", x: 25, y: 8.82, desc: "Leads to Abandoned Ship Corridors 1F. Matches Door D on 1F.", code: "D", destMap: "MAP_ABANDONED_SHIP_CORRIDORS_1F", destWarpId: "6" },
    { id: "aen-abandonedship-rooms-1f-3", name: "Door J to 1F", category: "entrance", x: 75, y: 97.06, desc: "Leads to Abandoned Ship Corridors 1F. Matches Door J on 1F.", code: "J", destMap: "MAP_ABANDONED_SHIP_CORRIDORS_1F", destWarpId: "5" },
    { id: "aen-abandonedship-rooms-1f-4", name: "Door E to 1F", category: "entrance", x: 75, y: 8.82, desc: "Leads to Abandoned Ship Corridors 1F. Matches Door E on 1F.", code: "E", destMap: "MAP_ABANDONED_SHIP_CORRIDORS_1F", destWarpId: "7" },
    { id: "aen-abandonedship-rooms-1f-5", name: "Door J to 1F", category: "entrance", x: 80.56, y: 97.06, desc: "Leads to Abandoned Ship Corridors 1F.", code: "J", destMap: "MAP_ABANDONED_SHIP_CORRIDORS_1F", destWarpId: "5" },
  ],
  "abandonedship-rooms-b1f": [
    { id: "aen-abandonedship-rooms-b1f-0", name: "Door A to B1F", category: "entrance", x: 16.67, y: 18.75, desc: "Leads to Abandoned Ship Corridors B1F. Matches Door A on B1F.", code: "A", destMap: "MAP_ABANDONED_SHIP_CORRIDORS_B1F", destWarpId: "2" },
    { id: "aen-abandonedship-rooms-b1f-1", name: "Door B to B1F", category: "entrance", x: 50, y: 18.75, desc: "Leads to Abandoned Ship Corridors B1F. Matches Door B on B1F.", code: "B", destMap: "MAP_ABANDONED_SHIP_CORRIDORS_B1F", destWarpId: "3" },
    { id: "aen-abandonedship-rooms-b1f-2", name: "Door C to B1F", category: "entrance", x: 83.33, y: 18.75, desc: "Leads to Abandoned Ship Corridors B1F. Matches Door C on B1F.", code: "C", destMap: "MAP_ABANDONED_SHIP_CORRIDORS_B1F", destWarpId: "4" },
  ],
  "abandonedship-rooms2-1f": [
    { id: "aen-abandonedship-rooms2-1f-0", name: "Door H to 1F", category: "entrance", x: 50, y: 97.06, desc: "Leads to Abandoned Ship Corridors 1F. Matches Door H on 1F.", code: "H", destMap: "MAP_ABANDONED_SHIP_CORRIDORS_1F", destWarpId: "8" },
    { id: "aen-abandonedship-rooms2-1f-1", name: "Door H to 1F", category: "entrance", x: 61.11, y: 97.06, desc: "Leads to Abandoned Ship Corridors 1F.", code: "H", destMap: "MAP_ABANDONED_SHIP_CORRIDORS_1F", destWarpId: "8" },
    { id: "aen-abandonedship-rooms2-1f-2", name: "Door A to 1F", category: "entrance", x: 50, y: 8.82, desc: "Leads to Abandoned Ship Corridors 1F. Matches Door A on 1F.", code: "A", destMap: "MAP_ABANDONED_SHIP_CORRIDORS_1F", destWarpId: "11" },
  ],
  "abandonedship-rooms2-b1f": [
    { id: "aen-abandonedship-rooms2-b1f-0", name: "Door D to B1F", category: "entrance", x: 25, y: 93.75, desc: "Leads to Abandoned Ship Corridors B1F. Matches Door D on B1F.", code: "D", destMap: "MAP_ABANDONED_SHIP_CORRIDORS_B1F", destWarpId: "1" },
    { id: "aen-abandonedship-rooms2-b1f-1", name: "Door D to B1F", category: "entrance", x: 30.56, y: 93.75, desc: "Leads to Abandoned Ship Corridors B1F.", code: "D", destMap: "MAP_ABANDONED_SHIP_CORRIDORS_B1F", destWarpId: "1" },
    { id: "aen-abandonedship-rooms2-b1f-2", name: "Door H to B1F", category: "entrance", x: 75, y: 93.75, desc: "Leads to Abandoned Ship Corridors B1F. Matches Door H on B1F.", code: "H", destMap: "MAP_ABANDONED_SHIP_CORRIDORS_B1F", destWarpId: "0" },
    { id: "aen-abandonedship-rooms2-b1f-3", name: "Door H to B1F", category: "entrance", x: 80.56, y: 93.75, desc: "Leads to Abandoned Ship Corridors B1F.", code: "H", destMap: "MAP_ABANDONED_SHIP_CORRIDORS_B1F", destWarpId: "0" },
  ],
  "aquahideout-b1f": [
    { id: "aen-aquahideout-b1f-0", name: "Warp A to 1F", category: "entrance", x: 57.84, y: 6.25, desc: "Goes up to Aqua Hideout 1F. Matches Warp A on 1F.", code: "A", destMap: "MAP_AQUA_HIDEOUT_1F", destWarpId: "2" },
    { id: "aen-aquahideout-b1f-1", name: "Warp C to B2F", category: "entrance", x: 36.27, y: 6.25, desc: "Goes down to Aqua Hideout B2F. Matches Warp C on B2F.", code: "C", destMap: "MAP_AQUA_HIDEOUT_B2F", destWarpId: "0" },
    { id: "aen-aquahideout-b1f-2", name: "Warp B to B2F", category: "entrance", x: 24.51, y: 6.25, desc: "Goes down to Aqua Hideout B2F. Matches Warp B on B2F.", code: "B", destMap: "MAP_AQUA_HIDEOUT_B2F", destWarpId: "1" },
    { id: "aen-aquahideout-b1f-3", name: "Warp D to B2F", category: "entrance", x: 6.86, y: 14.58, desc: "Goes down to Aqua Hideout B2F. Matches Warp D on B2F.", code: "D", destMap: "MAP_AQUA_HIDEOUT_B2F", destWarpId: "2" },
    { id: "aen-aquahideout-b1f-4", name: "Warp H to B1F", category: "entrance", x: 61.76, y: 18.75, desc: "Leads to Aqua Hideout B1F. Matches Warp H on B1F.", code: "H", destMap: "MAP_AQUA_HIDEOUT_B1F", destWarpId: "7" },
    { id: "aen-aquahideout-b1f-5", name: "Warp F to B1F", category: "entrance", x: 53.92, y: 18.75, desc: "Leads to Aqua Hideout B1F. Matches Warp F on B1F.", code: "F", destMap: "MAP_AQUA_HIDEOUT_B1F", destWarpId: "8" },
    { id: "aen-aquahideout-b1f-6", name: "Warp G to B1F", category: "entrance", x: 40.2, y: 18.75, desc: "Leads to Aqua Hideout B1F. Matches Warp G on B1F.", code: "G", destMap: "MAP_AQUA_HIDEOUT_B1F", destWarpId: "10" },
    { id: "aen-aquahideout-b1f-7", name: "Warp H to B1F", category: "entrance", x: 53.92, y: 52.08, desc: "Leads to Aqua Hideout B1F. Matches Warp H on B1F.", code: "H", destMap: "MAP_AQUA_HIDEOUT_B1F", destWarpId: "4" },
    { id: "aen-aquahideout-b1f-8", name: "Warp F to B1F", category: "entrance", x: 6.86, y: 64.58, desc: "Leads to Aqua Hideout B1F. Matches Warp F on B1F.", code: "F", destMap: "MAP_AQUA_HIDEOUT_B1F", destWarpId: "5" },
    { id: "aen-aquahideout-b1f-9", name: "Warp E to B1F", category: "entrance", x: 6.86, y: 85.42, desc: "Leads to Aqua Hideout B1F. Matches Warp E on B1F.", code: "E", destMap: "MAP_AQUA_HIDEOUT_B1F", destWarpId: "12" },
    { id: "aen-aquahideout-b1f-10", name: "Warp G to B1F", category: "entrance", x: 63.73, y: 81.25, desc: "Leads to Aqua Hideout B1F. Matches Warp G on B1F.", code: "G", destMap: "MAP_AQUA_HIDEOUT_B1F", destWarpId: "6" },
    { id: "aen-aquahideout-b1f-11", name: "Warp M to B1F", category: "entrance", x: 46.08, y: 43.75, desc: "Leads to Aqua Hideout B1F. Matches Warp M on B1F.", code: "M", destMap: "MAP_AQUA_HIDEOUT_B1F", destWarpId: "22" },
    { id: "aen-aquahideout-b1f-12", name: "Warp E to B1F", category: "entrance", x: 89.22, y: 14.58, desc: "Leads to Aqua Hideout B1F. Matches Warp E on B1F.", code: "E", destMap: "MAP_AQUA_HIDEOUT_B1F", destWarpId: "9" },
    { id: "aen-aquahideout-b1f-13", name: "Warp I to B1F", category: "entrance", x: 83.33, y: 22.92, desc: "Leads to Aqua Hideout B1F. Matches Warp I on B1F.", code: "I", destMap: "MAP_AQUA_HIDEOUT_B1F", destWarpId: "18" },
    { id: "aen-aquahideout-b1f-14", name: "Warp K to B1F", category: "entrance", x: 89.22, y: 22.92, desc: "Leads to Aqua Hideout B1F.", code: "K", destMap: "MAP_AQUA_HIDEOUT_B1F", destWarpId: "12" },
    { id: "aen-aquahideout-b1f-15", name: "Warp J to B1F", category: "entrance", x: 95.1, y: 22.92, desc: "Leads to Aqua Hideout B1F. Matches Warp J on B1F.", code: "J", destMap: "MAP_AQUA_HIDEOUT_B1F", destWarpId: "16" },
    { id: "aen-aquahideout-b1f-16", name: "Warp J to B1F", category: "entrance", x: 83.33, y: 39.58, desc: "Leads to Aqua Hideout B1F. Matches Warp J on B1F.", code: "J", destMap: "MAP_AQUA_HIDEOUT_B1F", destWarpId: "15" },
    { id: "aen-aquahideout-b1f-17", name: "Warp L to B1F", category: "entrance", x: 89.22, y: 39.58, desc: "Leads to Aqua Hideout B1F. Matches Warp L on B1F.", code: "L", destMap: "MAP_AQUA_HIDEOUT_B1F", destWarpId: "20" },
    { id: "aen-aquahideout-b1f-18", name: "Warp I to B1F", category: "entrance", x: 95.1, y: 39.58, desc: "Leads to Aqua Hideout B1F. Matches Warp I on B1F.", code: "I", destMap: "MAP_AQUA_HIDEOUT_B1F", destWarpId: "13" },
    { id: "aen-aquahideout-b1f-19", name: "Warp N to B1F", category: "entrance", x: 83.33, y: 56.25, desc: "Leads to Aqua Hideout B1F. Matches Warp N on B1F.", code: "N", destMap: "MAP_AQUA_HIDEOUT_B1F", destWarpId: "24" },
    { id: "aen-aquahideout-b1f-20", name: "Warp L to B1F", category: "entrance", x: 89.22, y: 56.25, desc: "Leads to Aqua Hideout B1F. Matches Warp L on B1F.", code: "L", destMap: "MAP_AQUA_HIDEOUT_B1F", destWarpId: "17" },
    { id: "aen-aquahideout-b1f-21", name: "Warp O to B1F", category: "entrance", x: 95.1, y: 56.25, desc: "Leads to Aqua Hideout B1F.", code: "O", destMap: "MAP_AQUA_HIDEOUT_B1F", destWarpId: "12" },
    { id: "aen-aquahideout-b1f-22", name: "Warp M to B1F", category: "entrance", x: 83.33, y: 72.92, desc: "Leads to Aqua Hideout B1F. Matches Warp M on B1F.", code: "M", destMap: "MAP_AQUA_HIDEOUT_B1F", destWarpId: "11" },
    { id: "aen-aquahideout-b1f-23", name: "Warp P to B1F", category: "entrance", x: 89.22, y: 72.92, desc: "Leads to Aqua Hideout B1F.", code: "P", destMap: "MAP_AQUA_HIDEOUT_B1F", destWarpId: "17" },
    { id: "aen-aquahideout-b1f-24", name: "Warp N to B1F", category: "entrance", x: 95.1, y: 72.92, desc: "Leads to Aqua Hideout B1F. Matches Warp N on B1F.", code: "N", destMap: "MAP_AQUA_HIDEOUT_B1F", destWarpId: "19" },
  ],
  "aquahideout-b2f": [
    { id: "aen-aquahideout-b2f-0", name: "Warp C to B1F", category: "entrance", x: 54.41, y: 6.25, desc: "Goes up to Aqua Hideout B1F. Matches Warp C on B1F.", code: "C", destMap: "MAP_AQUA_HIDEOUT_B1F", destWarpId: "1" },
    { id: "aen-aquahideout-b2f-1", name: "Warp B to B1F", category: "entrance", x: 36.76, y: 6.25, desc: "Goes up to Aqua Hideout B1F. Matches Warp B on B1F.", code: "B", destMap: "MAP_AQUA_HIDEOUT_B1F", destWarpId: "2" },
    { id: "aen-aquahideout-b2f-2", name: "Warp D to B1F", category: "entrance", x: 10.29, y: 14.58, desc: "Goes up to Aqua Hideout B1F. Matches Warp D on B1F.", code: "D", destMap: "MAP_AQUA_HIDEOUT_B1F", destWarpId: "3" },
    { id: "aen-aquahideout-b2f-3", name: "Warp A to B2F", category: "entrance", x: 92.65, y: 35.42, desc: "Leads to Aqua Hideout B2F. Matches Warp A on B2F.", code: "A", destMap: "MAP_AQUA_HIDEOUT_B2F", destWarpId: "5" },
    { id: "aen-aquahideout-b2f-4", name: "Warp E to B2F", category: "entrance", x: 25, y: 35.42, desc: "Leads to Aqua Hideout B2F. Matches Warp E on B2F.", code: "E", destMap: "MAP_AQUA_HIDEOUT_B2F", destWarpId: "8" },
    { id: "aen-aquahideout-b2f-5", name: "Warp A to B2F", category: "entrance", x: 16.18, y: 35.42, desc: "Leads to Aqua Hideout B2F. Matches Warp A on B2F.", code: "A", destMap: "MAP_AQUA_HIDEOUT_B2F", destWarpId: "3" },
    { id: "aen-aquahideout-b2f-6", name: "Warp F to B2F", category: "entrance", x: 54.41, y: 56.25, desc: "Leads to Aqua Hideout B2F. Matches Warp F on B2F.", code: "F", destMap: "MAP_AQUA_HIDEOUT_B2F", destWarpId: "7" },
    { id: "aen-aquahideout-b2f-7", name: "Warp F to B2F", category: "entrance", x: 36.76, y: 56.25, desc: "Leads to Aqua Hideout B2F. Matches Warp F on B2F.", code: "F", destMap: "MAP_AQUA_HIDEOUT_B2F", destWarpId: "6" },
    { id: "aen-aquahideout-b2f-8", name: "Warp E to B2F", category: "entrance", x: 92.65, y: 72.92, desc: "Leads to Aqua Hideout B2F. Matches Warp E on B2F.", code: "E", destMap: "MAP_AQUA_HIDEOUT_B2F", destWarpId: "4" },
    { id: "aen-aquahideout-b2f-9", name: "Warp G to B1F", category: "entrance", x: 95.59, y: 85.42, desc: "Goes up to Aqua Hideout B1F.", code: "G", destMap: "MAP_AQUA_HIDEOUT_B1F", destWarpId: "4" },
  ],
  "artisancave-1f": [
    { id: "aen-artisancave-1f-0", name: "Exit to Battle Frontier Outside East — north", category: "entrance", x: 50, y: 79.55, desc: "Leaves Artisan Cave 1F for Battle Frontier Outside East (north).", destMap: "MAP_BATTLE_FRONTIER_OUTSIDE_EAST", destWarpId: "13" },
    { id: "aen-artisancave-1f-1", name: "Ladder A to B1F", category: "entrance", x: 30.95, y: 25, desc: "Goes down to Artisan Cave B1F. Matches Ladder A on B1F.", code: "A", destMap: "MAP_ARTISAN_CAVE_B1F", destWarpId: "1" },
  ],
  "artisancave-b1f": [
    { id: "aen-artisancave-b1f-0", name: "Exit to Battle Frontier Outside West — southwest", category: "entrance", x: 18.48, y: 89.81, desc: "Leaves Artisan Cave B1F for Battle Frontier Outside West (southwest).", destMap: "MAP_BATTLE_FRONTIER_OUTSIDE_WEST", destWarpId: "10" },
    { id: "aen-artisancave-b1f-1", name: "Ladder A to 1F", category: "entrance", x: 83.7, y: 10.19, desc: "Goes up to Artisan Cave 1F. Matches Ladder A on 1F.", code: "A", destMap: "MAP_ARTISAN_CAVE_1F", destWarpId: "1" },
  ],
  "fierypath": [
    { id: "aen-fierypath-0", name: "Exit to Route 112 — southeast", category: "entrance", x: 75.71, y: 96.05, desc: "Leaves Fiery Path for Route 112 (southeast).", destMap: "MAP_ROUTE112", destWarpId: "4" },
    { id: "aen-fierypath-1", name: "Exit to Route 112 — north", category: "entrance", x: 75.71, y: 11.84, desc: "Leaves Fiery Path for Route 112 (north).", destMap: "MAP_ROUTE112", destWarpId: "5" },
  ],
  "granitecave-1f": [
    { id: "aen-granitecave-1f-0", name: "Exit to Route 106 — southeast", category: "entrance", x: 89.29, y: 83.33, desc: "Leaves Granite Cave 1F for Route 106 (southeast).", destMap: "MAP_ROUTE106", destWarpId: "0" },
    { id: "aen-granitecave-1f-1", name: "Ladder A to B1F", category: "entrance", x: 84.52, y: 23.33, desc: "Goes down to Granite Cave B1F. Matches Ladder A on B1F.", code: "A", destMap: "MAP_GRANITE_CAVE_B1F", destWarpId: "0" },
    { id: "aen-granitecave-1f-2", name: "Ladder C to B1F", category: "entrance", x: 41.67, y: 76.67, desc: "Goes down to Granite Cave B1F. Matches Ladder C on B1F.", code: "C", destMap: "MAP_GRANITE_CAVE_B1F", destWarpId: "1" },
    { id: "aen-granitecave-1f-3", name: "Door B to Steven's Room", category: "entrance", x: 13.1, y: 70, desc: "Leads to Granite Cave Steven's Room. Matches Door B on Steven's Room.", code: "B", destMap: "MAP_GRANITE_CAVE_STEVENS_ROOM", destWarpId: "0" },
  ],
  "granitecave-b1f": [
    { id: "aen-granitecave-b1f-0", name: "Ladder A to 1F", category: "entrance", x: 79.69, y: 51.92, desc: "Goes up to Granite Cave 1F. Matches Ladder A on 1F.", code: "A", destMap: "MAP_GRANITE_CAVE_1F", destWarpId: "1" },
    { id: "aen-granitecave-b1f-1", name: "Ladder C to 1F", category: "entrance", x: 14.06, y: 82.69, desc: "Goes up to Granite Cave 1F. Matches Ladder C on 1F.", code: "C", destMap: "MAP_GRANITE_CAVE_1F", destWarpId: "2" },
    { id: "aen-granitecave-b1f-2", name: "Ladder F to B2F", category: "entrance", x: 92.19, y: 51.92, desc: "Goes down to Granite Cave B2F. Matches Ladder F on B2F.", code: "F", destMap: "MAP_GRANITE_CAVE_B2F", destWarpId: "0" },
    { id: "aen-granitecave-b1f-3", name: "Ladder G to B2F", category: "entrance", x: 89.06, y: 82.69, desc: "Goes down to Granite Cave B2F. Matches Ladder G on B2F.", code: "G", destMap: "MAP_GRANITE_CAVE_B2F", destWarpId: "1" },
    { id: "aen-granitecave-b1f-4", name: "Ladder E to B2F", category: "entrance", x: 26.56, y: 21.15, desc: "Goes down to Granite Cave B2F. Matches Ladder E on B2F.", code: "E", destMap: "MAP_GRANITE_CAVE_B2F", destWarpId: "2" },
    { id: "aen-granitecave-b1f-5", name: "Ladder D to B2F", category: "entrance", x: 39.06, y: 13.46, desc: "Goes down to Granite Cave B2F. Matches Ladder D on B2F.", code: "D", destMap: "MAP_GRANITE_CAVE_B2F", destWarpId: "3" },
    { id: "aen-granitecave-b1f-6", name: "Ladder B to B2F", category: "entrance", x: 92.19, y: 9.62, desc: "Goes down to Granite Cave B2F. Matches Ladder B on B2F.", code: "B", destMap: "MAP_GRANITE_CAVE_B2F", destWarpId: "4" },
  ],
  "granitecave-b2f": [
    { id: "aen-granitecave-b2f-0", name: "Ladder F to B1F", category: "entrance", x: 92.19, y: 51.92, desc: "Goes up to Granite Cave B1F. Matches Ladder F on B1F.", code: "F", destMap: "MAP_GRANITE_CAVE_B1F", destWarpId: "2" },
    { id: "aen-granitecave-b2f-1", name: "Ladder G to B1F", category: "entrance", x: 89.06, y: 82.69, desc: "Goes up to Granite Cave B1F. Matches Ladder G on B1F.", code: "G", destMap: "MAP_GRANITE_CAVE_B1F", destWarpId: "3" },
    { id: "aen-granitecave-b2f-2", name: "Ladder E to B1F", category: "entrance", x: 26.56, y: 21.15, desc: "Goes up to Granite Cave B1F. Matches Ladder E on B1F.", code: "E", destMap: "MAP_GRANITE_CAVE_B1F", destWarpId: "4" },
    { id: "aen-granitecave-b2f-3", name: "Ladder D to B1F", category: "entrance", x: 39.06, y: 13.46, desc: "Goes up to Granite Cave B1F. Matches Ladder D on B1F.", code: "D", destMap: "MAP_GRANITE_CAVE_B1F", destWarpId: "5" },
    { id: "aen-granitecave-b2f-4", name: "Ladder B to B1F", category: "entrance", x: 92.19, y: 9.62, desc: "Goes up to Granite Cave B1F. Matches Ladder B on B1F.", code: "B", destMap: "MAP_GRANITE_CAVE_B1F", destWarpId: "6" },
  ],
  "granitecave-stevensroom": [
    { id: "aen-granitecave-stevensroom-0", name: "Door B to 1F", category: "entrance", x: 50, y: 25, desc: "Leads to Granite Cave 1F. Matches Door B on 1F.", code: "B", destMap: "MAP_GRANITE_CAVE_1F", destWarpId: "3" },
  ],
  "jaggedpass": [
    { id: "aen-jaggedpass-0", name: "Exit to Route 112 — south", category: "entrance", x: 48.33, y: 88.04, desc: "Leaves Jagged Pass for Route 112 (south).", destMap: "MAP_ROUTE112", destWarpId: "2" },
    { id: "aen-jaggedpass-1", name: "Exit to Route 112 — south", category: "entrance", x: 51.67, y: 88.04, desc: "Leaves Jagged Pass for Route 112 (south).", destMap: "MAP_ROUTE112", destWarpId: "3" },
    { id: "aen-jaggedpass-2", name: "Exit to Mt Chimney — north", category: "entrance", x: 45, y: 11.96, desc: "Leaves Jagged Pass for Mt Chimney (north).", destMap: "MAP_MT_CHIMNEY", destWarpId: "2" },
    { id: "aen-jaggedpass-3", name: "Exit to Mt Chimney — north", category: "entrance", x: 48.33, y: 11.96, desc: "Leaves Jagged Pass for Mt Chimney (north).", destMap: "MAP_MT_CHIMNEY", destWarpId: "3" },
    { id: "aen-jaggedpass-4", name: "Exit to Magma Hideout 1F — south", category: "entrance", x: 55, y: 40.22, desc: "Leaves Jagged Pass for Magma Hideout 1F (south).", destMap: "MAP_MAGMA_HIDEOUT_1F", destWarpId: "0" },
  ],
  "magmahideout-1f": [
    { id: "aen-magmahideout-1f-0", name: "Exit to Jagged Pass — southwest", category: "entrance", x: 28.38, y: 90.79, desc: "Leaves Magma Hideout 1F for Jagged Pass (southwest).", destMap: "MAP_JAGGED_PASS", destWarpId: "4" },
    { id: "aen-magmahideout-1f-1", name: "Door C to 1R", category: "entrance", x: 68.92, y: 90.79, desc: "Leads to Magma Hideout 2F 1R. Matches Door C on 1R.", code: "C", destMap: "MAP_MAGMA_HIDEOUT_2F_1R", destWarpId: "1" },
    { id: "aen-magmahideout-1f-2", name: "Door A to 2R", category: "entrance", x: 85.14, y: 9.21, desc: "Leads to Magma Hideout 2F 2R. Matches Door A on 2R.", code: "A", destMap: "MAP_MAGMA_HIDEOUT_2F_2R", destWarpId: "1" },
    { id: "aen-magmahideout-1f-3", name: "Door B to 3R", category: "entrance", x: 55.41, y: 59.21, desc: "Leads to Magma Hideout 2F 3R. Matches Door B on 3R.", code: "B", destMap: "MAP_MAGMA_HIDEOUT_2F_3R", destWarpId: "0" },
  ],
  "magmahideout-2f-2r": [
    { id: "aen-magmahideout-2f-2r-0", name: "Door D to 1R", category: "entrance", x: 21.43, y: 80.36, desc: "Leads to Magma Hideout 2F 1R. Matches Door D on 1R.", code: "D", destMap: "MAP_MAGMA_HIDEOUT_2F_1R", destWarpId: "0" },
    { id: "aen-magmahideout-2f-2r-1", name: "Door A to 1F", category: "entrance", x: 74.49, y: 16.07, desc: "Leads to Magma Hideout 1F. Matches Door A on 1F.", code: "A", destMap: "MAP_MAGMA_HIDEOUT_1F", destWarpId: "2" },
  ],
  "magmahideout-3f-1r": [
    { id: "aen-magmahideout-3f-1r-0", name: "Door A to 4F", category: "entrance", x: 26.79, y: 89.58, desc: "Leads to Magma Hideout 4F. Matches Door A on 4F.", code: "A", destMap: "MAP_MAGMA_HIDEOUT_4F", destWarpId: "0" },
    { id: "aen-magmahideout-3f-1r-1", name: "Door C to 2R", category: "entrance", x: 76.79, y: 39.58, desc: "Leads to Magma Hideout 3F 2R. Matches Door C on 2R.", code: "C", destMap: "MAP_MAGMA_HIDEOUT_3F_2R", destWarpId: "0" },
    { id: "aen-magmahideout-3f-1r-2", name: "Door B to 1R", category: "entrance", x: 83.93, y: 14.58, desc: "Leads to Magma Hideout 2F 1R. Matches Door B on 1R.", code: "B", destMap: "MAP_MAGMA_HIDEOUT_2F_1R", destWarpId: "2" },
  ],
  "magmahideout-3f-2r": [
    { id: "aen-magmahideout-3f-2r-0", name: "Door C to 1R", category: "entrance", x: 52.08, y: 91.18, desc: "Leads to Magma Hideout 3F 1R. Matches Door C on 1R.", code: "C", destMap: "MAP_MAGMA_HIDEOUT_3F_1R", destWarpId: "1" },
  ],
  "magmahideout-3f-3r": [
    { id: "aen-magmahideout-3f-3r-0", name: "Door A to 3R", category: "entrance", x: 50, y: 6.25, desc: "Leads to Magma Hideout 2F 3R. Matches Door A on 3R.", code: "A", destMap: "MAP_MAGMA_HIDEOUT_2F_3R", destWarpId: "1" },
    { id: "aen-magmahideout-3f-3r-1", name: "Door B to 4F", category: "entrance", x: 50, y: 89.58, desc: "Leads to Magma Hideout 4F. Matches Door B on 4F.", code: "B", destMap: "MAP_MAGMA_HIDEOUT_4F", destWarpId: "1" },
  ],
  "magmahideout-4f": [
    { id: "aen-magmahideout-4f-0", name: "Door A to 1R", category: "entrance", x: 78.81, y: 26.79, desc: "Leads to Magma Hideout 3F 1R. Matches Door A on 1R.", code: "A", destMap: "MAP_MAGMA_HIDEOUT_3F_1R", destWarpId: "0" },
    { id: "aen-magmahideout-4f-1", name: "Door B to 3R", category: "entrance", x: 34.75, y: 76.79, desc: "Leads to Magma Hideout 3F 3R. Matches Door B on 3R.", code: "B", destMap: "MAP_MAGMA_HIDEOUT_3F_3R", destWarpId: "1" },
  ],
  "meteorfalls-1f-1r": [
    { id: "aen-meteorfalls-1f-1r-0", name: "Exit to Route 114 — east", category: "entrance", x: 91.67, y: 44.05, desc: "Leaves Meteor Falls 1F 1R for Route 114 (east).", destMap: "MAP_ROUTE114", destWarpId: "0" },
    { id: "aen-meteorfalls-1f-1r-1", name: "Exit to Route 115 — southwest", category: "entrance", x: 21.67, y: 94.05, desc: "Leaves Meteor Falls 1F 1R for Route 115 (southwest).", destMap: "MAP_ROUTE115", destWarpId: "0" },
    { id: "aen-meteorfalls-1f-1r-2", name: "Door B to 2R", category: "entrance", x: 35, y: 8.33, desc: "Leads to Meteor Falls 1F 2R. Matches Door B on 2R.", code: "B", destMap: "MAP_METEOR_FALLS_1F_2R", destWarpId: "0" },
    { id: "aen-meteorfalls-1f-1r-3", name: "Door C to 1R", category: "entrance", x: 18.33, y: 10.71, desc: "Leads to Meteor Falls B 1F 1R. Matches Door C on 1R.", code: "C", destMap: "MAP_METEOR_FALLS_B1F_1R", destWarpId: "4" },
    { id: "aen-meteorfalls-1f-1r-4", name: "Door G to 1R", category: "entrance", x: 88.33, y: 67.86, desc: "Leads to Meteor Falls B 1F 1R. Matches Door G on 1R.", code: "G", destMap: "MAP_METEOR_FALLS_B1F_1R", destWarpId: "5" },
    { id: "aen-meteorfalls-1f-1r-5", name: "Door A to Steven's Cave", category: "entrance", x: 15, y: 5.95, desc: "Leads to Meteor Falls Steven's Cave. Matches Door A on Steven's Cave.", code: "A", destMap: "MAP_METEOR_FALLS_STEVENS_CAVE", destWarpId: "0" },
  ],
  "meteorfalls-b1f-2r": [
    { id: "aen-meteorfalls-b1f-2r-0", name: "Door A to 1R", category: "entrance", x: 50, y: 86.11, desc: "Leads to Meteor Falls B 1F 1R. Matches Door A on 1R.", code: "A", destMap: "MAP_METEOR_FALLS_B1F_1R", destWarpId: "3" },
  ],
  "mtpyre-2f": [
    { id: "aen-mtpyre-2f-0", name: "Stairs A to 1F", category: "entrance", x: 19.23, y: 11.54, desc: "Goes down to Mt Pyre 1F. Matches Stairs A on 1F.", code: "A", destMap: "MAP_MT_PYRE_1F", destWarpId: "4" },
    { id: "aen-mtpyre-2f-1", name: "Stairs C to 3F", category: "entrance", x: 80.77, y: 11.54, desc: "Goes up to Mt Pyre 3F. Matches Stairs C on 3F.", code: "C", destMap: "MAP_MT_PYRE_3F", destWarpId: "0" },
    { id: "aen-mtpyre-2f-2", name: "Stairs E to 3F", category: "entrance", x: 80.77, y: 96.15, desc: "Goes up to Mt Pyre 3F. Matches Stairs E on 3F.", code: "E", destMap: "MAP_MT_PYRE_3F", destWarpId: "4" },
    { id: "aen-mtpyre-2f-3", name: "Stairs D to 3F", category: "entrance", x: 50, y: 96.15, desc: "Goes up to Mt Pyre 3F. Matches Stairs D on 3F.", code: "D", destMap: "MAP_MT_PYRE_3F", destWarpId: "5" },
    { id: "aen-mtpyre-2f-4", name: "Stairs F to 1F", category: "entrance", x: 88.46, y: 73.08, desc: "Goes down to Mt Pyre 1F. Matches Stairs F on 1F.", code: "F", destMap: "MAP_MT_PYRE_1F", destWarpId: "5" },
  ],
  "mtpyre-3f": [
    { id: "aen-mtpyre-3f-0", name: "Stairs C to 2F", category: "entrance", x: 80.77, y: 11.54, desc: "Goes down to Mt Pyre 2F. Matches Stairs C on 2F.", code: "C", destMap: "MAP_MT_PYRE_2F", destWarpId: "1" },
    { id: "aen-mtpyre-3f-1", name: "Stairs A to 4F", category: "entrance", x: 19.23, y: 11.54, desc: "Goes up to Mt Pyre 4F. Matches Stairs A on 4F.", code: "A", destMap: "MAP_MT_PYRE_4F", destWarpId: "1" },
    { id: "aen-mtpyre-3f-2", name: "Stairs B to 4F", category: "entrance", x: 73.08, y: 80.77, desc: "Goes up to Mt Pyre 4F. Matches Stairs B on 4F.", code: "B", destMap: "MAP_MT_PYRE_4F", destWarpId: "4" },
    { id: "aen-mtpyre-3f-3", name: "Stairs F to 4F", category: "entrance", x: 11.54, y: 96.15, desc: "Goes up to Mt Pyre 4F. Matches Stairs F on 4F.", code: "F", destMap: "MAP_MT_PYRE_4F", destWarpId: "5" },
    { id: "aen-mtpyre-3f-4", name: "Stairs E to 2F", category: "entrance", x: 80.77, y: 96.15, desc: "Goes down to Mt Pyre 2F. Matches Stairs E on 2F.", code: "E", destMap: "MAP_MT_PYRE_2F", destWarpId: "2" },
    { id: "aen-mtpyre-3f-5", name: "Stairs D to 2F", category: "entrance", x: 50, y: 96.15, desc: "Goes down to Mt Pyre 2F. Matches Stairs D on 2F.", code: "D", destMap: "MAP_MT_PYRE_2F", destWarpId: "3" },
  ],
  "mtpyre-4f": [
    { id: "aen-mtpyre-4f-0", name: "Stairs C to 5F", category: "entrance", x: 80.77, y: 11.54, desc: "Goes up to Mt Pyre 5F. Matches Stairs C on 5F.", code: "C", destMap: "MAP_MT_PYRE_5F", destWarpId: "1" },
    { id: "aen-mtpyre-4f-1", name: "Stairs A to 3F", category: "entrance", x: 19.23, y: 42.31, desc: "Goes down to Mt Pyre 3F. Matches Stairs A on 3F.", code: "A", destMap: "MAP_MT_PYRE_3F", destWarpId: "1" },
    { id: "aen-mtpyre-4f-2", name: "Stairs D to 5F", category: "entrance", x: 96.15, y: 80.77, desc: "Goes up to Mt Pyre 5F. Matches Stairs D on 5F.", code: "D", destMap: "MAP_MT_PYRE_5F", destWarpId: "3" },
    { id: "aen-mtpyre-4f-3", name: "Stairs E to 5F", category: "entrance", x: 96.15, y: 96.15, desc: "Goes up to Mt Pyre 5F. Matches Stairs E on 5F.", code: "E", destMap: "MAP_MT_PYRE_5F", destWarpId: "4" },
    { id: "aen-mtpyre-4f-4", name: "Stairs B to 3F", category: "entrance", x: 73.08, y: 80.77, desc: "Goes down to Mt Pyre 3F. Matches Stairs B on 3F.", code: "B", destMap: "MAP_MT_PYRE_3F", destWarpId: "2" },
    { id: "aen-mtpyre-4f-5", name: "Stairs F to 3F", category: "entrance", x: 19.23, y: 96.15, desc: "Goes down to Mt Pyre 3F. Matches Stairs F on 3F.", code: "F", destMap: "MAP_MT_PYRE_3F", destWarpId: "3" },
  ],
  "mtpyre-5f": [
    { id: "aen-mtpyre-5f-0", name: "Stairs A to 6F", category: "entrance", x: 19.23, y: 11.54, desc: "Goes up to Mt Pyre 6F. Matches Stairs A on 6F.", code: "A", destMap: "MAP_MT_PYRE_6F", destWarpId: "0" },
    { id: "aen-mtpyre-5f-1", name: "Stairs C to 4F", category: "entrance", x: 80.77, y: 42.31, desc: "Goes down to Mt Pyre 4F. Matches Stairs C on 4F.", code: "C", destMap: "MAP_MT_PYRE_4F", destWarpId: "0" },
    { id: "aen-mtpyre-5f-2", name: "Stairs B to 6F", category: "entrance", x: 11.54, y: 80.77, desc: "Goes up to Mt Pyre 6F. Matches Stairs B on 6F.", code: "B", destMap: "MAP_MT_PYRE_6F", destWarpId: "1" },
    { id: "aen-mtpyre-5f-3", name: "Stairs D to 4F", category: "entrance", x: 96.15, y: 80.77, desc: "Goes down to Mt Pyre 4F. Matches Stairs D on 4F.", code: "D", destMap: "MAP_MT_PYRE_4F", destWarpId: "2" },
    { id: "aen-mtpyre-5f-4", name: "Stairs E to 4F", category: "entrance", x: 96.15, y: 96.15, desc: "Goes down to Mt Pyre 4F. Matches Stairs E on 4F.", code: "E", destMap: "MAP_MT_PYRE_4F", destWarpId: "3" },
  ],
  "mtpyre-6f": [
    { id: "aen-mtpyre-6f-0", name: "Stairs A to 5F", category: "entrance", x: 19.23, y: 11.54, desc: "Goes down to Mt Pyre 5F. Matches Stairs A on 5F.", code: "A", destMap: "MAP_MT_PYRE_5F", destWarpId: "0" },
    { id: "aen-mtpyre-6f-1", name: "Stairs B to 5F", category: "entrance", x: 11.54, y: 80.77, desc: "Goes down to Mt Pyre 5F. Matches Stairs B on 5F.", code: "B", destMap: "MAP_MT_PYRE_5F", destWarpId: "2" },
  ],
  "mtpyre-exterior": [
    { id: "aen-mtpyre-exterior-0", name: "Stairs B to 1F", category: "entrance", x: 27.63, y: 83.33, desc: "Goes down to Mt Pyre 1F. Matches Stairs B on 1F.", code: "B", destMap: "MAP_MT_PYRE_1F", destWarpId: "1" },
    { id: "aen-mtpyre-exterior-1", name: "Stairs A to Summit", category: "entrance", x: 51.32, y: 20.59, desc: "Goes up to Mt Pyre Summit. Matches Stairs A on Summit.", code: "A", destMap: "MAP_MT_PYRE_SUMMIT", destWarpId: "1" },
    { id: "aen-mtpyre-exterior-2", name: "Stairs A to Summit", category: "entrance", x: 53.95, y: 20.59, desc: "Goes up to Mt Pyre Summit.", code: "A", destMap: "MAP_MT_PYRE_SUMMIT", destWarpId: "1" },
  ],
  "mtpyre-summit": [
    { id: "aen-mtpyre-summit-0", name: "Stairs A to Exterior", category: "entrance", x: 45, y: 85.14, desc: "Goes down to Mt Pyre Exterior.", code: "A", destMap: "MAP_MT_PYRE_EXTERIOR", destWarpId: "1" },
    { id: "aen-mtpyre-summit-1", name: "Stairs A to Exterior", category: "entrance", x: 47, y: 85.14, desc: "Goes down to Mt Pyre Exterior. Matches Stairs A on Exterior.", code: "A", destMap: "MAP_MT_PYRE_EXTERIOR", destWarpId: "1" },
    { id: "aen-mtpyre-summit-2", name: "Stairs A to Exterior", category: "entrance", x: 49, y: 85.14, desc: "Goes down to Mt Pyre Exterior.", code: "A", destMap: "MAP_MT_PYRE_EXTERIOR", destWarpId: "1" },
  ],
  "navelrock-top": [
    { id: "aen-navelrock-top-0", name: "Door B to Up 4", category: "entrance", x: 54, y: 73.21, desc: "Leads to Navel Rock Up 4. Matches Door B on Up 4.", code: "B", destMap: "MAP_NAVEL_ROCK_UP4", destWarpId: "1" },
  ],
  "newmauville-inside": [
    { id: "aen-newmauville-inside-0", name: "Door A to Entrance", category: "entrance", x: 79.27, y: 81.71, desc: "Leads to New Mauville Entrance. Matches Door A on Entrance.", code: "A", destMap: "MAP_NEW_MAUVILLE_ENTRANCE", destWarpId: "1" },
  ],
  "petalburgwoods": [
    { id: "aen-petalburgwoods-0", name: "Exit to Route 104 — north", category: "entrance", x: 30.21, y: 12.5, desc: "Leaves Petalburg Woods for Route 104 (north).", destMap: "MAP_ROUTE104", destWarpId: "2" },
    { id: "aen-petalburgwoods-1", name: "Exit to Route 104 — north", category: "entrance", x: 32.29, y: 12.5, desc: "Leaves Petalburg Woods for Route 104 (north).", destMap: "MAP_ROUTE104", destWarpId: "3" },
    { id: "aen-petalburgwoods-2", name: "Exit to Route 104 — southwest", category: "entrance", x: 34.38, y: 87.5, desc: "Leaves Petalburg Woods for Route 104 (southwest).", destMap: "MAP_ROUTE104", destWarpId: "4" },
    { id: "aen-petalburgwoods-3", name: "Exit to Route 104 — southwest", category: "entrance", x: 36.46, y: 87.5, desc: "Leaves Petalburg Woods for Route 104 (southwest).", destMap: "MAP_ROUTE104", destWarpId: "5" },
    { id: "aen-petalburgwoods-4", name: "Exit to Route 104 — southeast", category: "entrance", x: 76.04, y: 87.5, desc: "Leaves Petalburg Woods for Route 104 (southeast).", destMap: "MAP_ROUTE104", destWarpId: "6" },
    { id: "aen-petalburgwoods-5", name: "Exit to Route 104 — southeast", category: "entrance", x: 78.13, y: 87.5, desc: "Leaves Petalburg Woods for Route 104 (southeast).", destMap: "MAP_ROUTE104", destWarpId: "7" },
  ],
  "rusturftunnel": [
    { id: "aen-rusturftunnel-0", name: "Exit to Route 116 — west", category: "entrance", x: 12.5, y: 43.75, desc: "Leaves Rusturf Tunnel for Route 116 (west).", destMap: "MAP_ROUTE116", destWarpId: "0" },
    { id: "aen-rusturftunnel-1", name: "Exit to Verdanturf Town — north", category: "entrance", x: 81.94, y: 68.75, desc: "Leaves Rusturf Tunnel for Verdanturf Town (north).", destMap: "MAP_VERDANTURF_TOWN", destWarpId: "4" },
    { id: "aen-rusturftunnel-2", name: "Exit to Route 116 — south", category: "entrance", x: 51.39, y: 85.42, desc: "Leaves Rusturf Tunnel for Route 116 (south).", destMap: "MAP_ROUTE116", destWarpId: "2" },
  ],
  "safarizone-southwest": [
    { id: "aen-safarizone-southwest-0", name: "Door A to Rest House", category: "entrance", x: 73.75, y: 18.75, desc: "Leads to Safari Zone Rest House. Matches Door A on Rest House.", code: "A", destMap: "MAP_SAFARI_ZONE_REST_HOUSE", destWarpId: "0" },
  ],
  "scorchedslab": [
    { id: "aen-scorchedslab-0", name: "Exit to Route 120 — south", category: "entrance", x: 50, y: 82.5, desc: "Leaves Scorched Slab for Route 120 (south).", destMap: "MAP_ROUTE120", destWarpId: "1" },
  ],
  "seafloorcavern-room9": [
    { id: "aen-seafloorcavern-room9-0", name: "Door A to Room 8", category: "entrance", x: 20.37, y: 9.78, desc: "Leads to Seafloor Cavern Room 8. Matches Door A on Room 8.", code: "A", destMap: "MAP_SEAFLOOR_CAVERN_ROOM8", destWarpId: "0" },
  ],
  "shoalcave-lowtideentranceroom": [
    { id: "aen-shoalcave-lowtideentranceroom-0", name: "Exit to Route 125 — south", category: "entrance", x: 58.57, y: 87.14, desc: "Leaves Shoal Cave Low Tide Entrance Room for Route 125 (south).", destMap: "MAP_ROUTE125", destWarpId: "0" },
    { id: "aen-shoalcave-lowtideentranceroom-1", name: "Door C to Low Tide Inner Room", category: "entrance", x: 55.71, y: 15.71, desc: "Leads to Shoal Cave Low Tide Inner Room. Matches Door C on Low Tide Inner Room.", code: "C", destMap: "MAP_SHOAL_CAVE_LOW_TIDE_INNER_ROOM", destWarpId: "0" },
    { id: "aen-shoalcave-lowtideentranceroom-2", name: "Door A to Low Tide Inner Room", category: "entrance", x: 18.57, y: 7.14, desc: "Leads to Shoal Cave Low Tide Inner Room. Matches Door A on Low Tide Inner Room.", code: "A", destMap: "MAP_SHOAL_CAVE_LOW_TIDE_INNER_ROOM", destWarpId: "6" },
    { id: "aen-shoalcave-lowtideentranceroom-3", name: "Door B to Low Tide Inner Room", category: "entrance", x: 78.57, y: 7.14, desc: "Leads to Shoal Cave Low Tide Inner Room. Matches Door B on Low Tide Inner Room.", code: "B", destMap: "MAP_SHOAL_CAVE_LOW_TIDE_INNER_ROOM", destWarpId: "7" },
  ],
  "shoalcave-lowtideiceroom": [
    { id: "aen-shoalcave-lowtideiceroom-0", name: "Door A to Low Tide Lower Room", category: "entrance", x: 87.5, y: 35, desc: "Leads to Shoal Cave Low Tide Lower Room. Matches Door A on Low Tide Lower Room.", code: "A", destMap: "MAP_SHOAL_CAVE_LOW_TIDE_LOWER_ROOM", destWarpId: "3" },
  ],
  "shoalcave-lowtideinnerroom": [
    { id: "aen-shoalcave-lowtideinnerroom-0", name: "Door C to Entrance Room", category: "entrance", x: 75, y: 77.63, desc: "Leads to Shoal Cave Low Tide Entrance Room. Matches Door C on Entrance Room.", code: "C", destMap: "MAP_SHOAL_CAVE_LOW_TIDE_ENTRANCE_ROOM", destWarpId: "1" },
    { id: "aen-shoalcave-lowtideinnerroom-1", name: "Door H to Low Tide Stairs Room", category: "entrance", x: 83.7, y: 40.79, desc: "Leads to Shoal Cave Low Tide Stairs Room. Matches Door H on Low Tide Stairs Room.", code: "H", destMap: "MAP_SHOAL_CAVE_LOW_TIDE_STAIRS_ROOM", destWarpId: "0" },
    { id: "aen-shoalcave-lowtideinnerroom-2", name: "Door E to Low Tide Stairs Room", category: "entrance", x: 92.39, y: 11.84, desc: "Leads to Shoal Cave Low Tide Stairs Room. Matches Door E on Low Tide Stairs Room.", code: "E", destMap: "MAP_SHOAL_CAVE_LOW_TIDE_STAIRS_ROOM", destWarpId: "1" },
    { id: "aen-shoalcave-lowtideinnerroom-3", name: "Door D to Low Tide Lower Room", category: "entrance", x: 42.39, y: 38.16, desc: "Leads to Shoal Cave Low Tide Lower Room. Matches Door D on Low Tide Lower Room.", code: "D", destMap: "MAP_SHOAL_CAVE_LOW_TIDE_LOWER_ROOM", destWarpId: "0" },
    { id: "aen-shoalcave-lowtideinnerroom-4", name: "Door F to Low Tide Lower Room", category: "entrance", x: 33.7, y: 51.32, desc: "Leads to Shoal Cave Low Tide Lower Room. Matches Door F on Low Tide Lower Room.", code: "F", destMap: "MAP_SHOAL_CAVE_LOW_TIDE_LOWER_ROOM", destWarpId: "1" },
    { id: "aen-shoalcave-lowtideinnerroom-5", name: "Door G to Low Tide Lower Room", category: "entrance", x: 66.3, y: 67.11, desc: "Leads to Shoal Cave Low Tide Lower Room. Matches Door G on Low Tide Lower Room.", code: "G", destMap: "MAP_SHOAL_CAVE_LOW_TIDE_LOWER_ROOM", destWarpId: "2" },
    { id: "aen-shoalcave-lowtideinnerroom-6", name: "Door A to Entrance Room", category: "entrance", x: 31.52, y: 88.16, desc: "Leads to Shoal Cave Low Tide Entrance Room. Matches Door A on Entrance Room.", code: "A", destMap: "MAP_SHOAL_CAVE_LOW_TIDE_ENTRANCE_ROOM", destWarpId: "2" },
    { id: "aen-shoalcave-lowtideinnerroom-7", name: "Door B to Entrance Room", category: "entrance", x: 88.04, y: 88.16, desc: "Leads to Shoal Cave Low Tide Entrance Room. Matches Door B on Entrance Room.", code: "B", destMap: "MAP_SHOAL_CAVE_LOW_TIDE_ENTRANCE_ROOM", destWarpId: "3" },
  ],
  "shoalcave-lowtidestairsroom": [
    { id: "aen-shoalcave-lowtidestairsroom-0", name: "Door H to Low Tide Inner Room", category: "entrance", x: 16.67, y: 83.33, desc: "Leads to Shoal Cave Low Tide Inner Room. Matches Door H on Low Tide Inner Room.", code: "H", destMap: "MAP_SHOAL_CAVE_LOW_TIDE_INNER_ROOM", destWarpId: "1" },
    { id: "aen-shoalcave-lowtidestairsroom-1", name: "Door E to Low Tide Inner Room", category: "entrance", x: 35.71, y: 30, desc: "Leads to Shoal Cave Low Tide Inner Room. Matches Door E on Low Tide Inner Room.", code: "E", destMap: "MAP_SHOAL_CAVE_LOW_TIDE_INNER_ROOM", destWarpId: "2" },
  ],
  "underwater-route126": [
    { id: "aen-underwater-route126-0", name: "Door A to Sootopolis City", category: "entrance", x: 56.88, y: 81.88, desc: "Leads to Underwater Sootopolis City. Matches Door A on Sootopolis City.", code: "A", destMap: "MAP_UNDERWATER_SOOTOPOLIS_CITY", destWarpId: "0" },
  ],
  "underwater-route127": [
    { id: "aen-underwater-route127-0", name: "Door A to Marine Cave", category: "entrance", x: 71.88, y: 6.88, desc: "Leads to Underwater Marine Cave.", code: "A", destMap: "MAP_UNDERWATER_MARINE_CAVE", destWarpId: "0" },
    { id: "aen-underwater-route127-1", name: "Door B to Marine Cave", category: "entrance", x: 84.38, y: 48.13, desc: "Leads to Underwater Marine Cave.", code: "B", destMap: "MAP_UNDERWATER_MARINE_CAVE", destWarpId: "0" },
  ],
  "underwater-route128": [
    { id: "aen-underwater-route128-0", name: "Door A to Seafloor Cavern", category: "entrance", x: 32.08, y: 66.25, desc: "Leads to Underwater Seafloor Cavern. Matches Door A on Seafloor Cavern.", code: "A", destMap: "MAP_UNDERWATER_SEAFLOOR_CAVERN", destWarpId: "0" },
  ],
  "victoryroad-1f": [
    { id: "aen-victoryroad-1f-0", name: "Exit to Ever Grande City — southwest", category: "entrance", x: 33.7, y: 90, desc: "Leaves Victory Road 1F for Ever Grande City (southwest).", destMap: "MAP_EVER_GRANDE_CITY", destWarpId: "2" },
    { id: "aen-victoryroad-1f-1", name: "Exit to Ever Grande City — north", category: "entrance", x: 85.87, y: 12.22, desc: "Leaves Victory Road 1F for Ever Grande City (north).", destMap: "MAP_EVER_GRANDE_CITY", destWarpId: "3" },
    { id: "aen-victoryroad-1f-2", name: "Ladder B to B1F", category: "entrance", x: 46.74, y: 72.22, desc: "Goes down to Victory Road B1F. Matches Ladder B on B1F.", code: "B", destMap: "MAP_VICTORY_ROAD_B1F", destWarpId: "5" },
    { id: "aen-victoryroad-1f-3", name: "Ladder C to B1F", category: "entrance", x: 92.39, y: 85.56, desc: "Goes down to Victory Road B1F. Matches Ladder C on B1F.", code: "C", destMap: "MAP_VICTORY_ROAD_B1F", destWarpId: "2" },
    { id: "aen-victoryroad-1f-4", name: "Ladder A to B1F", category: "entrance", x: 20.65, y: 32.22, desc: "Goes down to Victory Road B1F. Matches Ladder A on B1F.", code: "A", destMap: "MAP_VICTORY_ROAD_B1F", destWarpId: "4" },
  ],
  "victoryroad-b1f": [
    { id: "aen-victoryroad-b1f-0", name: "Ladder F to B2F", category: "entrance", x: 66.3, y: 82.26, desc: "Goes down to Victory Road B2F. Matches Ladder F on B2F.", code: "F", destMap: "MAP_VICTORY_ROAD_B2F", destWarpId: "0" },
    { id: "aen-victoryroad-b1f-1", name: "Ladder E to B2F", category: "entrance", x: 38.04, y: 53.23, desc: "Goes down to Victory Road B2F. Matches Ladder E on B2F.", code: "E", destMap: "MAP_VICTORY_ROAD_B2F", destWarpId: "2" },
    { id: "aen-victoryroad-b1f-2", name: "Ladder C to 1F", category: "entrance", x: 92.39, y: 82.26, desc: "Goes up to Victory Road 1F. Matches Ladder C on 1F.", code: "C", destMap: "MAP_VICTORY_ROAD_1F", destWarpId: "3" },
    { id: "aen-victoryroad-b1f-3", name: "Ladder D to B2F", category: "entrance", x: 92.39, y: 8.06, desc: "Goes down to Victory Road B2F. Matches Ladder D on B2F.", code: "D", destMap: "MAP_VICTORY_ROAD_B2F", destWarpId: "1" },
    { id: "aen-victoryroad-b1f-4", name: "Ladder A to 1F", category: "entrance", x: 18.48, y: 11.29, desc: "Goes up to Victory Road 1F. Matches Ladder A on 1F.", code: "A", destMap: "MAP_VICTORY_ROAD_1F", destWarpId: "4" },
    { id: "aen-victoryroad-b1f-5", name: "Ladder B to 1F", category: "entrance", x: 44.57, y: 69.35, desc: "Goes up to Victory Road 1F. Matches Ladder B on 1F.", code: "B", destMap: "MAP_VICTORY_ROAD_1F", destWarpId: "2" },
    { id: "aen-victoryroad-b1f-6", name: "Ladder G to B2F", category: "entrance", x: 11.96, y: 85.48, desc: "Goes down to Victory Road B2F. Matches Ladder G on B2F.", code: "G", destMap: "MAP_VICTORY_ROAD_B2F", destWarpId: "3" },
  ],
  "victoryroad-b2f": [
    { id: "aen-victoryroad-b2f-0", name: "Ladder F to B1F", category: "entrance", x: 66.3, y: 82.26, desc: "Goes up to Victory Road B1F. Matches Ladder F on B1F.", code: "F", destMap: "MAP_VICTORY_ROAD_B1F", destWarpId: "0" },
    { id: "aen-victoryroad-b2f-1", name: "Ladder D to B1F", category: "entrance", x: 94.57, y: 8.06, desc: "Goes up to Victory Road B1F. Matches Ladder D on B1F.", code: "D", destMap: "MAP_VICTORY_ROAD_B1F", destWarpId: "3" },
    { id: "aen-victoryroad-b2f-2", name: "Ladder E to B1F", category: "entrance", x: 42.39, y: 40.32, desc: "Goes up to Victory Road B1F. Matches Ladder E on B1F.", code: "E", destMap: "MAP_VICTORY_ROAD_B1F", destWarpId: "1" },
    { id: "aen-victoryroad-b2f-3", name: "Ladder G to B1F", category: "entrance", x: 11.96, y: 85.48, desc: "Goes up to Victory Road B1F. Matches Ladder G on B1F.", code: "G", destMap: "MAP_VICTORY_ROAD_B1F", destWarpId: "6" },
  ],
};
