// AUTO-GENERATED by scripts/sync-offline-data.mjs — do not edit by hand.

import type { DexEntry } from "./dex";

export const HOENN_DEX: DexEntry[] = [
  {
    "name": "Treecko",
    "slug": "treecko",
    "hoennNumber": 1,
    "nationalNumber": 252
  },
  {
    "name": "Grovyle",
    "slug": "grovyle",
    "hoennNumber": 2,
    "nationalNumber": 253
  },
  {
    "name": "Sceptile",
    "slug": "sceptile",
    "hoennNumber": 3,
    "nationalNumber": 254
  },
  {
    "name": "Torchic",
    "slug": "torchic",
    "hoennNumber": 4,
    "nationalNumber": 255
  },
  {
    "name": "Combusken",
    "slug": "combusken",
    "hoennNumber": 5,
    "nationalNumber": 256
  },
  {
    "name": "Blaziken",
    "slug": "blaziken",
    "hoennNumber": 6,
    "nationalNumber": 257
  },
  {
    "name": "Mudkip",
    "slug": "mudkip",
    "hoennNumber": 7,
    "nationalNumber": 258
  },
  {
    "name": "Marshtomp",
    "slug": "marshtomp",
    "hoennNumber": 8,
    "nationalNumber": 259
  },
  {
    "name": "Swampert",
    "slug": "swampert",
    "hoennNumber": 9,
    "nationalNumber": 260
  },
  {
    "name": "Poochyena",
    "slug": "poochyena",
    "hoennNumber": 10,
    "nationalNumber": 261
  },
  {
    "name": "Mightyena",
    "slug": "mightyena",
    "hoennNumber": 11,
    "nationalNumber": 262
  },
  {
    "name": "Zigzagoon",
    "slug": "zigzagoon",
    "hoennNumber": 12,
    "nationalNumber": 263
  },
  {
    "name": "Linoone",
    "slug": "linoone",
    "hoennNumber": 13,
    "nationalNumber": 264
  },
  {
    "name": "Wurmple",
    "slug": "wurmple",
    "hoennNumber": 14,
    "nationalNumber": 265
  },
  {
    "name": "Silcoon",
    "slug": "silcoon",
    "hoennNumber": 15,
    "nationalNumber": 266
  },
  {
    "name": "Beautifly",
    "slug": "beautifly",
    "hoennNumber": 16,
    "nationalNumber": 267
  },
  {
    "name": "Cascoon",
    "slug": "cascoon",
    "hoennNumber": 17,
    "nationalNumber": 268
  },
  {
    "name": "Dustox",
    "slug": "dustox",
    "hoennNumber": 18,
    "nationalNumber": 269
  },
  {
    "name": "Lotad",
    "slug": "lotad",
    "hoennNumber": 19,
    "nationalNumber": 270
  },
  {
    "name": "Lombre",
    "slug": "lombre",
    "hoennNumber": 20,
    "nationalNumber": 271
  },
  {
    "name": "Ludicolo",
    "slug": "ludicolo",
    "hoennNumber": 21,
    "nationalNumber": 272
  },
  {
    "name": "Seedot",
    "slug": "seedot",
    "hoennNumber": 22,
    "nationalNumber": 273
  },
  {
    "name": "Nuzleaf",
    "slug": "nuzleaf",
    "hoennNumber": 23,
    "nationalNumber": 274
  },
  {
    "name": "Shiftry",
    "slug": "shiftry",
    "hoennNumber": 24,
    "nationalNumber": 275
  },
  {
    "name": "Taillow",
    "slug": "taillow",
    "hoennNumber": 25,
    "nationalNumber": 276
  },
  {
    "name": "Swellow",
    "slug": "swellow",
    "hoennNumber": 26,
    "nationalNumber": 277
  },
  {
    "name": "Wingull",
    "slug": "wingull",
    "hoennNumber": 27,
    "nationalNumber": 278
  },
  {
    "name": "Pelipper",
    "slug": "pelipper",
    "hoennNumber": 28,
    "nationalNumber": 279
  },
  {
    "name": "Ralts",
    "slug": "ralts",
    "hoennNumber": 29,
    "nationalNumber": 280
  },
  {
    "name": "Kirlia",
    "slug": "kirlia",
    "hoennNumber": 30,
    "nationalNumber": 281
  },
  {
    "name": "Gardevoir",
    "slug": "gardevoir",
    "hoennNumber": 31,
    "nationalNumber": 282
  },
  {
    "name": "Surskit",
    "slug": "surskit",
    "hoennNumber": 32,
    "nationalNumber": 283
  },
  {
    "name": "Masquerain",
    "slug": "masquerain",
    "hoennNumber": 33,
    "nationalNumber": 284
  },
  {
    "name": "Shroomish",
    "slug": "shroomish",
    "hoennNumber": 34,
    "nationalNumber": 285
  },
  {
    "name": "Breloom",
    "slug": "breloom",
    "hoennNumber": 35,
    "nationalNumber": 286
  },
  {
    "name": "Slakoth",
    "slug": "slakoth",
    "hoennNumber": 36,
    "nationalNumber": 287
  },
  {
    "name": "Vigoroth",
    "slug": "vigoroth",
    "hoennNumber": 37,
    "nationalNumber": 288
  },
  {
    "name": "Slaking",
    "slug": "slaking",
    "hoennNumber": 38,
    "nationalNumber": 289
  },
  {
    "name": "Abra",
    "slug": "abra",
    "hoennNumber": 39,
    "nationalNumber": 63
  },
  {
    "name": "Kadabra",
    "slug": "kadabra",
    "hoennNumber": 40,
    "nationalNumber": 64
  },
  {
    "name": "Alakazam",
    "slug": "alakazam",
    "hoennNumber": 41,
    "nationalNumber": 65
  },
  {
    "name": "Nincada",
    "slug": "nincada",
    "hoennNumber": 42,
    "nationalNumber": 290
  },
  {
    "name": "Ninjask",
    "slug": "ninjask",
    "hoennNumber": 43,
    "nationalNumber": 291
  },
  {
    "name": "Shedinja",
    "slug": "shedinja",
    "hoennNumber": 44,
    "nationalNumber": 292
  },
  {
    "name": "Whismur",
    "slug": "whismur",
    "hoennNumber": 45,
    "nationalNumber": 293
  },
  {
    "name": "Loudred",
    "slug": "loudred",
    "hoennNumber": 46,
    "nationalNumber": 294
  },
  {
    "name": "Exploud",
    "slug": "exploud",
    "hoennNumber": 47,
    "nationalNumber": 295
  },
  {
    "name": "Makuhita",
    "slug": "makuhita",
    "hoennNumber": 48,
    "nationalNumber": 296
  },
  {
    "name": "Hariyama",
    "slug": "hariyama",
    "hoennNumber": 49,
    "nationalNumber": 297
  },
  {
    "name": "Goldeen",
    "slug": "goldeen",
    "hoennNumber": 50,
    "nationalNumber": 118
  },
  {
    "name": "Seaking",
    "slug": "seaking",
    "hoennNumber": 51,
    "nationalNumber": 119
  },
  {
    "name": "Magikarp",
    "slug": "magikarp",
    "hoennNumber": 52,
    "nationalNumber": 129
  },
  {
    "name": "Gyarados",
    "slug": "gyarados",
    "hoennNumber": 53,
    "nationalNumber": 130
  },
  {
    "name": "Azurill",
    "slug": "azurill",
    "hoennNumber": 54,
    "nationalNumber": 298
  },
  {
    "name": "Marill",
    "slug": "marill",
    "hoennNumber": 55,
    "nationalNumber": 183
  },
  {
    "name": "Azumarill",
    "slug": "azumarill",
    "hoennNumber": 56,
    "nationalNumber": 184
  },
  {
    "name": "Geodude",
    "slug": "geodude",
    "hoennNumber": 57,
    "nationalNumber": 74
  },
  {
    "name": "Graveler",
    "slug": "graveler",
    "hoennNumber": 58,
    "nationalNumber": 75
  },
  {
    "name": "Golem",
    "slug": "golem",
    "hoennNumber": 59,
    "nationalNumber": 76
  },
  {
    "name": "Nosepass",
    "slug": "nosepass",
    "hoennNumber": 60,
    "nationalNumber": 299
  },
  {
    "name": "Skitty",
    "slug": "skitty",
    "hoennNumber": 61,
    "nationalNumber": 300
  },
  {
    "name": "Delcatty",
    "slug": "delcatty",
    "hoennNumber": 62,
    "nationalNumber": 301
  },
  {
    "name": "Zubat",
    "slug": "zubat",
    "hoennNumber": 63,
    "nationalNumber": 41
  },
  {
    "name": "Golbat",
    "slug": "golbat",
    "hoennNumber": 64,
    "nationalNumber": 42
  },
  {
    "name": "Crobat",
    "slug": "crobat",
    "hoennNumber": 65,
    "nationalNumber": 169
  },
  {
    "name": "Tentacool",
    "slug": "tentacool",
    "hoennNumber": 66,
    "nationalNumber": 72
  },
  {
    "name": "Tentacruel",
    "slug": "tentacruel",
    "hoennNumber": 67,
    "nationalNumber": 73
  },
  {
    "name": "Sableye",
    "slug": "sableye",
    "hoennNumber": 68,
    "nationalNumber": 302
  },
  {
    "name": "Mawile",
    "slug": "mawile",
    "hoennNumber": 69,
    "nationalNumber": 303
  },
  {
    "name": "Aron",
    "slug": "aron",
    "hoennNumber": 70,
    "nationalNumber": 304
  },
  {
    "name": "Lairon",
    "slug": "lairon",
    "hoennNumber": 71,
    "nationalNumber": 305
  },
  {
    "name": "Aggron",
    "slug": "aggron",
    "hoennNumber": 72,
    "nationalNumber": 306
  },
  {
    "name": "Machop",
    "slug": "machop",
    "hoennNumber": 73,
    "nationalNumber": 66
  },
  {
    "name": "Machoke",
    "slug": "machoke",
    "hoennNumber": 74,
    "nationalNumber": 67
  },
  {
    "name": "Machamp",
    "slug": "machamp",
    "hoennNumber": 75,
    "nationalNumber": 68
  },
  {
    "name": "Meditite",
    "slug": "meditite",
    "hoennNumber": 76,
    "nationalNumber": 307
  },
  {
    "name": "Medicham",
    "slug": "medicham",
    "hoennNumber": 77,
    "nationalNumber": 308
  },
  {
    "name": "Electrike",
    "slug": "electrike",
    "hoennNumber": 78,
    "nationalNumber": 309
  },
  {
    "name": "Manectric",
    "slug": "manectric",
    "hoennNumber": 79,
    "nationalNumber": 310
  },
  {
    "name": "Plusle",
    "slug": "plusle",
    "hoennNumber": 80,
    "nationalNumber": 311
  },
  {
    "name": "Minun",
    "slug": "minun",
    "hoennNumber": 81,
    "nationalNumber": 312
  },
  {
    "name": "Magnemite",
    "slug": "magnemite",
    "hoennNumber": 82,
    "nationalNumber": 81
  },
  {
    "name": "Magneton",
    "slug": "magneton",
    "hoennNumber": 83,
    "nationalNumber": 82
  },
  {
    "name": "Voltorb",
    "slug": "voltorb",
    "hoennNumber": 84,
    "nationalNumber": 100
  },
  {
    "name": "Electrode",
    "slug": "electrode",
    "hoennNumber": 85,
    "nationalNumber": 101
  },
  {
    "name": "Volbeat",
    "slug": "volbeat",
    "hoennNumber": 86,
    "nationalNumber": 313
  },
  {
    "name": "Illumise",
    "slug": "illumise",
    "hoennNumber": 87,
    "nationalNumber": 314
  },
  {
    "name": "Oddish",
    "slug": "oddish",
    "hoennNumber": 88,
    "nationalNumber": 43
  },
  {
    "name": "Gloom",
    "slug": "gloom",
    "hoennNumber": 89,
    "nationalNumber": 44
  },
  {
    "name": "Vileplume",
    "slug": "vileplume",
    "hoennNumber": 90,
    "nationalNumber": 45
  },
  {
    "name": "Bellossom",
    "slug": "bellossom",
    "hoennNumber": 91,
    "nationalNumber": 182
  },
  {
    "name": "Doduo",
    "slug": "doduo",
    "hoennNumber": 92,
    "nationalNumber": 84
  },
  {
    "name": "Dodrio",
    "slug": "dodrio",
    "hoennNumber": 93,
    "nationalNumber": 85
  },
  {
    "name": "Roselia",
    "slug": "roselia",
    "hoennNumber": 94,
    "nationalNumber": 315
  },
  {
    "name": "Gulpin",
    "slug": "gulpin",
    "hoennNumber": 95,
    "nationalNumber": 316
  },
  {
    "name": "Swalot",
    "slug": "swalot",
    "hoennNumber": 96,
    "nationalNumber": 317
  },
  {
    "name": "Carvanha",
    "slug": "carvanha",
    "hoennNumber": 97,
    "nationalNumber": 318
  },
  {
    "name": "Sharpedo",
    "slug": "sharpedo",
    "hoennNumber": 98,
    "nationalNumber": 319
  },
  {
    "name": "Wailmer",
    "slug": "wailmer",
    "hoennNumber": 99,
    "nationalNumber": 320
  },
  {
    "name": "Wailord",
    "slug": "wailord",
    "hoennNumber": 100,
    "nationalNumber": 321
  },
  {
    "name": "Numel",
    "slug": "numel",
    "hoennNumber": 101,
    "nationalNumber": 322
  },
  {
    "name": "Camerupt",
    "slug": "camerupt",
    "hoennNumber": 102,
    "nationalNumber": 323
  },
  {
    "name": "Slugma",
    "slug": "slugma",
    "hoennNumber": 103,
    "nationalNumber": 218
  },
  {
    "name": "Magcargo",
    "slug": "magcargo",
    "hoennNumber": 104,
    "nationalNumber": 219
  },
  {
    "name": "Torkoal",
    "slug": "torkoal",
    "hoennNumber": 105,
    "nationalNumber": 324
  },
  {
    "name": "Grimer",
    "slug": "grimer",
    "hoennNumber": 106,
    "nationalNumber": 88
  },
  {
    "name": "Muk",
    "slug": "muk",
    "hoennNumber": 107,
    "nationalNumber": 89
  },
  {
    "name": "Koffing",
    "slug": "koffing",
    "hoennNumber": 108,
    "nationalNumber": 109
  },
  {
    "name": "Weezing",
    "slug": "weezing",
    "hoennNumber": 109,
    "nationalNumber": 110
  },
  {
    "name": "Spoink",
    "slug": "spoink",
    "hoennNumber": 110,
    "nationalNumber": 325
  },
  {
    "name": "Grumpig",
    "slug": "grumpig",
    "hoennNumber": 111,
    "nationalNumber": 326
  },
  {
    "name": "Sandshrew",
    "slug": "sandshrew",
    "hoennNumber": 112,
    "nationalNumber": 27
  },
  {
    "name": "Sandslash",
    "slug": "sandslash",
    "hoennNumber": 113,
    "nationalNumber": 28
  },
  {
    "name": "Spinda",
    "slug": "spinda",
    "hoennNumber": 114,
    "nationalNumber": 327
  },
  {
    "name": "Skarmory",
    "slug": "skarmory",
    "hoennNumber": 115,
    "nationalNumber": 227
  },
  {
    "name": "Trapinch",
    "slug": "trapinch",
    "hoennNumber": 116,
    "nationalNumber": 328
  },
  {
    "name": "Vibrava",
    "slug": "vibrava",
    "hoennNumber": 117,
    "nationalNumber": 329
  },
  {
    "name": "Flygon",
    "slug": "flygon",
    "hoennNumber": 118,
    "nationalNumber": 330
  },
  {
    "name": "Cacnea",
    "slug": "cacnea",
    "hoennNumber": 119,
    "nationalNumber": 331
  },
  {
    "name": "Cacturne",
    "slug": "cacturne",
    "hoennNumber": 120,
    "nationalNumber": 332
  },
  {
    "name": "Swablu",
    "slug": "swablu",
    "hoennNumber": 121,
    "nationalNumber": 333
  },
  {
    "name": "Altaria",
    "slug": "altaria",
    "hoennNumber": 122,
    "nationalNumber": 334
  },
  {
    "name": "Zangoose",
    "slug": "zangoose",
    "hoennNumber": 123,
    "nationalNumber": 335
  },
  {
    "name": "Seviper",
    "slug": "seviper",
    "hoennNumber": 124,
    "nationalNumber": 336
  },
  {
    "name": "Lunatone",
    "slug": "lunatone",
    "hoennNumber": 125,
    "nationalNumber": 337
  },
  {
    "name": "Solrock",
    "slug": "solrock",
    "hoennNumber": 126,
    "nationalNumber": 338
  },
  {
    "name": "Barboach",
    "slug": "barboach",
    "hoennNumber": 127,
    "nationalNumber": 339
  },
  {
    "name": "Whiscash",
    "slug": "whiscash",
    "hoennNumber": 128,
    "nationalNumber": 340
  },
  {
    "name": "Corphish",
    "slug": "corphish",
    "hoennNumber": 129,
    "nationalNumber": 341
  },
  {
    "name": "Crawdaunt",
    "slug": "crawdaunt",
    "hoennNumber": 130,
    "nationalNumber": 342
  },
  {
    "name": "Baltoy",
    "slug": "baltoy",
    "hoennNumber": 131,
    "nationalNumber": 343
  },
  {
    "name": "Claydol",
    "slug": "claydol",
    "hoennNumber": 132,
    "nationalNumber": 344
  },
  {
    "name": "Lileep",
    "slug": "lileep",
    "hoennNumber": 133,
    "nationalNumber": 345
  },
  {
    "name": "Cradily",
    "slug": "cradily",
    "hoennNumber": 134,
    "nationalNumber": 346
  },
  {
    "name": "Anorith",
    "slug": "anorith",
    "hoennNumber": 135,
    "nationalNumber": 347
  },
  {
    "name": "Armaldo",
    "slug": "armaldo",
    "hoennNumber": 136,
    "nationalNumber": 348
  },
  {
    "name": "Igglybuff",
    "slug": "igglybuff",
    "hoennNumber": 137,
    "nationalNumber": 174
  },
  {
    "name": "Jigglypuff",
    "slug": "jigglypuff",
    "hoennNumber": 138,
    "nationalNumber": 39
  },
  {
    "name": "Wigglytuff",
    "slug": "wigglytuff",
    "hoennNumber": 139,
    "nationalNumber": 40
  },
  {
    "name": "Feebas",
    "slug": "feebas",
    "hoennNumber": 140,
    "nationalNumber": 349
  },
  {
    "name": "Milotic",
    "slug": "milotic",
    "hoennNumber": 141,
    "nationalNumber": 350
  },
  {
    "name": "Castform",
    "slug": "castform",
    "hoennNumber": 142,
    "nationalNumber": 351
  },
  {
    "name": "Staryu",
    "slug": "staryu",
    "hoennNumber": 143,
    "nationalNumber": 120
  },
  {
    "name": "Starmie",
    "slug": "starmie",
    "hoennNumber": 144,
    "nationalNumber": 121
  },
  {
    "name": "Kecleon",
    "slug": "kecleon",
    "hoennNumber": 145,
    "nationalNumber": 352
  },
  {
    "name": "Shuppet",
    "slug": "shuppet",
    "hoennNumber": 146,
    "nationalNumber": 353
  },
  {
    "name": "Banette",
    "slug": "banette",
    "hoennNumber": 147,
    "nationalNumber": 354
  },
  {
    "name": "Duskull",
    "slug": "duskull",
    "hoennNumber": 148,
    "nationalNumber": 355
  },
  {
    "name": "Dusclops",
    "slug": "dusclops",
    "hoennNumber": 149,
    "nationalNumber": 356
  },
  {
    "name": "Tropius",
    "slug": "tropius",
    "hoennNumber": 150,
    "nationalNumber": 357
  },
  {
    "name": "Chimecho",
    "slug": "chimecho",
    "hoennNumber": 151,
    "nationalNumber": 358
  },
  {
    "name": "Absol",
    "slug": "absol",
    "hoennNumber": 152,
    "nationalNumber": 359
  },
  {
    "name": "Vulpix",
    "slug": "vulpix",
    "hoennNumber": 153,
    "nationalNumber": 37
  },
  {
    "name": "Ninetales",
    "slug": "ninetales",
    "hoennNumber": 154,
    "nationalNumber": 38
  },
  {
    "name": "Pichu",
    "slug": "pichu",
    "hoennNumber": 155,
    "nationalNumber": 172
  },
  {
    "name": "Pikachu",
    "slug": "pikachu",
    "hoennNumber": 156,
    "nationalNumber": 25
  },
  {
    "name": "Raichu",
    "slug": "raichu",
    "hoennNumber": 157,
    "nationalNumber": 26
  },
  {
    "name": "Psyduck",
    "slug": "psyduck",
    "hoennNumber": 158,
    "nationalNumber": 54
  },
  {
    "name": "Golduck",
    "slug": "golduck",
    "hoennNumber": 159,
    "nationalNumber": 55
  },
  {
    "name": "Wynaut",
    "slug": "wynaut",
    "hoennNumber": 160,
    "nationalNumber": 360
  },
  {
    "name": "Wobbuffet",
    "slug": "wobbuffet",
    "hoennNumber": 161,
    "nationalNumber": 202
  },
  {
    "name": "Natu",
    "slug": "natu",
    "hoennNumber": 162,
    "nationalNumber": 177
  },
  {
    "name": "Xatu",
    "slug": "xatu",
    "hoennNumber": 163,
    "nationalNumber": 178
  },
  {
    "name": "Girafarig",
    "slug": "girafarig",
    "hoennNumber": 164,
    "nationalNumber": 203
  },
  {
    "name": "Phanpy",
    "slug": "phanpy",
    "hoennNumber": 165,
    "nationalNumber": 231
  },
  {
    "name": "Donphan",
    "slug": "donphan",
    "hoennNumber": 166,
    "nationalNumber": 232
  },
  {
    "name": "Pinsir",
    "slug": "pinsir",
    "hoennNumber": 167,
    "nationalNumber": 127
  },
  {
    "name": "Heracross",
    "slug": "heracross",
    "hoennNumber": 168,
    "nationalNumber": 214
  },
  {
    "name": "Rhyhorn",
    "slug": "rhyhorn",
    "hoennNumber": 169,
    "nationalNumber": 111
  },
  {
    "name": "Rhydon",
    "slug": "rhydon",
    "hoennNumber": 170,
    "nationalNumber": 112
  },
  {
    "name": "Snorunt",
    "slug": "snorunt",
    "hoennNumber": 171,
    "nationalNumber": 361
  },
  {
    "name": "Glalie",
    "slug": "glalie",
    "hoennNumber": 172,
    "nationalNumber": 362
  },
  {
    "name": "Spheal",
    "slug": "spheal",
    "hoennNumber": 173,
    "nationalNumber": 363
  },
  {
    "name": "Sealeo",
    "slug": "sealeo",
    "hoennNumber": 174,
    "nationalNumber": 364
  },
  {
    "name": "Walrein",
    "slug": "walrein",
    "hoennNumber": 175,
    "nationalNumber": 365
  },
  {
    "name": "Clamperl",
    "slug": "clamperl",
    "hoennNumber": 176,
    "nationalNumber": 366
  },
  {
    "name": "Huntail",
    "slug": "huntail",
    "hoennNumber": 177,
    "nationalNumber": 367
  },
  {
    "name": "Gorebyss",
    "slug": "gorebyss",
    "hoennNumber": 178,
    "nationalNumber": 368
  },
  {
    "name": "Relicanth",
    "slug": "relicanth",
    "hoennNumber": 179,
    "nationalNumber": 369
  },
  {
    "name": "Corsola",
    "slug": "corsola",
    "hoennNumber": 180,
    "nationalNumber": 222
  },
  {
    "name": "Chinchou",
    "slug": "chinchou",
    "hoennNumber": 181,
    "nationalNumber": 170
  },
  {
    "name": "Lanturn",
    "slug": "lanturn",
    "hoennNumber": 182,
    "nationalNumber": 171
  },
  {
    "name": "Luvdisc",
    "slug": "luvdisc",
    "hoennNumber": 183,
    "nationalNumber": 370
  },
  {
    "name": "Horsea",
    "slug": "horsea",
    "hoennNumber": 184,
    "nationalNumber": 116
  },
  {
    "name": "Seadra",
    "slug": "seadra",
    "hoennNumber": 185,
    "nationalNumber": 117
  },
  {
    "name": "Kingdra",
    "slug": "kingdra",
    "hoennNumber": 186,
    "nationalNumber": 230
  },
  {
    "name": "Bagon",
    "slug": "bagon",
    "hoennNumber": 187,
    "nationalNumber": 371
  },
  {
    "name": "Shelgon",
    "slug": "shelgon",
    "hoennNumber": 188,
    "nationalNumber": 372
  },
  {
    "name": "Salamence",
    "slug": "salamence",
    "hoennNumber": 189,
    "nationalNumber": 373
  },
  {
    "name": "Beldum",
    "slug": "beldum",
    "hoennNumber": 190,
    "nationalNumber": 374
  },
  {
    "name": "Metang",
    "slug": "metang",
    "hoennNumber": 191,
    "nationalNumber": 375
  },
  {
    "name": "Metagross",
    "slug": "metagross",
    "hoennNumber": 192,
    "nationalNumber": 376
  },
  {
    "name": "Regirock",
    "slug": "regirock",
    "hoennNumber": 193,
    "nationalNumber": 377
  },
  {
    "name": "Regice",
    "slug": "regice",
    "hoennNumber": 194,
    "nationalNumber": 378
  },
  {
    "name": "Registeel",
    "slug": "registeel",
    "hoennNumber": 195,
    "nationalNumber": 379
  },
  {
    "name": "Latias",
    "slug": "latias",
    "hoennNumber": 196,
    "nationalNumber": 380
  },
  {
    "name": "Latios",
    "slug": "latios",
    "hoennNumber": 197,
    "nationalNumber": 381
  },
  {
    "name": "Kyogre",
    "slug": "kyogre",
    "hoennNumber": 198,
    "nationalNumber": 382
  },
  {
    "name": "Groudon",
    "slug": "groudon",
    "hoennNumber": 199,
    "nationalNumber": 383
  },
  {
    "name": "Rayquaza",
    "slug": "rayquaza",
    "hoennNumber": 200,
    "nationalNumber": 384
  },
  {
    "name": "Jirachi",
    "slug": "jirachi",
    "hoennNumber": 201,
    "nationalNumber": 385
  },
  {
    "name": "Deoxys",
    "slug": "deoxys",
    "hoennNumber": 202,
    "nationalNumber": 386
  }
];

export const NATIONAL_DEX: DexEntry[] = [
  {
    "name": "Bulbasaur",
    "slug": "bulbasaur",
    "nationalNumber": 1
  },
  {
    "name": "Ivysaur",
    "slug": "ivysaur",
    "nationalNumber": 2
  },
  {
    "name": "Venusaur",
    "slug": "venusaur",
    "nationalNumber": 3
  },
  {
    "name": "Charmander",
    "slug": "charmander",
    "nationalNumber": 4
  },
  {
    "name": "Charmeleon",
    "slug": "charmeleon",
    "nationalNumber": 5
  },
  {
    "name": "Charizard",
    "slug": "charizard",
    "nationalNumber": 6
  },
  {
    "name": "Squirtle",
    "slug": "squirtle",
    "nationalNumber": 7
  },
  {
    "name": "Wartortle",
    "slug": "wartortle",
    "nationalNumber": 8
  },
  {
    "name": "Blastoise",
    "slug": "blastoise",
    "nationalNumber": 9
  },
  {
    "name": "Caterpie",
    "slug": "caterpie",
    "nationalNumber": 10
  },
  {
    "name": "Metapod",
    "slug": "metapod",
    "nationalNumber": 11
  },
  {
    "name": "Butterfree",
    "slug": "butterfree",
    "nationalNumber": 12
  },
  {
    "name": "Weedle",
    "slug": "weedle",
    "nationalNumber": 13
  },
  {
    "name": "Kakuna",
    "slug": "kakuna",
    "nationalNumber": 14
  },
  {
    "name": "Beedrill",
    "slug": "beedrill",
    "nationalNumber": 15
  },
  {
    "name": "Pidgey",
    "slug": "pidgey",
    "nationalNumber": 16
  },
  {
    "name": "Pidgeotto",
    "slug": "pidgeotto",
    "nationalNumber": 17
  },
  {
    "name": "Pidgeot",
    "slug": "pidgeot",
    "nationalNumber": 18
  },
  {
    "name": "Rattata",
    "slug": "rattata",
    "nationalNumber": 19
  },
  {
    "name": "Raticate",
    "slug": "raticate",
    "nationalNumber": 20
  },
  {
    "name": "Spearow",
    "slug": "spearow",
    "nationalNumber": 21
  },
  {
    "name": "Fearow",
    "slug": "fearow",
    "nationalNumber": 22
  },
  {
    "name": "Ekans",
    "slug": "ekans",
    "nationalNumber": 23
  },
  {
    "name": "Arbok",
    "slug": "arbok",
    "nationalNumber": 24
  },
  {
    "name": "Nidoran♀",
    "slug": "nidoran-f",
    "nationalNumber": 29
  },
  {
    "name": "Nidorina",
    "slug": "nidorina",
    "nationalNumber": 30
  },
  {
    "name": "Nidoqueen",
    "slug": "nidoqueen",
    "nationalNumber": 31
  },
  {
    "name": "Nidoran♂",
    "slug": "nidoran-m",
    "nationalNumber": 32
  },
  {
    "name": "Nidorino",
    "slug": "nidorino",
    "nationalNumber": 33
  },
  {
    "name": "Nidoking",
    "slug": "nidoking",
    "nationalNumber": 34
  },
  {
    "name": "Clefairy",
    "slug": "clefairy",
    "nationalNumber": 35
  },
  {
    "name": "Clefable",
    "slug": "clefable",
    "nationalNumber": 36
  },
  {
    "name": "Paras",
    "slug": "paras",
    "nationalNumber": 46
  },
  {
    "name": "Parasect",
    "slug": "parasect",
    "nationalNumber": 47
  },
  {
    "name": "Venonat",
    "slug": "venonat",
    "nationalNumber": 48
  },
  {
    "name": "Venomoth",
    "slug": "venomoth",
    "nationalNumber": 49
  },
  {
    "name": "Diglett",
    "slug": "diglett",
    "nationalNumber": 50
  },
  {
    "name": "Dugtrio",
    "slug": "dugtrio",
    "nationalNumber": 51
  },
  {
    "name": "Meowth",
    "slug": "meowth",
    "nationalNumber": 52
  },
  {
    "name": "Persian",
    "slug": "persian",
    "nationalNumber": 53
  },
  {
    "name": "Mankey",
    "slug": "mankey",
    "nationalNumber": 56
  },
  {
    "name": "Primeape",
    "slug": "primeape",
    "nationalNumber": 57
  },
  {
    "name": "Growlithe",
    "slug": "growlithe",
    "nationalNumber": 58
  },
  {
    "name": "Arcanine",
    "slug": "arcanine",
    "nationalNumber": 59
  },
  {
    "name": "Poliwag",
    "slug": "poliwag",
    "nationalNumber": 60
  },
  {
    "name": "Poliwhirl",
    "slug": "poliwhirl",
    "nationalNumber": 61
  },
  {
    "name": "Poliwrath",
    "slug": "poliwrath",
    "nationalNumber": 62
  },
  {
    "name": "Bellsprout",
    "slug": "bellsprout",
    "nationalNumber": 69
  },
  {
    "name": "Weepinbell",
    "slug": "weepinbell",
    "nationalNumber": 70
  },
  {
    "name": "Victreebel",
    "slug": "victreebel",
    "nationalNumber": 71
  },
  {
    "name": "Ponyta",
    "slug": "ponyta",
    "nationalNumber": 77
  },
  {
    "name": "Rapidash",
    "slug": "rapidash",
    "nationalNumber": 78
  },
  {
    "name": "Slowpoke",
    "slug": "slowpoke",
    "nationalNumber": 79
  },
  {
    "name": "Slowbro",
    "slug": "slowbro",
    "nationalNumber": 80
  },
  {
    "name": "Farfetch'd",
    "slug": "farfetchd",
    "nationalNumber": 83
  },
  {
    "name": "Seel",
    "slug": "seel",
    "nationalNumber": 86
  },
  {
    "name": "Dewgong",
    "slug": "dewgong",
    "nationalNumber": 87
  },
  {
    "name": "Shellder",
    "slug": "shellder",
    "nationalNumber": 90
  },
  {
    "name": "Cloyster",
    "slug": "cloyster",
    "nationalNumber": 91
  },
  {
    "name": "Gastly",
    "slug": "gastly",
    "nationalNumber": 92
  },
  {
    "name": "Haunter",
    "slug": "haunter",
    "nationalNumber": 93
  },
  {
    "name": "Gengar",
    "slug": "gengar",
    "nationalNumber": 94
  },
  {
    "name": "Onix",
    "slug": "onix",
    "nationalNumber": 95
  },
  {
    "name": "Drowzee",
    "slug": "drowzee",
    "nationalNumber": 96
  },
  {
    "name": "Hypno",
    "slug": "hypno",
    "nationalNumber": 97
  },
  {
    "name": "Krabby",
    "slug": "krabby",
    "nationalNumber": 98
  },
  {
    "name": "Kingler",
    "slug": "kingler",
    "nationalNumber": 99
  },
  {
    "name": "Exeggcute",
    "slug": "exeggcute",
    "nationalNumber": 102
  },
  {
    "name": "Exeggutor",
    "slug": "exeggutor",
    "nationalNumber": 103
  },
  {
    "name": "Cubone",
    "slug": "cubone",
    "nationalNumber": 104
  },
  {
    "name": "Marowak",
    "slug": "marowak",
    "nationalNumber": 105
  },
  {
    "name": "Hitmonlee",
    "slug": "hitmonlee",
    "nationalNumber": 106
  },
  {
    "name": "Hitmonchan",
    "slug": "hitmonchan",
    "nationalNumber": 107
  },
  {
    "name": "Lickitung",
    "slug": "lickitung",
    "nationalNumber": 108
  },
  {
    "name": "Chansey",
    "slug": "chansey",
    "nationalNumber": 113
  },
  {
    "name": "Tangela",
    "slug": "tangela",
    "nationalNumber": 114
  },
  {
    "name": "Kangaskhan",
    "slug": "kangaskhan",
    "nationalNumber": 115
  },
  {
    "name": "Mr. Mime",
    "slug": "mr-mime",
    "nationalNumber": 122
  },
  {
    "name": "Scyther",
    "slug": "scyther",
    "nationalNumber": 123
  },
  {
    "name": "Jynx",
    "slug": "jynx",
    "nationalNumber": 124
  },
  {
    "name": "Electabuzz",
    "slug": "electabuzz",
    "nationalNumber": 125
  },
  {
    "name": "Magmar",
    "slug": "magmar",
    "nationalNumber": 126
  },
  {
    "name": "Tauros",
    "slug": "tauros",
    "nationalNumber": 128
  },
  {
    "name": "Lapras",
    "slug": "lapras",
    "nationalNumber": 131
  },
  {
    "name": "Ditto",
    "slug": "ditto",
    "nationalNumber": 132
  },
  {
    "name": "Eevee",
    "slug": "eevee",
    "nationalNumber": 133
  },
  {
    "name": "Vaporeon",
    "slug": "vaporeon",
    "nationalNumber": 134
  },
  {
    "name": "Jolteon",
    "slug": "jolteon",
    "nationalNumber": 135
  },
  {
    "name": "Flareon",
    "slug": "flareon",
    "nationalNumber": 136
  },
  {
    "name": "Porygon",
    "slug": "porygon",
    "nationalNumber": 137
  },
  {
    "name": "Omanyte",
    "slug": "omanyte",
    "nationalNumber": 138
  },
  {
    "name": "Omastar",
    "slug": "omastar",
    "nationalNumber": 139
  },
  {
    "name": "Kabuto",
    "slug": "kabuto",
    "nationalNumber": 140
  },
  {
    "name": "Kabutops",
    "slug": "kabutops",
    "nationalNumber": 141
  },
  {
    "name": "Aerodactyl",
    "slug": "aerodactyl",
    "nationalNumber": 142
  },
  {
    "name": "Snorlax",
    "slug": "snorlax",
    "nationalNumber": 143
  },
  {
    "name": "Articuno",
    "slug": "articuno",
    "nationalNumber": 144
  },
  {
    "name": "Zapdos",
    "slug": "zapdos",
    "nationalNumber": 145
  },
  {
    "name": "Moltres",
    "slug": "moltres",
    "nationalNumber": 146
  },
  {
    "name": "Dratini",
    "slug": "dratini",
    "nationalNumber": 147
  },
  {
    "name": "Dragonair",
    "slug": "dragonair",
    "nationalNumber": 148
  },
  {
    "name": "Dragonite",
    "slug": "dragonite",
    "nationalNumber": 149
  },
  {
    "name": "Mewtwo",
    "slug": "mewtwo",
    "nationalNumber": 150
  },
  {
    "name": "Mew",
    "slug": "mew",
    "nationalNumber": 151
  },
  {
    "name": "Chikorita",
    "slug": "chikorita",
    "nationalNumber": 152
  },
  {
    "name": "Bayleef",
    "slug": "bayleef",
    "nationalNumber": 153
  },
  {
    "name": "Meganium",
    "slug": "meganium",
    "nationalNumber": 154
  },
  {
    "name": "Cyndaquil",
    "slug": "cyndaquil",
    "nationalNumber": 155
  },
  {
    "name": "Quilava",
    "slug": "quilava",
    "nationalNumber": 156
  },
  {
    "name": "Typhlosion",
    "slug": "typhlosion",
    "nationalNumber": 157
  },
  {
    "name": "Totodile",
    "slug": "totodile",
    "nationalNumber": 158
  },
  {
    "name": "Croconaw",
    "slug": "croconaw",
    "nationalNumber": 159
  },
  {
    "name": "Feraligatr",
    "slug": "feraligatr",
    "nationalNumber": 160
  },
  {
    "name": "Sentret",
    "slug": "sentret",
    "nationalNumber": 161
  },
  {
    "name": "Furret",
    "slug": "furret",
    "nationalNumber": 162
  },
  {
    "name": "Hoothoot",
    "slug": "hoothoot",
    "nationalNumber": 163
  },
  {
    "name": "Noctowl",
    "slug": "noctowl",
    "nationalNumber": 164
  },
  {
    "name": "Ledyba",
    "slug": "ledyba",
    "nationalNumber": 165
  },
  {
    "name": "Ledian",
    "slug": "ledian",
    "nationalNumber": 166
  },
  {
    "name": "Spinarak",
    "slug": "spinarak",
    "nationalNumber": 167
  },
  {
    "name": "Ariados",
    "slug": "ariados",
    "nationalNumber": 168
  },
  {
    "name": "Cleffa",
    "slug": "cleffa",
    "nationalNumber": 173
  },
  {
    "name": "Togepi",
    "slug": "togepi",
    "nationalNumber": 175
  },
  {
    "name": "Togetic",
    "slug": "togetic",
    "nationalNumber": 176
  },
  {
    "name": "Mareep",
    "slug": "mareep",
    "nationalNumber": 179
  },
  {
    "name": "Flaaffy",
    "slug": "flaaffy",
    "nationalNumber": 180
  },
  {
    "name": "Ampharos",
    "slug": "ampharos",
    "nationalNumber": 181
  },
  {
    "name": "Sudowoodo",
    "slug": "sudowoodo",
    "nationalNumber": 185
  },
  {
    "name": "Politoed",
    "slug": "politoed",
    "nationalNumber": 186
  },
  {
    "name": "Hoppip",
    "slug": "hoppip",
    "nationalNumber": 187
  },
  {
    "name": "Skiploom",
    "slug": "skiploom",
    "nationalNumber": 188
  },
  {
    "name": "Jumpluff",
    "slug": "jumpluff",
    "nationalNumber": 189
  },
  {
    "name": "Aipom",
    "slug": "aipom",
    "nationalNumber": 190
  },
  {
    "name": "Sunkern",
    "slug": "sunkern",
    "nationalNumber": 191
  },
  {
    "name": "Sunflora",
    "slug": "sunflora",
    "nationalNumber": 192
  },
  {
    "name": "Yanma",
    "slug": "yanma",
    "nationalNumber": 193
  },
  {
    "name": "Wooper",
    "slug": "wooper",
    "nationalNumber": 194
  },
  {
    "name": "Quagsire",
    "slug": "quagsire",
    "nationalNumber": 195
  },
  {
    "name": "Espeon",
    "slug": "espeon",
    "nationalNumber": 196
  },
  {
    "name": "Umbreon",
    "slug": "umbreon",
    "nationalNumber": 197
  },
  {
    "name": "Murkrow",
    "slug": "murkrow",
    "nationalNumber": 198
  },
  {
    "name": "Slowking",
    "slug": "slowking",
    "nationalNumber": 199
  },
  {
    "name": "Misdreavus",
    "slug": "misdreavus",
    "nationalNumber": 200
  },
  {
    "name": "Unown",
    "slug": "unown",
    "nationalNumber": 201
  },
  {
    "name": "Pineco",
    "slug": "pineco",
    "nationalNumber": 204
  },
  {
    "name": "Forretress",
    "slug": "forretress",
    "nationalNumber": 205
  },
  {
    "name": "Dunsparce",
    "slug": "dunsparce",
    "nationalNumber": 206
  },
  {
    "name": "Gligar",
    "slug": "gligar",
    "nationalNumber": 207
  },
  {
    "name": "Steelix",
    "slug": "steelix",
    "nationalNumber": 208
  },
  {
    "name": "Snubbull",
    "slug": "snubbull",
    "nationalNumber": 209
  },
  {
    "name": "Granbull",
    "slug": "granbull",
    "nationalNumber": 210
  },
  {
    "name": "Qwilfish",
    "slug": "qwilfish",
    "nationalNumber": 211
  },
  {
    "name": "Scizor",
    "slug": "scizor",
    "nationalNumber": 212
  },
  {
    "name": "Shuckle",
    "slug": "shuckle",
    "nationalNumber": 213
  },
  {
    "name": "Sneasel",
    "slug": "sneasel",
    "nationalNumber": 215
  },
  {
    "name": "Teddiursa",
    "slug": "teddiursa",
    "nationalNumber": 216
  },
  {
    "name": "Ursaring",
    "slug": "ursaring",
    "nationalNumber": 217
  },
  {
    "name": "Swinub",
    "slug": "swinub",
    "nationalNumber": 220
  },
  {
    "name": "Piloswine",
    "slug": "piloswine",
    "nationalNumber": 221
  },
  {
    "name": "Remoraid",
    "slug": "remoraid",
    "nationalNumber": 223
  },
  {
    "name": "Octillery",
    "slug": "octillery",
    "nationalNumber": 224
  },
  {
    "name": "Delibird",
    "slug": "delibird",
    "nationalNumber": 225
  },
  {
    "name": "Mantine",
    "slug": "mantine",
    "nationalNumber": 226
  },
  {
    "name": "Houndour",
    "slug": "houndour",
    "nationalNumber": 228
  },
  {
    "name": "Houndoom",
    "slug": "houndoom",
    "nationalNumber": 229
  },
  {
    "name": "Porygon2",
    "slug": "porygon2",
    "nationalNumber": 233
  },
  {
    "name": "Stantler",
    "slug": "stantler",
    "nationalNumber": 234
  },
  {
    "name": "Smeargle",
    "slug": "smeargle",
    "nationalNumber": 235
  },
  {
    "name": "Tyrogue",
    "slug": "tyrogue",
    "nationalNumber": 236
  },
  {
    "name": "Hitmontop",
    "slug": "hitmontop",
    "nationalNumber": 237
  },
  {
    "name": "Smoochum",
    "slug": "smoochum",
    "nationalNumber": 238
  },
  {
    "name": "Elekid",
    "slug": "elekid",
    "nationalNumber": 239
  },
  {
    "name": "Magby",
    "slug": "magby",
    "nationalNumber": 240
  },
  {
    "name": "Miltank",
    "slug": "miltank",
    "nationalNumber": 241
  },
  {
    "name": "Blissey",
    "slug": "blissey",
    "nationalNumber": 242
  },
  {
    "name": "Raikou",
    "slug": "raikou",
    "nationalNumber": 243
  },
  {
    "name": "Entei",
    "slug": "entei",
    "nationalNumber": 244
  },
  {
    "name": "Suicune",
    "slug": "suicune",
    "nationalNumber": 245
  },
  {
    "name": "Larvitar",
    "slug": "larvitar",
    "nationalNumber": 246
  },
  {
    "name": "Pupitar",
    "slug": "pupitar",
    "nationalNumber": 247
  },
  {
    "name": "Tyranitar",
    "slug": "tyranitar",
    "nationalNumber": 248
  },
  {
    "name": "Lugia",
    "slug": "lugia",
    "nationalNumber": 249
  },
  {
    "name": "Ho-Oh",
    "slug": "ho-oh",
    "nationalNumber": 250
  },
  {
    "name": "Celebi",
    "slug": "celebi",
    "nationalNumber": 251
  },
  {
    "name": "?????????? (Decamark)",
    "slug": "",
    "nationalNumber": 387,
    "isGlitch": true
  }
];

export const ALL_DEX: DexEntry[] = [
  {
    "name": "Bulbasaur",
    "slug": "bulbasaur",
    "nationalNumber": 1
  },
  {
    "name": "Ivysaur",
    "slug": "ivysaur",
    "nationalNumber": 2
  },
  {
    "name": "Venusaur",
    "slug": "venusaur",
    "nationalNumber": 3
  },
  {
    "name": "Charmander",
    "slug": "charmander",
    "nationalNumber": 4
  },
  {
    "name": "Charmeleon",
    "slug": "charmeleon",
    "nationalNumber": 5
  },
  {
    "name": "Charizard",
    "slug": "charizard",
    "nationalNumber": 6
  },
  {
    "name": "Squirtle",
    "slug": "squirtle",
    "nationalNumber": 7
  },
  {
    "name": "Wartortle",
    "slug": "wartortle",
    "nationalNumber": 8
  },
  {
    "name": "Blastoise",
    "slug": "blastoise",
    "nationalNumber": 9
  },
  {
    "name": "Caterpie",
    "slug": "caterpie",
    "nationalNumber": 10
  },
  {
    "name": "Metapod",
    "slug": "metapod",
    "nationalNumber": 11
  },
  {
    "name": "Butterfree",
    "slug": "butterfree",
    "nationalNumber": 12
  },
  {
    "name": "Weedle",
    "slug": "weedle",
    "nationalNumber": 13
  },
  {
    "name": "Kakuna",
    "slug": "kakuna",
    "nationalNumber": 14
  },
  {
    "name": "Beedrill",
    "slug": "beedrill",
    "nationalNumber": 15
  },
  {
    "name": "Pidgey",
    "slug": "pidgey",
    "nationalNumber": 16
  },
  {
    "name": "Pidgeotto",
    "slug": "pidgeotto",
    "nationalNumber": 17
  },
  {
    "name": "Pidgeot",
    "slug": "pidgeot",
    "nationalNumber": 18
  },
  {
    "name": "Rattata",
    "slug": "rattata",
    "nationalNumber": 19
  },
  {
    "name": "Raticate",
    "slug": "raticate",
    "nationalNumber": 20
  },
  {
    "name": "Spearow",
    "slug": "spearow",
    "nationalNumber": 21
  },
  {
    "name": "Fearow",
    "slug": "fearow",
    "nationalNumber": 22
  },
  {
    "name": "Ekans",
    "slug": "ekans",
    "nationalNumber": 23
  },
  {
    "name": "Arbok",
    "slug": "arbok",
    "nationalNumber": 24
  },
  {
    "name": "Pikachu",
    "slug": "pikachu",
    "hoennNumber": 156,
    "nationalNumber": 25
  },
  {
    "name": "Raichu",
    "slug": "raichu",
    "hoennNumber": 157,
    "nationalNumber": 26
  },
  {
    "name": "Sandshrew",
    "slug": "sandshrew",
    "hoennNumber": 112,
    "nationalNumber": 27
  },
  {
    "name": "Sandslash",
    "slug": "sandslash",
    "hoennNumber": 113,
    "nationalNumber": 28
  },
  {
    "name": "Nidoran♀",
    "slug": "nidoran-f",
    "nationalNumber": 29
  },
  {
    "name": "Nidorina",
    "slug": "nidorina",
    "nationalNumber": 30
  },
  {
    "name": "Nidoqueen",
    "slug": "nidoqueen",
    "nationalNumber": 31
  },
  {
    "name": "Nidoran♂",
    "slug": "nidoran-m",
    "nationalNumber": 32
  },
  {
    "name": "Nidorino",
    "slug": "nidorino",
    "nationalNumber": 33
  },
  {
    "name": "Nidoking",
    "slug": "nidoking",
    "nationalNumber": 34
  },
  {
    "name": "Clefairy",
    "slug": "clefairy",
    "nationalNumber": 35
  },
  {
    "name": "Clefable",
    "slug": "clefable",
    "nationalNumber": 36
  },
  {
    "name": "Vulpix",
    "slug": "vulpix",
    "hoennNumber": 153,
    "nationalNumber": 37
  },
  {
    "name": "Ninetales",
    "slug": "ninetales",
    "hoennNumber": 154,
    "nationalNumber": 38
  },
  {
    "name": "Jigglypuff",
    "slug": "jigglypuff",
    "hoennNumber": 138,
    "nationalNumber": 39
  },
  {
    "name": "Wigglytuff",
    "slug": "wigglytuff",
    "hoennNumber": 139,
    "nationalNumber": 40
  },
  {
    "name": "Zubat",
    "slug": "zubat",
    "hoennNumber": 63,
    "nationalNumber": 41
  },
  {
    "name": "Golbat",
    "slug": "golbat",
    "hoennNumber": 64,
    "nationalNumber": 42
  },
  {
    "name": "Oddish",
    "slug": "oddish",
    "hoennNumber": 88,
    "nationalNumber": 43
  },
  {
    "name": "Gloom",
    "slug": "gloom",
    "hoennNumber": 89,
    "nationalNumber": 44
  },
  {
    "name": "Vileplume",
    "slug": "vileplume",
    "hoennNumber": 90,
    "nationalNumber": 45
  },
  {
    "name": "Paras",
    "slug": "paras",
    "nationalNumber": 46
  },
  {
    "name": "Parasect",
    "slug": "parasect",
    "nationalNumber": 47
  },
  {
    "name": "Venonat",
    "slug": "venonat",
    "nationalNumber": 48
  },
  {
    "name": "Venomoth",
    "slug": "venomoth",
    "nationalNumber": 49
  },
  {
    "name": "Diglett",
    "slug": "diglett",
    "nationalNumber": 50
  },
  {
    "name": "Dugtrio",
    "slug": "dugtrio",
    "nationalNumber": 51
  },
  {
    "name": "Meowth",
    "slug": "meowth",
    "nationalNumber": 52
  },
  {
    "name": "Persian",
    "slug": "persian",
    "nationalNumber": 53
  },
  {
    "name": "Psyduck",
    "slug": "psyduck",
    "hoennNumber": 158,
    "nationalNumber": 54
  },
  {
    "name": "Golduck",
    "slug": "golduck",
    "hoennNumber": 159,
    "nationalNumber": 55
  },
  {
    "name": "Mankey",
    "slug": "mankey",
    "nationalNumber": 56
  },
  {
    "name": "Primeape",
    "slug": "primeape",
    "nationalNumber": 57
  },
  {
    "name": "Growlithe",
    "slug": "growlithe",
    "nationalNumber": 58
  },
  {
    "name": "Arcanine",
    "slug": "arcanine",
    "nationalNumber": 59
  },
  {
    "name": "Poliwag",
    "slug": "poliwag",
    "nationalNumber": 60
  },
  {
    "name": "Poliwhirl",
    "slug": "poliwhirl",
    "nationalNumber": 61
  },
  {
    "name": "Poliwrath",
    "slug": "poliwrath",
    "nationalNumber": 62
  },
  {
    "name": "Abra",
    "slug": "abra",
    "hoennNumber": 39,
    "nationalNumber": 63
  },
  {
    "name": "Kadabra",
    "slug": "kadabra",
    "hoennNumber": 40,
    "nationalNumber": 64
  },
  {
    "name": "Alakazam",
    "slug": "alakazam",
    "hoennNumber": 41,
    "nationalNumber": 65
  },
  {
    "name": "Machop",
    "slug": "machop",
    "hoennNumber": 73,
    "nationalNumber": 66
  },
  {
    "name": "Machoke",
    "slug": "machoke",
    "hoennNumber": 74,
    "nationalNumber": 67
  },
  {
    "name": "Machamp",
    "slug": "machamp",
    "hoennNumber": 75,
    "nationalNumber": 68
  },
  {
    "name": "Bellsprout",
    "slug": "bellsprout",
    "nationalNumber": 69
  },
  {
    "name": "Weepinbell",
    "slug": "weepinbell",
    "nationalNumber": 70
  },
  {
    "name": "Victreebel",
    "slug": "victreebel",
    "nationalNumber": 71
  },
  {
    "name": "Tentacool",
    "slug": "tentacool",
    "hoennNumber": 66,
    "nationalNumber": 72
  },
  {
    "name": "Tentacruel",
    "slug": "tentacruel",
    "hoennNumber": 67,
    "nationalNumber": 73
  },
  {
    "name": "Geodude",
    "slug": "geodude",
    "hoennNumber": 57,
    "nationalNumber": 74
  },
  {
    "name": "Graveler",
    "slug": "graveler",
    "hoennNumber": 58,
    "nationalNumber": 75
  },
  {
    "name": "Golem",
    "slug": "golem",
    "hoennNumber": 59,
    "nationalNumber": 76
  },
  {
    "name": "Ponyta",
    "slug": "ponyta",
    "nationalNumber": 77
  },
  {
    "name": "Rapidash",
    "slug": "rapidash",
    "nationalNumber": 78
  },
  {
    "name": "Slowpoke",
    "slug": "slowpoke",
    "nationalNumber": 79
  },
  {
    "name": "Slowbro",
    "slug": "slowbro",
    "nationalNumber": 80
  },
  {
    "name": "Magnemite",
    "slug": "magnemite",
    "hoennNumber": 82,
    "nationalNumber": 81
  },
  {
    "name": "Magneton",
    "slug": "magneton",
    "hoennNumber": 83,
    "nationalNumber": 82
  },
  {
    "name": "Farfetch'd",
    "slug": "farfetchd",
    "nationalNumber": 83
  },
  {
    "name": "Doduo",
    "slug": "doduo",
    "hoennNumber": 92,
    "nationalNumber": 84
  },
  {
    "name": "Dodrio",
    "slug": "dodrio",
    "hoennNumber": 93,
    "nationalNumber": 85
  },
  {
    "name": "Seel",
    "slug": "seel",
    "nationalNumber": 86
  },
  {
    "name": "Dewgong",
    "slug": "dewgong",
    "nationalNumber": 87
  },
  {
    "name": "Grimer",
    "slug": "grimer",
    "hoennNumber": 106,
    "nationalNumber": 88
  },
  {
    "name": "Muk",
    "slug": "muk",
    "hoennNumber": 107,
    "nationalNumber": 89
  },
  {
    "name": "Shellder",
    "slug": "shellder",
    "nationalNumber": 90
  },
  {
    "name": "Cloyster",
    "slug": "cloyster",
    "nationalNumber": 91
  },
  {
    "name": "Gastly",
    "slug": "gastly",
    "nationalNumber": 92
  },
  {
    "name": "Haunter",
    "slug": "haunter",
    "nationalNumber": 93
  },
  {
    "name": "Gengar",
    "slug": "gengar",
    "nationalNumber": 94
  },
  {
    "name": "Onix",
    "slug": "onix",
    "nationalNumber": 95
  },
  {
    "name": "Drowzee",
    "slug": "drowzee",
    "nationalNumber": 96
  },
  {
    "name": "Hypno",
    "slug": "hypno",
    "nationalNumber": 97
  },
  {
    "name": "Krabby",
    "slug": "krabby",
    "nationalNumber": 98
  },
  {
    "name": "Kingler",
    "slug": "kingler",
    "nationalNumber": 99
  },
  {
    "name": "Voltorb",
    "slug": "voltorb",
    "hoennNumber": 84,
    "nationalNumber": 100
  },
  {
    "name": "Electrode",
    "slug": "electrode",
    "hoennNumber": 85,
    "nationalNumber": 101
  },
  {
    "name": "Exeggcute",
    "slug": "exeggcute",
    "nationalNumber": 102
  },
  {
    "name": "Exeggutor",
    "slug": "exeggutor",
    "nationalNumber": 103
  },
  {
    "name": "Cubone",
    "slug": "cubone",
    "nationalNumber": 104
  },
  {
    "name": "Marowak",
    "slug": "marowak",
    "nationalNumber": 105
  },
  {
    "name": "Hitmonlee",
    "slug": "hitmonlee",
    "nationalNumber": 106
  },
  {
    "name": "Hitmonchan",
    "slug": "hitmonchan",
    "nationalNumber": 107
  },
  {
    "name": "Lickitung",
    "slug": "lickitung",
    "nationalNumber": 108
  },
  {
    "name": "Koffing",
    "slug": "koffing",
    "hoennNumber": 108,
    "nationalNumber": 109
  },
  {
    "name": "Weezing",
    "slug": "weezing",
    "hoennNumber": 109,
    "nationalNumber": 110
  },
  {
    "name": "Rhyhorn",
    "slug": "rhyhorn",
    "hoennNumber": 169,
    "nationalNumber": 111
  },
  {
    "name": "Rhydon",
    "slug": "rhydon",
    "hoennNumber": 170,
    "nationalNumber": 112
  },
  {
    "name": "Chansey",
    "slug": "chansey",
    "nationalNumber": 113
  },
  {
    "name": "Tangela",
    "slug": "tangela",
    "nationalNumber": 114
  },
  {
    "name": "Kangaskhan",
    "slug": "kangaskhan",
    "nationalNumber": 115
  },
  {
    "name": "Horsea",
    "slug": "horsea",
    "hoennNumber": 184,
    "nationalNumber": 116
  },
  {
    "name": "Seadra",
    "slug": "seadra",
    "hoennNumber": 185,
    "nationalNumber": 117
  },
  {
    "name": "Goldeen",
    "slug": "goldeen",
    "hoennNumber": 50,
    "nationalNumber": 118
  },
  {
    "name": "Seaking",
    "slug": "seaking",
    "hoennNumber": 51,
    "nationalNumber": 119
  },
  {
    "name": "Staryu",
    "slug": "staryu",
    "hoennNumber": 143,
    "nationalNumber": 120
  },
  {
    "name": "Starmie",
    "slug": "starmie",
    "hoennNumber": 144,
    "nationalNumber": 121
  },
  {
    "name": "Mr. Mime",
    "slug": "mr-mime",
    "nationalNumber": 122
  },
  {
    "name": "Scyther",
    "slug": "scyther",
    "nationalNumber": 123
  },
  {
    "name": "Jynx",
    "slug": "jynx",
    "nationalNumber": 124
  },
  {
    "name": "Electabuzz",
    "slug": "electabuzz",
    "nationalNumber": 125
  },
  {
    "name": "Magmar",
    "slug": "magmar",
    "nationalNumber": 126
  },
  {
    "name": "Pinsir",
    "slug": "pinsir",
    "hoennNumber": 167,
    "nationalNumber": 127
  },
  {
    "name": "Tauros",
    "slug": "tauros",
    "nationalNumber": 128
  },
  {
    "name": "Magikarp",
    "slug": "magikarp",
    "hoennNumber": 52,
    "nationalNumber": 129
  },
  {
    "name": "Gyarados",
    "slug": "gyarados",
    "hoennNumber": 53,
    "nationalNumber": 130
  },
  {
    "name": "Lapras",
    "slug": "lapras",
    "nationalNumber": 131
  },
  {
    "name": "Ditto",
    "slug": "ditto",
    "nationalNumber": 132
  },
  {
    "name": "Eevee",
    "slug": "eevee",
    "nationalNumber": 133
  },
  {
    "name": "Vaporeon",
    "slug": "vaporeon",
    "nationalNumber": 134
  },
  {
    "name": "Jolteon",
    "slug": "jolteon",
    "nationalNumber": 135
  },
  {
    "name": "Flareon",
    "slug": "flareon",
    "nationalNumber": 136
  },
  {
    "name": "Porygon",
    "slug": "porygon",
    "nationalNumber": 137
  },
  {
    "name": "Omanyte",
    "slug": "omanyte",
    "nationalNumber": 138
  },
  {
    "name": "Omastar",
    "slug": "omastar",
    "nationalNumber": 139
  },
  {
    "name": "Kabuto",
    "slug": "kabuto",
    "nationalNumber": 140
  },
  {
    "name": "Kabutops",
    "slug": "kabutops",
    "nationalNumber": 141
  },
  {
    "name": "Aerodactyl",
    "slug": "aerodactyl",
    "nationalNumber": 142
  },
  {
    "name": "Snorlax",
    "slug": "snorlax",
    "nationalNumber": 143
  },
  {
    "name": "Articuno",
    "slug": "articuno",
    "nationalNumber": 144
  },
  {
    "name": "Zapdos",
    "slug": "zapdos",
    "nationalNumber": 145
  },
  {
    "name": "Moltres",
    "slug": "moltres",
    "nationalNumber": 146
  },
  {
    "name": "Dratini",
    "slug": "dratini",
    "nationalNumber": 147
  },
  {
    "name": "Dragonair",
    "slug": "dragonair",
    "nationalNumber": 148
  },
  {
    "name": "Dragonite",
    "slug": "dragonite",
    "nationalNumber": 149
  },
  {
    "name": "Mewtwo",
    "slug": "mewtwo",
    "nationalNumber": 150
  },
  {
    "name": "Mew",
    "slug": "mew",
    "nationalNumber": 151
  },
  {
    "name": "Chikorita",
    "slug": "chikorita",
    "nationalNumber": 152
  },
  {
    "name": "Bayleef",
    "slug": "bayleef",
    "nationalNumber": 153
  },
  {
    "name": "Meganium",
    "slug": "meganium",
    "nationalNumber": 154
  },
  {
    "name": "Cyndaquil",
    "slug": "cyndaquil",
    "nationalNumber": 155
  },
  {
    "name": "Quilava",
    "slug": "quilava",
    "nationalNumber": 156
  },
  {
    "name": "Typhlosion",
    "slug": "typhlosion",
    "nationalNumber": 157
  },
  {
    "name": "Totodile",
    "slug": "totodile",
    "nationalNumber": 158
  },
  {
    "name": "Croconaw",
    "slug": "croconaw",
    "nationalNumber": 159
  },
  {
    "name": "Feraligatr",
    "slug": "feraligatr",
    "nationalNumber": 160
  },
  {
    "name": "Sentret",
    "slug": "sentret",
    "nationalNumber": 161
  },
  {
    "name": "Furret",
    "slug": "furret",
    "nationalNumber": 162
  },
  {
    "name": "Hoothoot",
    "slug": "hoothoot",
    "nationalNumber": 163
  },
  {
    "name": "Noctowl",
    "slug": "noctowl",
    "nationalNumber": 164
  },
  {
    "name": "Ledyba",
    "slug": "ledyba",
    "nationalNumber": 165
  },
  {
    "name": "Ledian",
    "slug": "ledian",
    "nationalNumber": 166
  },
  {
    "name": "Spinarak",
    "slug": "spinarak",
    "nationalNumber": 167
  },
  {
    "name": "Ariados",
    "slug": "ariados",
    "nationalNumber": 168
  },
  {
    "name": "Crobat",
    "slug": "crobat",
    "hoennNumber": 65,
    "nationalNumber": 169
  },
  {
    "name": "Chinchou",
    "slug": "chinchou",
    "hoennNumber": 181,
    "nationalNumber": 170
  },
  {
    "name": "Lanturn",
    "slug": "lanturn",
    "hoennNumber": 182,
    "nationalNumber": 171
  },
  {
    "name": "Pichu",
    "slug": "pichu",
    "hoennNumber": 155,
    "nationalNumber": 172
  },
  {
    "name": "Cleffa",
    "slug": "cleffa",
    "nationalNumber": 173
  },
  {
    "name": "Igglybuff",
    "slug": "igglybuff",
    "hoennNumber": 137,
    "nationalNumber": 174
  },
  {
    "name": "Togepi",
    "slug": "togepi",
    "nationalNumber": 175
  },
  {
    "name": "Togetic",
    "slug": "togetic",
    "nationalNumber": 176
  },
  {
    "name": "Natu",
    "slug": "natu",
    "hoennNumber": 162,
    "nationalNumber": 177
  },
  {
    "name": "Xatu",
    "slug": "xatu",
    "hoennNumber": 163,
    "nationalNumber": 178
  },
  {
    "name": "Mareep",
    "slug": "mareep",
    "nationalNumber": 179
  },
  {
    "name": "Flaaffy",
    "slug": "flaaffy",
    "nationalNumber": 180
  },
  {
    "name": "Ampharos",
    "slug": "ampharos",
    "nationalNumber": 181
  },
  {
    "name": "Bellossom",
    "slug": "bellossom",
    "hoennNumber": 91,
    "nationalNumber": 182
  },
  {
    "name": "Marill",
    "slug": "marill",
    "hoennNumber": 55,
    "nationalNumber": 183
  },
  {
    "name": "Azumarill",
    "slug": "azumarill",
    "hoennNumber": 56,
    "nationalNumber": 184
  },
  {
    "name": "Sudowoodo",
    "slug": "sudowoodo",
    "nationalNumber": 185
  },
  {
    "name": "Politoed",
    "slug": "politoed",
    "nationalNumber": 186
  },
  {
    "name": "Hoppip",
    "slug": "hoppip",
    "nationalNumber": 187
  },
  {
    "name": "Skiploom",
    "slug": "skiploom",
    "nationalNumber": 188
  },
  {
    "name": "Jumpluff",
    "slug": "jumpluff",
    "nationalNumber": 189
  },
  {
    "name": "Aipom",
    "slug": "aipom",
    "nationalNumber": 190
  },
  {
    "name": "Sunkern",
    "slug": "sunkern",
    "nationalNumber": 191
  },
  {
    "name": "Sunflora",
    "slug": "sunflora",
    "nationalNumber": 192
  },
  {
    "name": "Yanma",
    "slug": "yanma",
    "nationalNumber": 193
  },
  {
    "name": "Wooper",
    "slug": "wooper",
    "nationalNumber": 194
  },
  {
    "name": "Quagsire",
    "slug": "quagsire",
    "nationalNumber": 195
  },
  {
    "name": "Espeon",
    "slug": "espeon",
    "nationalNumber": 196
  },
  {
    "name": "Umbreon",
    "slug": "umbreon",
    "nationalNumber": 197
  },
  {
    "name": "Murkrow",
    "slug": "murkrow",
    "nationalNumber": 198
  },
  {
    "name": "Slowking",
    "slug": "slowking",
    "nationalNumber": 199
  },
  {
    "name": "Misdreavus",
    "slug": "misdreavus",
    "nationalNumber": 200
  },
  {
    "name": "Unown",
    "slug": "unown",
    "nationalNumber": 201
  },
  {
    "name": "Wobbuffet",
    "slug": "wobbuffet",
    "hoennNumber": 161,
    "nationalNumber": 202
  },
  {
    "name": "Girafarig",
    "slug": "girafarig",
    "hoennNumber": 164,
    "nationalNumber": 203
  },
  {
    "name": "Pineco",
    "slug": "pineco",
    "nationalNumber": 204
  },
  {
    "name": "Forretress",
    "slug": "forretress",
    "nationalNumber": 205
  },
  {
    "name": "Dunsparce",
    "slug": "dunsparce",
    "nationalNumber": 206
  },
  {
    "name": "Gligar",
    "slug": "gligar",
    "nationalNumber": 207
  },
  {
    "name": "Steelix",
    "slug": "steelix",
    "nationalNumber": 208
  },
  {
    "name": "Snubbull",
    "slug": "snubbull",
    "nationalNumber": 209
  },
  {
    "name": "Granbull",
    "slug": "granbull",
    "nationalNumber": 210
  },
  {
    "name": "Qwilfish",
    "slug": "qwilfish",
    "nationalNumber": 211
  },
  {
    "name": "Scizor",
    "slug": "scizor",
    "nationalNumber": 212
  },
  {
    "name": "Shuckle",
    "slug": "shuckle",
    "nationalNumber": 213
  },
  {
    "name": "Heracross",
    "slug": "heracross",
    "hoennNumber": 168,
    "nationalNumber": 214
  },
  {
    "name": "Sneasel",
    "slug": "sneasel",
    "nationalNumber": 215
  },
  {
    "name": "Teddiursa",
    "slug": "teddiursa",
    "nationalNumber": 216
  },
  {
    "name": "Ursaring",
    "slug": "ursaring",
    "nationalNumber": 217
  },
  {
    "name": "Slugma",
    "slug": "slugma",
    "hoennNumber": 103,
    "nationalNumber": 218
  },
  {
    "name": "Magcargo",
    "slug": "magcargo",
    "hoennNumber": 104,
    "nationalNumber": 219
  },
  {
    "name": "Swinub",
    "slug": "swinub",
    "nationalNumber": 220
  },
  {
    "name": "Piloswine",
    "slug": "piloswine",
    "nationalNumber": 221
  },
  {
    "name": "Corsola",
    "slug": "corsola",
    "hoennNumber": 180,
    "nationalNumber": 222
  },
  {
    "name": "Remoraid",
    "slug": "remoraid",
    "nationalNumber": 223
  },
  {
    "name": "Octillery",
    "slug": "octillery",
    "nationalNumber": 224
  },
  {
    "name": "Delibird",
    "slug": "delibird",
    "nationalNumber": 225
  },
  {
    "name": "Mantine",
    "slug": "mantine",
    "nationalNumber": 226
  },
  {
    "name": "Skarmory",
    "slug": "skarmory",
    "hoennNumber": 115,
    "nationalNumber": 227
  },
  {
    "name": "Houndour",
    "slug": "houndour",
    "nationalNumber": 228
  },
  {
    "name": "Houndoom",
    "slug": "houndoom",
    "nationalNumber": 229
  },
  {
    "name": "Kingdra",
    "slug": "kingdra",
    "hoennNumber": 186,
    "nationalNumber": 230
  },
  {
    "name": "Phanpy",
    "slug": "phanpy",
    "hoennNumber": 165,
    "nationalNumber": 231
  },
  {
    "name": "Donphan",
    "slug": "donphan",
    "hoennNumber": 166,
    "nationalNumber": 232
  },
  {
    "name": "Porygon2",
    "slug": "porygon2",
    "nationalNumber": 233
  },
  {
    "name": "Stantler",
    "slug": "stantler",
    "nationalNumber": 234
  },
  {
    "name": "Smeargle",
    "slug": "smeargle",
    "nationalNumber": 235
  },
  {
    "name": "Tyrogue",
    "slug": "tyrogue",
    "nationalNumber": 236
  },
  {
    "name": "Hitmontop",
    "slug": "hitmontop",
    "nationalNumber": 237
  },
  {
    "name": "Smoochum",
    "slug": "smoochum",
    "nationalNumber": 238
  },
  {
    "name": "Elekid",
    "slug": "elekid",
    "nationalNumber": 239
  },
  {
    "name": "Magby",
    "slug": "magby",
    "nationalNumber": 240
  },
  {
    "name": "Miltank",
    "slug": "miltank",
    "nationalNumber": 241
  },
  {
    "name": "Blissey",
    "slug": "blissey",
    "nationalNumber": 242
  },
  {
    "name": "Raikou",
    "slug": "raikou",
    "nationalNumber": 243
  },
  {
    "name": "Entei",
    "slug": "entei",
    "nationalNumber": 244
  },
  {
    "name": "Suicune",
    "slug": "suicune",
    "nationalNumber": 245
  },
  {
    "name": "Larvitar",
    "slug": "larvitar",
    "nationalNumber": 246
  },
  {
    "name": "Pupitar",
    "slug": "pupitar",
    "nationalNumber": 247
  },
  {
    "name": "Tyranitar",
    "slug": "tyranitar",
    "nationalNumber": 248
  },
  {
    "name": "Lugia",
    "slug": "lugia",
    "nationalNumber": 249
  },
  {
    "name": "Ho-Oh",
    "slug": "ho-oh",
    "nationalNumber": 250
  },
  {
    "name": "Celebi",
    "slug": "celebi",
    "nationalNumber": 251
  },
  {
    "name": "Treecko",
    "slug": "treecko",
    "hoennNumber": 1,
    "nationalNumber": 252
  },
  {
    "name": "Grovyle",
    "slug": "grovyle",
    "hoennNumber": 2,
    "nationalNumber": 253
  },
  {
    "name": "Sceptile",
    "slug": "sceptile",
    "hoennNumber": 3,
    "nationalNumber": 254
  },
  {
    "name": "Torchic",
    "slug": "torchic",
    "hoennNumber": 4,
    "nationalNumber": 255
  },
  {
    "name": "Combusken",
    "slug": "combusken",
    "hoennNumber": 5,
    "nationalNumber": 256
  },
  {
    "name": "Blaziken",
    "slug": "blaziken",
    "hoennNumber": 6,
    "nationalNumber": 257
  },
  {
    "name": "Mudkip",
    "slug": "mudkip",
    "hoennNumber": 7,
    "nationalNumber": 258
  },
  {
    "name": "Marshtomp",
    "slug": "marshtomp",
    "hoennNumber": 8,
    "nationalNumber": 259
  },
  {
    "name": "Swampert",
    "slug": "swampert",
    "hoennNumber": 9,
    "nationalNumber": 260
  },
  {
    "name": "Poochyena",
    "slug": "poochyena",
    "hoennNumber": 10,
    "nationalNumber": 261
  },
  {
    "name": "Mightyena",
    "slug": "mightyena",
    "hoennNumber": 11,
    "nationalNumber": 262
  },
  {
    "name": "Zigzagoon",
    "slug": "zigzagoon",
    "hoennNumber": 12,
    "nationalNumber": 263
  },
  {
    "name": "Linoone",
    "slug": "linoone",
    "hoennNumber": 13,
    "nationalNumber": 264
  },
  {
    "name": "Wurmple",
    "slug": "wurmple",
    "hoennNumber": 14,
    "nationalNumber": 265
  },
  {
    "name": "Silcoon",
    "slug": "silcoon",
    "hoennNumber": 15,
    "nationalNumber": 266
  },
  {
    "name": "Beautifly",
    "slug": "beautifly",
    "hoennNumber": 16,
    "nationalNumber": 267
  },
  {
    "name": "Cascoon",
    "slug": "cascoon",
    "hoennNumber": 17,
    "nationalNumber": 268
  },
  {
    "name": "Dustox",
    "slug": "dustox",
    "hoennNumber": 18,
    "nationalNumber": 269
  },
  {
    "name": "Lotad",
    "slug": "lotad",
    "hoennNumber": 19,
    "nationalNumber": 270
  },
  {
    "name": "Lombre",
    "slug": "lombre",
    "hoennNumber": 20,
    "nationalNumber": 271
  },
  {
    "name": "Ludicolo",
    "slug": "ludicolo",
    "hoennNumber": 21,
    "nationalNumber": 272
  },
  {
    "name": "Seedot",
    "slug": "seedot",
    "hoennNumber": 22,
    "nationalNumber": 273
  },
  {
    "name": "Nuzleaf",
    "slug": "nuzleaf",
    "hoennNumber": 23,
    "nationalNumber": 274
  },
  {
    "name": "Shiftry",
    "slug": "shiftry",
    "hoennNumber": 24,
    "nationalNumber": 275
  },
  {
    "name": "Taillow",
    "slug": "taillow",
    "hoennNumber": 25,
    "nationalNumber": 276
  },
  {
    "name": "Swellow",
    "slug": "swellow",
    "hoennNumber": 26,
    "nationalNumber": 277
  },
  {
    "name": "Wingull",
    "slug": "wingull",
    "hoennNumber": 27,
    "nationalNumber": 278
  },
  {
    "name": "Pelipper",
    "slug": "pelipper",
    "hoennNumber": 28,
    "nationalNumber": 279
  },
  {
    "name": "Ralts",
    "slug": "ralts",
    "hoennNumber": 29,
    "nationalNumber": 280
  },
  {
    "name": "Kirlia",
    "slug": "kirlia",
    "hoennNumber": 30,
    "nationalNumber": 281
  },
  {
    "name": "Gardevoir",
    "slug": "gardevoir",
    "hoennNumber": 31,
    "nationalNumber": 282
  },
  {
    "name": "Surskit",
    "slug": "surskit",
    "hoennNumber": 32,
    "nationalNumber": 283
  },
  {
    "name": "Masquerain",
    "slug": "masquerain",
    "hoennNumber": 33,
    "nationalNumber": 284
  },
  {
    "name": "Shroomish",
    "slug": "shroomish",
    "hoennNumber": 34,
    "nationalNumber": 285
  },
  {
    "name": "Breloom",
    "slug": "breloom",
    "hoennNumber": 35,
    "nationalNumber": 286
  },
  {
    "name": "Slakoth",
    "slug": "slakoth",
    "hoennNumber": 36,
    "nationalNumber": 287
  },
  {
    "name": "Vigoroth",
    "slug": "vigoroth",
    "hoennNumber": 37,
    "nationalNumber": 288
  },
  {
    "name": "Slaking",
    "slug": "slaking",
    "hoennNumber": 38,
    "nationalNumber": 289
  },
  {
    "name": "Nincada",
    "slug": "nincada",
    "hoennNumber": 42,
    "nationalNumber": 290
  },
  {
    "name": "Ninjask",
    "slug": "ninjask",
    "hoennNumber": 43,
    "nationalNumber": 291
  },
  {
    "name": "Shedinja",
    "slug": "shedinja",
    "hoennNumber": 44,
    "nationalNumber": 292
  },
  {
    "name": "Whismur",
    "slug": "whismur",
    "hoennNumber": 45,
    "nationalNumber": 293
  },
  {
    "name": "Loudred",
    "slug": "loudred",
    "hoennNumber": 46,
    "nationalNumber": 294
  },
  {
    "name": "Exploud",
    "slug": "exploud",
    "hoennNumber": 47,
    "nationalNumber": 295
  },
  {
    "name": "Makuhita",
    "slug": "makuhita",
    "hoennNumber": 48,
    "nationalNumber": 296
  },
  {
    "name": "Hariyama",
    "slug": "hariyama",
    "hoennNumber": 49,
    "nationalNumber": 297
  },
  {
    "name": "Azurill",
    "slug": "azurill",
    "hoennNumber": 54,
    "nationalNumber": 298
  },
  {
    "name": "Nosepass",
    "slug": "nosepass",
    "hoennNumber": 60,
    "nationalNumber": 299
  },
  {
    "name": "Skitty",
    "slug": "skitty",
    "hoennNumber": 61,
    "nationalNumber": 300
  },
  {
    "name": "Delcatty",
    "slug": "delcatty",
    "hoennNumber": 62,
    "nationalNumber": 301
  },
  {
    "name": "Sableye",
    "slug": "sableye",
    "hoennNumber": 68,
    "nationalNumber": 302
  },
  {
    "name": "Mawile",
    "slug": "mawile",
    "hoennNumber": 69,
    "nationalNumber": 303
  },
  {
    "name": "Aron",
    "slug": "aron",
    "hoennNumber": 70,
    "nationalNumber": 304
  },
  {
    "name": "Lairon",
    "slug": "lairon",
    "hoennNumber": 71,
    "nationalNumber": 305
  },
  {
    "name": "Aggron",
    "slug": "aggron",
    "hoennNumber": 72,
    "nationalNumber": 306
  },
  {
    "name": "Meditite",
    "slug": "meditite",
    "hoennNumber": 76,
    "nationalNumber": 307
  },
  {
    "name": "Medicham",
    "slug": "medicham",
    "hoennNumber": 77,
    "nationalNumber": 308
  },
  {
    "name": "Electrike",
    "slug": "electrike",
    "hoennNumber": 78,
    "nationalNumber": 309
  },
  {
    "name": "Manectric",
    "slug": "manectric",
    "hoennNumber": 79,
    "nationalNumber": 310
  },
  {
    "name": "Plusle",
    "slug": "plusle",
    "hoennNumber": 80,
    "nationalNumber": 311
  },
  {
    "name": "Minun",
    "slug": "minun",
    "hoennNumber": 81,
    "nationalNumber": 312
  },
  {
    "name": "Volbeat",
    "slug": "volbeat",
    "hoennNumber": 86,
    "nationalNumber": 313
  },
  {
    "name": "Illumise",
    "slug": "illumise",
    "hoennNumber": 87,
    "nationalNumber": 314
  },
  {
    "name": "Roselia",
    "slug": "roselia",
    "hoennNumber": 94,
    "nationalNumber": 315
  },
  {
    "name": "Gulpin",
    "slug": "gulpin",
    "hoennNumber": 95,
    "nationalNumber": 316
  },
  {
    "name": "Swalot",
    "slug": "swalot",
    "hoennNumber": 96,
    "nationalNumber": 317
  },
  {
    "name": "Carvanha",
    "slug": "carvanha",
    "hoennNumber": 97,
    "nationalNumber": 318
  },
  {
    "name": "Sharpedo",
    "slug": "sharpedo",
    "hoennNumber": 98,
    "nationalNumber": 319
  },
  {
    "name": "Wailmer",
    "slug": "wailmer",
    "hoennNumber": 99,
    "nationalNumber": 320
  },
  {
    "name": "Wailord",
    "slug": "wailord",
    "hoennNumber": 100,
    "nationalNumber": 321
  },
  {
    "name": "Numel",
    "slug": "numel",
    "hoennNumber": 101,
    "nationalNumber": 322
  },
  {
    "name": "Camerupt",
    "slug": "camerupt",
    "hoennNumber": 102,
    "nationalNumber": 323
  },
  {
    "name": "Torkoal",
    "slug": "torkoal",
    "hoennNumber": 105,
    "nationalNumber": 324
  },
  {
    "name": "Spoink",
    "slug": "spoink",
    "hoennNumber": 110,
    "nationalNumber": 325
  },
  {
    "name": "Grumpig",
    "slug": "grumpig",
    "hoennNumber": 111,
    "nationalNumber": 326
  },
  {
    "name": "Spinda",
    "slug": "spinda",
    "hoennNumber": 114,
    "nationalNumber": 327
  },
  {
    "name": "Trapinch",
    "slug": "trapinch",
    "hoennNumber": 116,
    "nationalNumber": 328
  },
  {
    "name": "Vibrava",
    "slug": "vibrava",
    "hoennNumber": 117,
    "nationalNumber": 329
  },
  {
    "name": "Flygon",
    "slug": "flygon",
    "hoennNumber": 118,
    "nationalNumber": 330
  },
  {
    "name": "Cacnea",
    "slug": "cacnea",
    "hoennNumber": 119,
    "nationalNumber": 331
  },
  {
    "name": "Cacturne",
    "slug": "cacturne",
    "hoennNumber": 120,
    "nationalNumber": 332
  },
  {
    "name": "Swablu",
    "slug": "swablu",
    "hoennNumber": 121,
    "nationalNumber": 333
  },
  {
    "name": "Altaria",
    "slug": "altaria",
    "hoennNumber": 122,
    "nationalNumber": 334
  },
  {
    "name": "Zangoose",
    "slug": "zangoose",
    "hoennNumber": 123,
    "nationalNumber": 335
  },
  {
    "name": "Seviper",
    "slug": "seviper",
    "hoennNumber": 124,
    "nationalNumber": 336
  },
  {
    "name": "Lunatone",
    "slug": "lunatone",
    "hoennNumber": 125,
    "nationalNumber": 337
  },
  {
    "name": "Solrock",
    "slug": "solrock",
    "hoennNumber": 126,
    "nationalNumber": 338
  },
  {
    "name": "Barboach",
    "slug": "barboach",
    "hoennNumber": 127,
    "nationalNumber": 339
  },
  {
    "name": "Whiscash",
    "slug": "whiscash",
    "hoennNumber": 128,
    "nationalNumber": 340
  },
  {
    "name": "Corphish",
    "slug": "corphish",
    "hoennNumber": 129,
    "nationalNumber": 341
  },
  {
    "name": "Crawdaunt",
    "slug": "crawdaunt",
    "hoennNumber": 130,
    "nationalNumber": 342
  },
  {
    "name": "Baltoy",
    "slug": "baltoy",
    "hoennNumber": 131,
    "nationalNumber": 343
  },
  {
    "name": "Claydol",
    "slug": "claydol",
    "hoennNumber": 132,
    "nationalNumber": 344
  },
  {
    "name": "Lileep",
    "slug": "lileep",
    "hoennNumber": 133,
    "nationalNumber": 345
  },
  {
    "name": "Cradily",
    "slug": "cradily",
    "hoennNumber": 134,
    "nationalNumber": 346
  },
  {
    "name": "Anorith",
    "slug": "anorith",
    "hoennNumber": 135,
    "nationalNumber": 347
  },
  {
    "name": "Armaldo",
    "slug": "armaldo",
    "hoennNumber": 136,
    "nationalNumber": 348
  },
  {
    "name": "Feebas",
    "slug": "feebas",
    "hoennNumber": 140,
    "nationalNumber": 349
  },
  {
    "name": "Milotic",
    "slug": "milotic",
    "hoennNumber": 141,
    "nationalNumber": 350
  },
  {
    "name": "Castform",
    "slug": "castform",
    "hoennNumber": 142,
    "nationalNumber": 351
  },
  {
    "name": "Kecleon",
    "slug": "kecleon",
    "hoennNumber": 145,
    "nationalNumber": 352
  },
  {
    "name": "Shuppet",
    "slug": "shuppet",
    "hoennNumber": 146,
    "nationalNumber": 353
  },
  {
    "name": "Banette",
    "slug": "banette",
    "hoennNumber": 147,
    "nationalNumber": 354
  },
  {
    "name": "Duskull",
    "slug": "duskull",
    "hoennNumber": 148,
    "nationalNumber": 355
  },
  {
    "name": "Dusclops",
    "slug": "dusclops",
    "hoennNumber": 149,
    "nationalNumber": 356
  },
  {
    "name": "Tropius",
    "slug": "tropius",
    "hoennNumber": 150,
    "nationalNumber": 357
  },
  {
    "name": "Chimecho",
    "slug": "chimecho",
    "hoennNumber": 151,
    "nationalNumber": 358
  },
  {
    "name": "Absol",
    "slug": "absol",
    "hoennNumber": 152,
    "nationalNumber": 359
  },
  {
    "name": "Wynaut",
    "slug": "wynaut",
    "hoennNumber": 160,
    "nationalNumber": 360
  },
  {
    "name": "Snorunt",
    "slug": "snorunt",
    "hoennNumber": 171,
    "nationalNumber": 361
  },
  {
    "name": "Glalie",
    "slug": "glalie",
    "hoennNumber": 172,
    "nationalNumber": 362
  },
  {
    "name": "Spheal",
    "slug": "spheal",
    "hoennNumber": 173,
    "nationalNumber": 363
  },
  {
    "name": "Sealeo",
    "slug": "sealeo",
    "hoennNumber": 174,
    "nationalNumber": 364
  },
  {
    "name": "Walrein",
    "slug": "walrein",
    "hoennNumber": 175,
    "nationalNumber": 365
  },
  {
    "name": "Clamperl",
    "slug": "clamperl",
    "hoennNumber": 176,
    "nationalNumber": 366
  },
  {
    "name": "Huntail",
    "slug": "huntail",
    "hoennNumber": 177,
    "nationalNumber": 367
  },
  {
    "name": "Gorebyss",
    "slug": "gorebyss",
    "hoennNumber": 178,
    "nationalNumber": 368
  },
  {
    "name": "Relicanth",
    "slug": "relicanth",
    "hoennNumber": 179,
    "nationalNumber": 369
  },
  {
    "name": "Luvdisc",
    "slug": "luvdisc",
    "hoennNumber": 183,
    "nationalNumber": 370
  },
  {
    "name": "Bagon",
    "slug": "bagon",
    "hoennNumber": 187,
    "nationalNumber": 371
  },
  {
    "name": "Shelgon",
    "slug": "shelgon",
    "hoennNumber": 188,
    "nationalNumber": 372
  },
  {
    "name": "Salamence",
    "slug": "salamence",
    "hoennNumber": 189,
    "nationalNumber": 373
  },
  {
    "name": "Beldum",
    "slug": "beldum",
    "hoennNumber": 190,
    "nationalNumber": 374
  },
  {
    "name": "Metang",
    "slug": "metang",
    "hoennNumber": 191,
    "nationalNumber": 375
  },
  {
    "name": "Metagross",
    "slug": "metagross",
    "hoennNumber": 192,
    "nationalNumber": 376
  },
  {
    "name": "Regirock",
    "slug": "regirock",
    "hoennNumber": 193,
    "nationalNumber": 377
  },
  {
    "name": "Regice",
    "slug": "regice",
    "hoennNumber": 194,
    "nationalNumber": 378
  },
  {
    "name": "Registeel",
    "slug": "registeel",
    "hoennNumber": 195,
    "nationalNumber": 379
  },
  {
    "name": "Latias",
    "slug": "latias",
    "hoennNumber": 196,
    "nationalNumber": 380
  },
  {
    "name": "Latios",
    "slug": "latios",
    "hoennNumber": 197,
    "nationalNumber": 381
  },
  {
    "name": "Kyogre",
    "slug": "kyogre",
    "hoennNumber": 198,
    "nationalNumber": 382
  },
  {
    "name": "Groudon",
    "slug": "groudon",
    "hoennNumber": 199,
    "nationalNumber": 383
  },
  {
    "name": "Rayquaza",
    "slug": "rayquaza",
    "hoennNumber": 200,
    "nationalNumber": 384
  },
  {
    "name": "Jirachi",
    "slug": "jirachi",
    "hoennNumber": 201,
    "nationalNumber": 385
  },
  {
    "name": "Deoxys",
    "slug": "deoxys",
    "hoennNumber": 202,
    "nationalNumber": 386
  },
  {
    "name": "?????????? (Decamark)",
    "slug": "",
    "nationalNumber": 387,
    "isGlitch": true
  }
];

