/** Auto-generated by scripts/sync-gym-sprites.mjs — do not edit by hand. */
export interface GymBadgeSprite {
  spriteSheet: string;
  spriteWidth: number;
  spriteHeight: number;
  spriteFrame: number;
}

export const GYM_BADGE_SHEET = "sprites/gym/badges.png";
export const GYM_BADGE_WIDTH = 16;
export const GYM_BADGE_HEIGHT = 16;

/** mapPointId (e.g. gym-rustboro) → frame index on the badge sheet. */
export const GYM_BADGE_FRAME_BY_MAP_POINT: Record<string, number> = {
  "gym-rustboro": 0,
  "gym-dewford": 1,
  "gym-mauville": 2,
  "gym-lavaridge": 3,
  "gym-petalburg": 4,
  "gym-fortree": 5,
  "gym-mossdeep": 6,
  "gym-sootopolis": 7
};

export function getGymBadgeSprite(mapPointId: string): GymBadgeSprite | null {
  const frame = GYM_BADGE_FRAME_BY_MAP_POINT[mapPointId];
  if (frame == null) return null;
  return {
    spriteSheet: GYM_BADGE_SHEET,
    spriteWidth: GYM_BADGE_WIDTH,
    spriteHeight: GYM_BADGE_HEIGHT,
    spriteFrame: frame,
  };
}
