// AUTO-GENERATED by scripts/bake-hoenn-overworld-sprites.mjs — do not edit by hand.
/** Lossless tile-atlas overlays for HoennMap filter layers (pixel-perfect crops). */

export interface HoennBakeLayerTile {
  /** Placement on the overworld map, in source pixels. */
  mapX: number;
  mapY: number;
  mapW: number;
  mapH: number;
  /** Source rect inside the layer atlas image. */
  atlasX: number;
  atlasY: number;
  atlasW: number;
  atlasH: number;
}

export interface HoennBakeLayerAtlas {
  atlasWidth: number;
  atlasHeight: number;
  tiles: HoennBakeLayerTile[];
}

export const HOENN_MAP_BAKE_MAP_SIZE = { width: 12800, height: 6128 } as const;
export const HOENN_MAP_BAKE_SPRITE_SCALE = 2;
export const HOENN_MAP_BAKE_LAYER_ATLASES: Record<string, HoennBakeLayerAtlas> = {
  "trainer": {
    "atlasWidth": 2044,
    "atlasHeight": 2560,
    "tiles": [
      {
        "mapX": 936,
        "mapY": 422,
        "mapW": 28,
        "mapH": 40,
        "atlasX": 1915,
        "atlasY": 2425,
        "atlasW": 28,
        "atlasH": 40
      },
      {
        "mapX": 1032,
        "mapY": 102,
        "mapW": 80,
        "mapH": 264,
        "atlasX": 294,
        "atlasY": 1287,
        "atlasW": 80,
        "atlasH": 264
      },
      {
        "mapX": 1704,
        "mapY": 70,
        "mapW": 256,
        "mapH": 152,
        "atlasX": 1754,
        "atlasY": 1980,
        "atlasW": 256,
        "atlasH": 152
      },
      {
        "mapX": 2060,
        "mapY": 76,
        "mapW": 380,
        "mapH": 114,
        "atlasX": 487,
        "atlasY": 2302,
        "atlasW": 380,
        "atlasH": 114
      },
      {
        "mapX": 2586,
        "mapY": 18,
        "mapW": 486,
        "mapH": 492,
        "atlasX": 433,
        "atlasY": 0,
        "atlasW": 486,
        "atlasH": 492
      },
      {
        "mapX": 3072,
        "mapY": 150,
        "mapW": 328,
        "mapH": 358,
        "atlasX": 707,
        "atlasY": 922,
        "atlasW": 328,
        "atlasH": 358
      },
      {
        "mapX": 3704,
        "mapY": 438,
        "mapW": 32,
        "mapH": 40,
        "atlasX": 1752,
        "atlasY": 2425,
        "atlasW": 32,
        "atlasH": 40
      },
      {
        "mapX": 4924,
        "mapY": 82,
        "mapW": 88,
        "mapH": 172,
        "atlasX": 1362,
        "atlasY": 1785,
        "atlasW": 88,
        "atlasH": 172
      },
      {
        "mapX": 5834,
        "mapY": 70,
        "mapW": 252,
        "mapH": 442,
        "atlasX": 1111,
        "atlasY": 0,
        "atlasW": 252,
        "atlasH": 442
      },
      {
        "mapX": 6266,
        "mapY": 200,
        "mapW": 28,
        "mapH": 40,
        "atlasX": 1944,
        "atlasY": 2425,
        "atlasW": 28,
        "atlasH": 40
      },
      {
        "mapX": 72,
        "mapY": 758,
        "mapW": 256,
        "mapH": 170,
        "atlasX": 1451,
        "atlasY": 1785,
        "atlasW": 256,
        "atlasH": 170
      },
      {
        "mapX": 936,
        "mapY": 566,
        "mapW": 88,
        "mapH": 376,
        "atlasX": 1009,
        "atlasY": 513,
        "atlasW": 88,
        "atlasH": 376
      },
      {
        "mapX": 1024,
        "mapY": 710,
        "mapW": 118,
        "mapH": 264,
        "atlasX": 175,
        "atlasY": 1287,
        "atlasW": 118,
        "atlasH": 264
      },
      {
        "mapX": 2792,
        "mapY": 836,
        "mapW": 176,
        "mapH": 138,
        "atlasX": 1346,
        "atlasY": 2149,
        "atlasW": 176,
        "atlasH": 138
      },
      {
        "mapX": 3528,
        "mapY": 726,
        "mapW": 28,
        "mapH": 40,
        "atlasX": 1973,
        "atlasY": 2425,
        "atlasW": 28,
        "atlasH": 40
      },
      {
        "mapX": 3642,
        "mapY": 566,
        "mapW": 42,
        "mapH": 264,
        "atlasX": 375,
        "atlasY": 1287,
        "atlasW": 42,
        "atlasH": 264
      },
      {
        "mapX": 4602,
        "mapY": 982,
        "mapW": 6,
        "mapH": 38,
        "atlasX": 115,
        "atlasY": 2520,
        "atlasW": 6,
        "atlasH": 38
      },
      {
        "mapX": 4608,
        "mapY": 770,
        "mapW": 196,
        "mapH": 252,
        "atlasX": 418,
        "atlasY": 1287,
        "atlasW": 196,
        "atlasH": 252
      },
      {
        "mapX": 5896,
        "mapY": 512,
        "mapW": 190,
        "mapH": 462,
        "atlasX": 920,
        "atlasY": 0,
        "atlasW": 190,
        "atlasH": 462
      },
      {
        "mapX": 6184,
        "mapY": 566,
        "mapW": 174,
        "mapH": 264,
        "atlasX": 0,
        "atlasY": 1287,
        "atlasW": 174,
        "atlasH": 264
      },
      {
        "mapX": 234,
        "mapY": 1446,
        "mapW": 222,
        "mapH": 88,
        "atlasX": 249,
        "atlasY": 2425,
        "atlasW": 222,
        "atlasH": 88
      },
      {
        "mapX": 872,
        "mapY": 1046,
        "mapW": 30,
        "mapH": 42,
        "atlasX": 1578,
        "atlasY": 2425,
        "atlasW": 30,
        "atlasH": 42
      },
      {
        "mapX": 1048,
        "mapY": 1156,
        "mapW": 94,
        "mapH": 44,
        "atlasX": 917,
        "atlasY": 2425,
        "atlasW": 94,
        "atlasH": 44
      },
      {
        "mapX": 2904,
        "mapY": 1030,
        "mapW": 142,
        "mapH": 88,
        "atlasX": 472,
        "atlasY": 2425,
        "atlasW": 142,
        "atlasH": 88
      },
      {
        "mapX": 3352,
        "mapY": 1110,
        "mapW": 224,
        "mapH": 216,
        "atlasX": 760,
        "atlasY": 1552,
        "atlasW": 224,
        "atlasH": 216
      },
      {
        "mapX": 3624,
        "mapY": 1030,
        "mapW": 188,
        "mapH": 216,
        "atlasX": 985,
        "atlasY": 1552,
        "atlasW": 188,
        "atlasH": 216
      },
      {
        "mapX": 4586,
        "mapY": 1066,
        "mapW": 22,
        "mapH": 134,
        "atlasX": 1523,
        "atlasY": 2149,
        "atlasW": 22,
        "atlasH": 134
      },
      {
        "mapX": 4608,
        "mapY": 1062,
        "mapW": 456,
        "mapH": 280,
        "atlasX": 1364,
        "atlasY": 922,
        "atlasW": 456,
        "atlasH": 280
      },
      {
        "mapX": 5916,
        "mapY": 1138,
        "mapW": 170,
        "mapH": 156,
        "atlasX": 1216,
        "atlasY": 1980,
        "atlasW": 170,
        "atlasH": 156
      },
      {
        "mapX": 6568,
        "mapY": 1350,
        "mapW": 32,
        "mapH": 120,
        "atlasX": 454,
        "atlasY": 2302,
        "atlasW": 32,
        "atlasH": 120
      },
      {
        "mapX": 6748,
        "mapY": 1334,
        "mapW": 316,
        "mapH": 104,
        "atlasX": 1251,
        "atlasY": 2302,
        "atlasW": 316,
        "atlasH": 104
      },
      {
        "mapX": 7276,
        "mapY": 1334,
        "mapW": 300,
        "mapH": 168,
        "atlasX": 1708,
        "atlasY": 1785,
        "atlasW": 300,
        "atlasH": 168
      },
      {
        "mapX": 9064,
        "mapY": 1306,
        "mapW": 32,
        "mapH": 126,
        "atlasX": 1609,
        "atlasY": 2149,
        "atlasW": 32,
        "atlasH": 126
      },
      {
        "mapX": 9498,
        "mapY": 1342,
        "mapW": 28,
        "mapH": 28,
        "atlasX": 515,
        "atlasY": 2520,
        "atlasW": 28,
        "atlasH": 28
      },
      {
        "mapX": 10346,
        "mapY": 1238,
        "mapW": 398,
        "mapH": 228,
        "atlasX": 361,
        "atlasY": 1552,
        "atlasW": 398,
        "atlasH": 228
      },
      {
        "mapX": 10840,
        "mapY": 1082,
        "mapW": 192,
        "mapH": 272,
        "atlasX": 1821,
        "atlasY": 922,
        "atlasW": 192,
        "atlasH": 272
      },
      {
        "mapX": 378,
        "mapY": 1638,
        "mapW": 94,
        "mapH": 42,
        "atlasX": 1347,
        "atlasY": 2425,
        "atlasW": 94,
        "atlasH": 42
      },
      {
        "mapX": 828,
        "mapY": 2040,
        "mapW": 24,
        "mapH": 8,
        "atlasX": 1047,
        "atlasY": 2520,
        "atlasW": 24,
        "atlasH": 8
      },
      {
        "mapX": 1048,
        "mapY": 2008,
        "mapW": 142,
        "mapH": 40,
        "atlasX": 1609,
        "atlasY": 2425,
        "atlasW": 142,
        "atlasH": 40
      },
      {
        "mapX": 3450,
        "mapY": 1880,
        "mapW": 78,
        "mapH": 70,
        "atlasX": 615,
        "atlasY": 2425,
        "atlasW": 78,
        "atlasH": 70
      },
      {
        "mapX": 4554,
        "mapY": 1974,
        "mapW": 28,
        "mapH": 40,
        "atlasX": 2002,
        "atlasY": 2425,
        "atlasW": 28,
        "atlasH": 40
      },
      {
        "mapX": 4664,
        "mapY": 1640,
        "mapW": 384,
        "mapH": 408,
        "atlasX": 0,
        "atlasY": 513,
        "atlasW": 384,
        "atlasH": 408
      },
      {
        "mapX": 9226,
        "mapY": 1646,
        "mapW": 46,
        "mapH": 30,
        "atlasX": 275,
        "atlasY": 2520,
        "atlasW": 46,
        "atlasH": 30
      },
      {
        "mapX": 9736,
        "mapY": 1662,
        "mapW": 174,
        "mapH": 236,
        "atlasX": 948,
        "atlasY": 1287,
        "atlasW": 174,
        "atlasH": 236
      },
      {
        "mapX": 826,
        "mapY": 2048,
        "mapW": 188,
        "mapH": 190,
        "atlasX": 468,
        "atlasY": 1785,
        "atlasW": 188,
        "atlasH": 190
      },
      {
        "mapX": 1050,
        "mapY": 2048,
        "mapW": 284,
        "mapH": 190,
        "atlasX": 183,
        "atlasY": 1785,
        "atlasW": 284,
        "atlasH": 190
      },
      {
        "mapX": 2360,
        "mapY": 2278,
        "mapW": 174,
        "mapH": 168,
        "atlasX": 0,
        "atlasY": 1980,
        "atlasW": 174,
        "atlasH": 168
      },
      {
        "mapX": 2572,
        "mapY": 2278,
        "mapW": 380,
        "mapH": 232,
        "atlasX": 1617,
        "atlasY": 1287,
        "atlasW": 380,
        "atlasH": 232
      },
      {
        "mapX": 3512,
        "mapY": 2088,
        "mapW": 32,
        "mapH": 40,
        "atlasX": 1785,
        "atlasY": 2425,
        "atlasW": 32,
        "atlasH": 40
      },
      {
        "mapX": 3608,
        "mapY": 2086,
        "mapW": 480,
        "mapH": 392,
        "atlasX": 528,
        "atlasY": 513,
        "atlasW": 480,
        "atlasH": 392
      },
      {
        "mapX": 4106,
        "mapY": 2390,
        "mapW": 382,
        "mapH": 104,
        "atlasX": 868,
        "atlasY": 2302,
        "atlasW": 382,
        "atlasH": 104
      },
      {
        "mapX": 4730,
        "mapY": 2048,
        "mapW": 156,
        "mapH": 366,
        "atlasX": 1882,
        "atlasY": 513,
        "atlasW": 156,
        "atlasH": 366
      },
      {
        "mapX": 5336,
        "mapY": 2358,
        "mapW": 96,
        "mapH": 152,
        "atlasX": 0,
        "atlasY": 2149,
        "atlasW": 96,
        "atlasH": 152
      },
      {
        "mapX": 5708,
        "mapY": 2326,
        "mapW": 360,
        "mapH": 232,
        "atlasX": 0,
        "atlasY": 1552,
        "atlasW": 360,
        "atlasH": 232
      },
      {
        "mapX": 6170,
        "mapY": 2406,
        "mapW": 366,
        "mapH": 152,
        "atlasX": 1387,
        "atlasY": 1980,
        "atlasW": 366,
        "atlasH": 152
      },
      {
        "mapX": 7320,
        "mapY": 2408,
        "mapW": 32,
        "mapH": 102,
        "atlasX": 1903,
        "atlasY": 2302,
        "atlasW": 32,
        "atlasH": 102
      },
      {
        "mapX": 9848,
        "mapY": 2122,
        "mapW": 238,
        "mapH": 210,
        "atlasX": 1679,
        "atlasY": 1552,
        "atlasW": 238,
        "atlasH": 210
      },
      {
        "mapX": 10906,
        "mapY": 2438,
        "mapW": 358,
        "mapH": 122,
        "atlasX": 0,
        "atlasY": 2302,
        "atlasW": 358,
        "atlasH": 122
      },
      {
        "mapX": 11264,
        "mapY": 2520,
        "mapW": 22,
        "mapH": 40,
        "atlasX": 54,
        "atlasY": 2520,
        "atlasW": 22,
        "atlasH": 40
      },
      {
        "mapX": 456,
        "mapY": 3014,
        "mapW": 32,
        "mapH": 40,
        "atlasX": 1818,
        "atlasY": 2425,
        "atlasW": 32,
        "atlasH": 40
      },
      {
        "mapX": 3352,
        "mapY": 2838,
        "mapW": 174,
        "mapH": 234,
        "atlasX": 1442,
        "atlasY": 1287,
        "atlasW": 174,
        "atlasH": 234
      },
      {
        "mapX": 3664,
        "mapY": 2774,
        "mapW": 88,
        "mapH": 298,
        "atlasX": 1275,
        "atlasY": 922,
        "atlasW": 88,
        "atlasH": 298
      },
      {
        "mapX": 9096,
        "mapY": 2990,
        "mapW": 32,
        "mapH": 26,
        "atlasX": 689,
        "atlasY": 2520,
        "atlasW": 32,
        "atlasH": 26
      },
      {
        "mapX": 9850,
        "mapY": 2574,
        "mapW": 142,
        "mapH": 364,
        "atlasX": 0,
        "atlasY": 922,
        "atlasW": 142,
        "atlasH": 364
      },
      {
        "mapX": 10424,
        "mapY": 2582,
        "mapW": 76,
        "mapH": 42,
        "atlasX": 1442,
        "atlasY": 2425,
        "atlasW": 76,
        "atlasH": 42
      },
      {
        "mapX": 10904,
        "mapY": 2560,
        "mapW": 78,
        "mapH": 362,
        "atlasX": 143,
        "atlasY": 922,
        "atlasW": 78,
        "atlasH": 362
      },
      {
        "mapX": 330,
        "mapY": 3132,
        "mapW": 182,
        "mapH": 194,
        "atlasX": 0,
        "atlasY": 1785,
        "atlasW": 182,
        "atlasH": 194
      },
      {
        "mapX": 512,
        "mapY": 3274,
        "mapW": 8,
        "mapH": 26,
        "atlasX": 755,
        "atlasY": 2520,
        "atlasW": 8,
        "atlasH": 26
      },
      {
        "mapX": 2988,
        "mapY": 3574,
        "mapW": 24,
        "mapH": 10,
        "atlasX": 1022,
        "atlasY": 2520,
        "atlasW": 24,
        "atlasH": 10
      },
      {
        "mapX": 3240,
        "mapY": 3158,
        "mapW": 238,
        "mapH": 298,
        "atlasX": 1036,
        "atlasY": 922,
        "atlasW": 238,
        "atlasH": 298
      },
      {
        "mapX": 3738,
        "mapY": 3174,
        "mapW": 58,
        "mapH": 42,
        "atlasX": 1519,
        "atlasY": 2425,
        "atlasW": 58,
        "atlasH": 42
      },
      {
        "mapX": 9064,
        "mapY": 3274,
        "mapW": 152,
        "mapH": 34,
        "atlasX": 122,
        "atlasY": 2520,
        "atlasW": 152,
        "atlasH": 34
      },
      {
        "mapX": 9216,
        "mapY": 3282,
        "mapW": 6,
        "mapH": 20,
        "atlasX": 930,
        "atlasY": 2520,
        "atlasW": 6,
        "atlasH": 20
      },
      {
        "mapX": 9770,
        "mapY": 3262,
        "mapW": 28,
        "mapH": 28,
        "atlasX": 544,
        "atlasY": 2520,
        "atlasW": 28,
        "atlasH": 28
      },
      {
        "mapX": 10520,
        "mapY": 3310,
        "mapW": 32,
        "mapH": 26,
        "atlasX": 722,
        "atlasY": 2520,
        "atlasW": 32,
        "atlasH": 26
      },
      {
        "mapX": 11240,
        "mapY": 3222,
        "mapW": 24,
        "mapH": 40,
        "atlasX": 29,
        "atlasY": 2520,
        "atlasW": 24,
        "atlasH": 40
      },
      {
        "mapX": 11264,
        "mapY": 3222,
        "mapW": 8,
        "mapH": 38,
        "atlasX": 106,
        "atlasY": 2520,
        "atlasW": 8,
        "atlasH": 38
      },
      {
        "mapX": 168,
        "mapY": 3590,
        "mapW": 142,
        "mapH": 408,
        "atlasX": 385,
        "atlasY": 513,
        "atlasW": 142,
        "atlasH": 408
      },
      {
        "mapX": 1240,
        "mapY": 3912,
        "mapW": 296,
        "mapH": 184,
        "atlasX": 810,
        "atlasY": 1785,
        "atlasW": 296,
        "atlasH": 184
      },
      {
        "mapX": 1536,
        "mapY": 4072,
        "mapW": 134,
        "mapH": 24,
        "atlasX": 764,
        "atlasY": 2520,
        "atlasW": 134,
        "atlasH": 24
      },
      {
        "mapX": 2488,
        "mapY": 3598,
        "mapW": 32,
        "mapH": 140,
        "atlasX": 1280,
        "atlasY": 2149,
        "atlasW": 32,
        "atlasH": 140
      },
      {
        "mapX": 2712,
        "mapY": 3584,
        "mapW": 360,
        "mapH": 160,
        "atlasX": 456,
        "atlasY": 1980,
        "atlasW": 360,
        "atlasH": 160
      },
      {
        "mapX": 3072,
        "mapY": 3676,
        "mapW": 486,
        "mapH": 148,
        "atlasX": 97,
        "atlasY": 2149,
        "atlasW": 486,
        "atlasH": 148
      },
      {
        "mapX": 3722,
        "mapY": 3640,
        "mapW": 28,
        "mapH": 38,
        "atlasX": 77,
        "atlasY": 2520,
        "atlasW": 28,
        "atlasH": 38
      },
      {
        "mapX": 10620,
        "mapY": 3622,
        "mapW": 28,
        "mapH": 40,
        "atlasX": 0,
        "atlasY": 2520,
        "atlasW": 28,
        "atlasH": 40
      },
      {
        "mapX": 10794,
        "mapY": 3640,
        "mapW": 470,
        "mapH": 418,
        "atlasX": 1364,
        "atlasY": 0,
        "atlasW": 470,
        "atlasH": 418
      },
      {
        "mapX": 11264,
        "mapY": 3886,
        "mapW": 248,
        "mapH": 94,
        "atlasX": 0,
        "atlasY": 2425,
        "atlasW": 248,
        "atlasH": 94
      },
      {
        "mapX": 11848,
        "mapY": 3854,
        "mapW": 32,
        "mapH": 140,
        "atlasX": 1313,
        "atlasY": 2149,
        "atlasW": 32,
        "atlasH": 140
      },
      {
        "mapX": 296,
        "mapY": 4318,
        "mapW": 32,
        "mapH": 28,
        "atlasX": 482,
        "atlasY": 2520,
        "atlasW": 32,
        "atlasH": 28
      },
      {
        "mapX": 1512,
        "mapY": 4096,
        "mapW": 24,
        "mapH": 30,
        "atlasX": 322,
        "atlasY": 2520,
        "atlasW": 24,
        "atlasH": 30
      },
      {
        "mapX": 1536,
        "mapY": 4096,
        "mapW": 134,
        "mapH": 28,
        "atlasX": 347,
        "atlasY": 2520,
        "atlasW": 134,
        "atlasH": 28
      },
      {
        "mapX": 4218,
        "mapY": 4502,
        "mapW": 334,
        "mapH": 42,
        "atlasX": 1012,
        "atlasY": 2425,
        "atlasW": 334,
        "atlasH": 42
      },
      {
        "mapX": 4616,
        "mapY": 4254,
        "mapW": 254,
        "mapH": 176,
        "atlasX": 1107,
        "atlasY": 1785,
        "atlasW": 254,
        "atlasH": 176
      },
      {
        "mapX": 5226,
        "mapY": 4190,
        "mapW": 126,
        "mapH": 210,
        "atlasX": 1918,
        "atlasY": 1552,
        "atlasW": 126,
        "atlasH": 210
      },
      {
        "mapX": 5706,
        "mapY": 4314,
        "mapW": 334,
        "mapH": 102,
        "atlasX": 1568,
        "atlasY": 2302,
        "atlasW": 334,
        "atlasH": 102
      },
      {
        "mapX": 6200,
        "mapY": 4238,
        "mapW": 384,
        "mapH": 370,
        "atlasX": 1497,
        "atlasY": 513,
        "atlasW": 384,
        "atlasH": 370
      },
      {
        "mapX": 6730,
        "mapY": 4350,
        "mapW": 332,
        "mapH": 240,
        "atlasX": 615,
        "atlasY": 1287,
        "atlasW": 332,
        "atlasH": 240
      },
      {
        "mapX": 7176,
        "mapY": 4584,
        "mapW": 30,
        "mapH": 24,
        "atlasX": 899,
        "atlasY": 2520,
        "atlasW": 30,
        "atlasH": 24
      },
      {
        "mapX": 8122,
        "mapY": 4398,
        "mapW": 62,
        "mapH": 126,
        "atlasX": 1546,
        "atlasY": 2149,
        "atlasW": 62,
        "atlasH": 126
      },
      {
        "mapX": 8282,
        "mapY": 4446,
        "mapW": 238,
        "mapH": 124,
        "atlasX": 1642,
        "atlasY": 2149,
        "atlasW": 238,
        "atlasH": 124
      },
      {
        "mapX": 8824,
        "mapY": 4462,
        "mapW": 272,
        "mapH": 140,
        "atlasX": 1007,
        "atlasY": 2149,
        "atlasW": 272,
        "atlasH": 140
      },
      {
        "mapX": 10074,
        "mapY": 4478,
        "mapW": 28,
        "mapH": 28,
        "atlasX": 573,
        "atlasY": 2520,
        "atlasW": 28,
        "atlasH": 28
      },
      {
        "mapX": 10392,
        "mapY": 4366,
        "mapW": 318,
        "mapH": 234,
        "atlasX": 1123,
        "atlasY": 1287,
        "atlasW": 318,
        "atlasH": 234
      },
      {
        "mapX": 10794,
        "mapY": 4286,
        "mapW": 28,
        "mapH": 28,
        "atlasX": 602,
        "atlasY": 2520,
        "atlasW": 28,
        "atlasH": 28
      },
      {
        "mapX": 56,
        "mapY": 4750,
        "mapW": 398,
        "mapH": 370,
        "atlasX": 1098,
        "atlasY": 513,
        "atlasW": 398,
        "atlasH": 370
      },
      {
        "mapX": 4216,
        "mapY": 4614,
        "mapW": 32,
        "mapH": 40,
        "atlasX": 1851,
        "atlasY": 2425,
        "atlasW": 32,
        "atlasH": 40
      },
      {
        "mapX": 6202,
        "mapY": 4608,
        "mapW": 28,
        "mapH": 10,
        "atlasX": 964,
        "atlasY": 2520,
        "atlasW": 28,
        "atlasH": 10
      },
      {
        "mapX": 6730,
        "mapY": 4618,
        "mapW": 222,
        "mapH": 52,
        "atlasX": 694,
        "atlasY": 2425,
        "atlasW": 222,
        "atlasH": 52
      },
      {
        "mapX": 7180,
        "mapY": 4608,
        "mapW": 26,
        "mapH": 16,
        "atlasX": 937,
        "atlasY": 2520,
        "atlasW": 26,
        "atlasH": 16
      },
      {
        "mapX": 8650,
        "mapY": 4654,
        "mapW": 28,
        "mapH": 28,
        "atlasX": 631,
        "atlasY": 2520,
        "atlasW": 28,
        "atlasH": 28
      },
      {
        "mapX": 9066,
        "mapY": 4622,
        "mapW": 28,
        "mapH": 28,
        "atlasX": 660,
        "atlasY": 2520,
        "atlasW": 28,
        "atlasH": 28
      },
      {
        "mapX": 56,
        "mapY": 5120,
        "mapW": 432,
        "mapH": 512,
        "atlasX": 0,
        "atlasY": 0,
        "atlasW": 432,
        "atlasH": 512
      },
      {
        "mapX": 3432,
        "mapY": 5218,
        "mapW": 152,
        "mapH": 188,
        "atlasX": 657,
        "atlasY": 1785,
        "atlasW": 152,
        "atlasH": 188
      },
      {
        "mapX": 3584,
        "mapY": 5218,
        "mapW": 102,
        "mapH": 414,
        "atlasX": 1835,
        "atlasY": 0,
        "atlasW": 102,
        "atlasH": 414
      },
      {
        "mapX": 458,
        "mapY": 5632,
        "mapW": 28,
        "mapH": 10,
        "atlasX": 993,
        "atlasY": 2520,
        "atlasW": 28,
        "atlasH": 10
      },
      {
        "mapX": 808,
        "mapY": 5672,
        "mapW": 30,
        "mapH": 40,
        "atlasX": 1884,
        "atlasY": 2425,
        "atlasW": 30,
        "atlasH": 40
      },
      {
        "mapX": 1032,
        "mapY": 5670,
        "mapW": 504,
        "mapH": 212,
        "atlasX": 1174,
        "atlasY": 1552,
        "atlasW": 504,
        "atlasH": 212
      },
      {
        "mapX": 1536,
        "mapY": 5806,
        "mapW": 422,
        "mapH": 140,
        "atlasX": 584,
        "atlasY": 2149,
        "atlasW": 422,
        "atlasH": 140
      },
      {
        "mapX": 2072,
        "mapY": 5822,
        "mapW": 398,
        "mapH": 156,
        "atlasX": 817,
        "atlasY": 1980,
        "atlasW": 398,
        "atlasH": 156
      },
      {
        "mapX": 2792,
        "mapY": 5814,
        "mapW": 280,
        "mapH": 164,
        "atlasX": 175,
        "atlasY": 1980,
        "atlasW": 280,
        "atlasH": 164
      },
      {
        "mapX": 3072,
        "mapY": 5674,
        "mapW": 484,
        "mapH": 358,
        "atlasX": 222,
        "atlasY": 922,
        "atlasW": 484,
        "atlasH": 358
      },
      {
        "mapX": 3592,
        "mapY": 5632,
        "mapW": 94,
        "mapH": 120,
        "atlasX": 359,
        "atlasY": 2302,
        "atlasW": 94,
        "atlasH": 120
      }
    ]
  },
  "npc": {
    "atlasWidth": 2018,
    "atlasHeight": 1523,
    "tiles": [
      {
        "mapX": 938,
        "mapY": 182,
        "mapW": 28,
        "mapH": 58,
        "atlasX": 240,
        "atlasY": 1451,
        "atlasW": 28,
        "atlasH": 58
      },
      {
        "mapX": 1402,
        "mapY": 120,
        "mapW": 78,
        "mapH": 134,
        "atlasX": 634,
        "atlasY": 1314,
        "atlasW": 78,
        "atlasH": 134
      },
      {
        "mapX": 2170,
        "mapY": 72,
        "mapW": 302,
        "mapH": 102,
        "atlasX": 1605,
        "atlasY": 1314,
        "atlasW": 302,
        "atlasH": 102
      },
      {
        "mapX": 2570,
        "mapY": 54,
        "mapW": 202,
        "mapH": 296,
        "atlasX": 1240,
        "atlasY": 471,
        "atlasW": 202,
        "atlasH": 296
      },
      {
        "mapX": 3402,
        "mapY": 104,
        "mapW": 182,
        "mapH": 230,
        "atlasX": 1360,
        "atlasY": 832,
        "atlasW": 182,
        "atlasH": 230
      },
      {
        "mapX": 3584,
        "mapY": 108,
        "mapW": 6,
        "mapH": 32,
        "atlasX": 1391,
        "atlasY": 1451,
        "atlasW": 6,
        "atlasH": 32
      },
      {
        "mapX": 4684,
        "mapY": 504,
        "mapW": 28,
        "mapH": 8,
        "atlasX": 1510,
        "atlasY": 1451,
        "atlasW": 28,
        "atlasH": 8
      },
      {
        "mapX": 5240,
        "mapY": 22,
        "mapW": 392,
        "mapH": 246,
        "atlasX": 385,
        "atlasY": 832,
        "atlasW": 392,
        "atlasH": 246
      },
      {
        "mapX": 5632,
        "mapY": 26,
        "mapW": 360,
        "mapH": 244,
        "atlasX": 778,
        "atlasY": 832,
        "atlasW": 360,
        "atlasH": 244
      },
      {
        "mapX": 1064,
        "mapY": 678,
        "mapW": 32,
        "mapH": 40,
        "atlasX": 806,
        "atlasY": 1451,
        "atlasW": 32,
        "atlasH": 40
      },
      {
        "mapX": 2312,
        "mapY": 600,
        "mapW": 248,
        "mapH": 390,
        "atlasX": 1283,
        "atlasY": 0,
        "atlasW": 248,
        "atlasH": 390
      },
      {
        "mapX": 2560,
        "mapY": 598,
        "mapW": 456,
        "mapH": 216,
        "atlasX": 0,
        "atlasY": 1097,
        "atlasW": 456,
        "atlasH": 216
      },
      {
        "mapX": 3416,
        "mapY": 868,
        "mapW": 32,
        "mapH": 42,
        "atlasX": 653,
        "atlasY": 1451,
        "atlasW": 32,
        "atlasH": 42
      },
      {
        "mapX": 4682,
        "mapY": 512,
        "mapW": 30,
        "mapH": 48,
        "atlasX": 622,
        "atlasY": 1451,
        "atlasW": 30,
        "atlasH": 48
      },
      {
        "mapX": 2298,
        "mapY": 1050,
        "mapW": 122,
        "mapH": 132,
        "atlasX": 713,
        "atlasY": 1314,
        "atlasW": 122,
        "atlasH": 132
      },
      {
        "mapX": 2680,
        "mapY": 1092,
        "mapW": 32,
        "mapH": 42,
        "atlasX": 686,
        "atlasY": 1451,
        "atlasW": 32,
        "atlasH": 42
      },
      {
        "mapX": 3322,
        "mapY": 1430,
        "mapW": 28,
        "mapH": 40,
        "atlasX": 1035,
        "atlasY": 1451,
        "atlasW": 28,
        "atlasH": 40
      },
      {
        "mapX": 5034,
        "mapY": 1464,
        "mapW": 28,
        "mapH": 38,
        "atlasX": 1230,
        "atlasY": 1451,
        "atlasW": 28,
        "atlasH": 38
      },
      {
        "mapX": 5976,
        "mapY": 1446,
        "mapW": 32,
        "mapH": 40,
        "atlasX": 839,
        "atlasY": 1451,
        "atlasW": 32,
        "atlasH": 40
      },
      {
        "mapX": 6856,
        "mapY": 1480,
        "mapW": 32,
        "mapH": 40,
        "atlasX": 872,
        "atlasY": 1451,
        "atlasW": 32,
        "atlasH": 40
      },
      {
        "mapX": 7914,
        "mapY": 1238,
        "mapW": 278,
        "mapH": 266,
        "atlasX": 1660,
        "atlasY": 471,
        "atlasW": 278,
        "atlasH": 266
      },
      {
        "mapX": 8192,
        "mapY": 1204,
        "mapW": 424,
        "mapH": 332,
        "atlasX": 289,
        "atlasY": 471,
        "atlasW": 424,
        "atlasH": 332
      },
      {
        "mapX": 8842,
        "mapY": 1336,
        "mapW": 30,
        "mapH": 40,
        "atlasX": 1004,
        "atlasY": 1451,
        "atlasW": 30,
        "atlasH": 40
      },
      {
        "mapX": 280,
        "mapY": 1734,
        "mapW": 32,
        "mapH": 40,
        "atlasX": 905,
        "atlasY": 1451,
        "atlasW": 32,
        "atlasH": 40
      },
      {
        "mapX": 3402,
        "mapY": 1590,
        "mapW": 142,
        "mapH": 248,
        "atlasX": 242,
        "atlasY": 832,
        "atlasW": 142,
        "atlasH": 248
      },
      {
        "mapX": 4970,
        "mapY": 1720,
        "mapW": 28,
        "mapH": 38,
        "atlasX": 1259,
        "atlasY": 1451,
        "atlasW": 28,
        "atlasH": 38
      },
      {
        "mapX": 7928,
        "mapY": 1542,
        "mapW": 222,
        "mapH": 152,
        "atlasX": 1510,
        "atlasY": 1097,
        "atlasW": 222,
        "atlasH": 152
      },
      {
        "mapX": 8218,
        "mapY": 1536,
        "mapW": 46,
        "mapH": 190,
        "atlasX": 457,
        "atlasY": 1097,
        "atlasW": 46,
        "atlasH": 190
      },
      {
        "mapX": 10536,
        "mapY": 1772,
        "mapW": 216,
        "mapH": 276,
        "atlasX": 1443,
        "atlasY": 471,
        "atlasW": 216,
        "atlasH": 276
      },
      {
        "mapX": 10752,
        "mapY": 1654,
        "mapW": 408,
        "mapH": 394,
        "atlasX": 874,
        "atlasY": 0,
        "atlasW": 408,
        "atlasH": 394
      },
      {
        "mapX": 296,
        "mapY": 2088,
        "mapW": 216,
        "mapH": 470,
        "atlasX": 0,
        "atlasY": 0,
        "atlasW": 216,
        "atlasH": 470
      },
      {
        "mapX": 512,
        "mapY": 2506,
        "mapW": 6,
        "mapH": 34,
        "atlasX": 1384,
        "atlasY": 1451,
        "atlasW": 6,
        "atlasH": 34
      },
      {
        "mapX": 1240,
        "mapY": 2072,
        "mapW": 160,
        "mapH": 70,
        "atlasX": 79,
        "atlasY": 1451,
        "atlasW": 160,
        "atlasH": 70
      },
      {
        "mapX": 1818,
        "mapY": 2134,
        "mapW": 28,
        "mapH": 40,
        "atlasX": 1064,
        "atlasY": 1451,
        "atlasW": 28,
        "atlasH": 40
      },
      {
        "mapX": 2440,
        "mapY": 2422,
        "mapW": 32,
        "mapH": 40,
        "atlasX": 938,
        "atlasY": 1451,
        "atlasW": 32,
        "atlasH": 40
      },
      {
        "mapX": 2636,
        "mapY": 2280,
        "mapW": 396,
        "mapH": 134,
        "atlasX": 237,
        "atlasY": 1314,
        "atlasW": 396,
        "atlasH": 134
      },
      {
        "mapX": 3320,
        "mapY": 2310,
        "mapW": 264,
        "mapH": 168,
        "atlasX": 772,
        "atlasY": 1097,
        "atlasW": 264,
        "atlasH": 168
      },
      {
        "mapX": 3584,
        "mapY": 2356,
        "mapW": 472,
        "mapH": 154,
        "atlasX": 1037,
        "atlasY": 1097,
        "atlasW": 472,
        "atlasH": 154
      },
      {
        "mapX": 4280,
        "mapY": 2342,
        "mapW": 28,
        "mapH": 40,
        "atlasX": 1093,
        "atlasY": 1451,
        "atlasW": 28,
        "atlasH": 40
      },
      {
        "mapX": 4778,
        "mapY": 2102,
        "mapW": 28,
        "mapH": 42,
        "atlasX": 719,
        "atlasY": 1451,
        "atlasW": 28,
        "atlasH": 42
      },
      {
        "mapX": 6842,
        "mapY": 2422,
        "mapW": 28,
        "mapH": 40,
        "atlasX": 1122,
        "atlasY": 1451,
        "atlasW": 28,
        "atlasH": 40
      },
      {
        "mapX": 10728,
        "mapY": 2048,
        "mapW": 24,
        "mapH": 30,
        "atlasX": 1398,
        "atlasY": 1451,
        "atlasW": 24,
        "atlasH": 30
      },
      {
        "mapX": 10752,
        "mapY": 2048,
        "mapW": 312,
        "mapH": 110,
        "atlasX": 1292,
        "atlasY": 1314,
        "atlasW": 312,
        "atlasH": 110
      },
      {
        "mapX": 186,
        "mapY": 2648,
        "mapW": 236,
        "mapH": 136,
        "atlasX": 0,
        "atlasY": 1314,
        "atlasW": 236,
        "atlasH": 136
      },
      {
        "mapX": 586,
        "mapY": 3018,
        "mapW": 28,
        "mapH": 36,
        "atlasX": 1346,
        "atlasY": 1451,
        "atlasW": 28,
        "atlasH": 36
      },
      {
        "mapX": 3352,
        "mapY": 2648,
        "mapW": 110,
        "mapH": 102,
        "atlasX": 1908,
        "atlasY": 1314,
        "atlasW": 110,
        "atlasH": 102
      },
      {
        "mapX": 3626,
        "mapY": 2918,
        "mapW": 28,
        "mapH": 42,
        "atlasX": 748,
        "atlasY": 1451,
        "atlasW": 28,
        "atlasH": 42
      },
      {
        "mapX": 9690,
        "mapY": 2643,
        "mapW": 28,
        "mapH": 40,
        "atlasX": 1151,
        "atlasY": 1451,
        "atlasW": 28,
        "atlasH": 40
      },
      {
        "mapX": 9768,
        "mapY": 2815,
        "mapW": 348,
        "mapH": 219,
        "atlasX": 1543,
        "atlasY": 832,
        "atlasW": 348,
        "atlasH": 219
      },
      {
        "mapX": 74,
        "mapY": 3190,
        "mapW": 78,
        "mapH": 152,
        "atlasX": 1733,
        "atlasY": 1097,
        "atlasW": 78,
        "atlasH": 152
      },
      {
        "mapX": 2024,
        "mapY": 3542,
        "mapW": 24,
        "mapH": 40,
        "atlasX": 1180,
        "atlasY": 1451,
        "atlasW": 24,
        "atlasH": 40
      },
      {
        "mapX": 2048,
        "mapY": 3544,
        "mapW": 8,
        "mapH": 36,
        "atlasX": 1375,
        "atlasY": 1451,
        "atlasW": 8,
        "atlasH": 36
      },
      {
        "mapX": 3338,
        "mapY": 3446,
        "mapW": 28,
        "mapH": 42,
        "atlasX": 777,
        "atlasY": 1451,
        "atlasW": 28,
        "atlasH": 42
      },
      {
        "mapX": 9416,
        "mapY": 3152,
        "mapW": 208,
        "mapH": 172,
        "atlasX": 563,
        "atlasY": 1097,
        "atlasW": 208,
        "atlasH": 172
      },
      {
        "mapX": 9736,
        "mapY": 3107,
        "mapW": 352,
        "mapH": 55,
        "atlasX": 269,
        "atlasY": 1451,
        "atlasW": 352,
        "atlasH": 55
      },
      {
        "mapX": 232,
        "mapY": 3672,
        "mapW": 272,
        "mapH": 424,
        "atlasX": 386,
        "atlasY": 0,
        "atlasW": 272,
        "atlasH": 424
      },
      {
        "mapX": 762,
        "mapY": 3844,
        "mapW": 220,
        "mapH": 234,
        "atlasX": 1139,
        "atlasY": 832,
        "atlasW": 220,
        "atlasH": 234
      },
      {
        "mapX": 1404,
        "mapY": 4034,
        "mapW": 24,
        "mapH": 28,
        "atlasX": 1423,
        "atlasY": 1451,
        "atlasW": 24,
        "atlasH": 28
      },
      {
        "mapX": 1706,
        "mapY": 3912,
        "mapW": 342,
        "mapH": 114,
        "atlasX": 949,
        "atlasY": 1314,
        "atlasW": 342,
        "atlasH": 114
      },
      {
        "mapX": 2048,
        "mapY": 3656,
        "mapW": 214,
        "mapH": 406,
        "atlasX": 659,
        "atlasY": 0,
        "atlasW": 214,
        "atlasH": 406
      },
      {
        "mapX": 2700,
        "mapY": 3686,
        "mapW": 24,
        "mapH": 40,
        "atlasX": 1205,
        "atlasY": 1451,
        "atlasW": 24,
        "atlasH": 40
      },
      {
        "mapX": 3304,
        "mapY": 3642,
        "mapW": 190,
        "mapH": 372,
        "atlasX": 1739,
        "atlasY": 0,
        "atlasW": 190,
        "atlasH": 372
      },
      {
        "mapX": 3626,
        "mapY": 3798,
        "mapW": 60,
        "mapH": 250,
        "atlasX": 181,
        "atlasY": 832,
        "atlasW": 60,
        "atlasH": 250
      },
      {
        "mapX": 442,
        "mapY": 4096,
        "mapW": 28,
        "mapH": 14,
        "atlasX": 1481,
        "atlasY": 1451,
        "atlasW": 28,
        "atlasH": 14
      },
      {
        "mapX": 1946,
        "mapY": 4342,
        "mapW": 78,
        "mapH": 72,
        "atlasX": 0,
        "atlasY": 1451,
        "atlasW": 78,
        "atlasH": 72
      },
      {
        "mapX": 2170,
        "mapY": 4296,
        "mapW": 28,
        "mapH": 38,
        "atlasX": 1288,
        "atlasY": 1451,
        "atlasW": 28,
        "atlasH": 38
      },
      {
        "mapX": 3274,
        "mapY": 4310,
        "mapW": 310,
        "mapH": 298,
        "atlasX": 929,
        "atlasY": 471,
        "atlasW": 310,
        "atlasH": 298
      },
      {
        "mapX": 3584,
        "mapY": 4344,
        "mapW": 180,
        "mapH": 264,
        "atlasX": 0,
        "atlasY": 832,
        "atlasW": 180,
        "atlasH": 264
      },
      {
        "mapX": 7820,
        "mapY": 4360,
        "mapW": 58,
        "mapH": 182,
        "atlasX": 504,
        "atlasY": 1097,
        "atlasW": 58,
        "atlasH": 182
      },
      {
        "mapX": 1992,
        "mapY": 4614,
        "mapW": 32,
        "mapH": 40,
        "atlasX": 971,
        "atlasY": 1451,
        "atlasW": 32,
        "atlasH": 40
      },
      {
        "mapX": 2104,
        "mapY": 4652,
        "mapW": 92,
        "mapH": 146,
        "atlasX": 1812,
        "atlasY": 1097,
        "atlasW": 92,
        "atlasH": 146
      },
      {
        "mapX": 3256,
        "mapY": 4630,
        "mapW": 288,
        "mapH": 360,
        "atlasX": 0,
        "atlasY": 471,
        "atlasW": 288,
        "atlasH": 360
      },
      {
        "mapX": 3608,
        "mapY": 4608,
        "mapW": 206,
        "mapH": 382,
        "atlasX": 1532,
        "atlasY": 0,
        "atlasW": 206,
        "atlasH": 382
      },
      {
        "mapX": 3370,
        "mapY": 5202,
        "mapW": 214,
        "mapH": 316,
        "atlasX": 714,
        "atlasY": 471,
        "atlasW": 214,
        "atlasH": 316
      },
      {
        "mapX": 3584,
        "mapY": 5192,
        "mapW": 168,
        "mapH": 440,
        "atlasX": 217,
        "atlasY": 0,
        "atlasW": 168,
        "atlasH": 440
      },
      {
        "mapX": 970,
        "mapY": 5864,
        "mapW": 28,
        "mapH": 38,
        "atlasX": 1317,
        "atlasY": 1451,
        "atlasW": 28,
        "atlasH": 38
      },
      {
        "mapX": 1064,
        "mapY": 5912,
        "mapW": 112,
        "mapH": 118,
        "atlasX": 836,
        "atlasY": 1314,
        "atlasW": 112,
        "atlasH": 118
      },
      {
        "mapX": 3672,
        "mapY": 5632,
        "mapW": 32,
        "mapH": 14,
        "atlasX": 1448,
        "atlasY": 1451,
        "atlasW": 32,
        "atlasH": 14
      }
    ]
  },
  "item": {
    "atlasWidth": 1944,
    "atlasHeight": 674,
    "tiles": [
      {
        "mapX": 750,
        "mapY": 114,
        "mapW": 20,
        "mapH": 20,
        "atlasX": 346,
        "atlasY": 622,
        "atlasW": 20,
        "atlasH": 20
      },
      {
        "mapX": 1134,
        "mapY": 322,
        "mapW": 20,
        "mapH": 20,
        "atlasX": 367,
        "atlasY": 622,
        "atlasW": 20,
        "atlasH": 20
      },
      {
        "mapX": 1838,
        "mapY": 226,
        "mapW": 20,
        "mapH": 20,
        "atlasX": 388,
        "atlasY": 622,
        "atlasW": 20,
        "atlasH": 20
      },
      {
        "mapX": 2446,
        "mapY": 98,
        "mapW": 20,
        "mapH": 20,
        "atlasX": 409,
        "atlasY": 622,
        "atlasW": 20,
        "atlasH": 20
      },
      {
        "mapX": 2862,
        "mapY": 66,
        "mapW": 20,
        "mapH": 20,
        "atlasX": 430,
        "atlasY": 622,
        "atlasW": 20,
        "atlasH": 20
      },
      {
        "mapX": 4606,
        "mapY": 280,
        "mapW": 2,
        "mapH": 8,
        "atlasX": 1308,
        "atlasY": 622,
        "atlasW": 2,
        "atlasH": 8
      },
      {
        "mapX": 4608,
        "mapY": 66,
        "mapW": 194,
        "mapH": 228,
        "atlasX": 789,
        "atlasY": 0,
        "atlasW": 194,
        "atlasH": 228
      },
      {
        "mapX": 6110,
        "mapY": 194,
        "mapW": 20,
        "mapH": 20,
        "atlasX": 451,
        "atlasY": 622,
        "atlasW": 20,
        "atlasH": 20
      },
      {
        "mapX": 190,
        "mapY": 770,
        "mapW": 116,
        "mapH": 132,
        "atlasX": 275,
        "atlasY": 489,
        "atlasW": 116,
        "atlasH": 132
      },
      {
        "mapX": 814,
        "mapY": 610,
        "mapW": 20,
        "mapH": 20,
        "atlasX": 472,
        "atlasY": 622,
        "atlasW": 20,
        "atlasH": 20
      },
      {
        "mapX": 2782,
        "mapY": 994,
        "mapW": 20,
        "mapH": 20,
        "atlasX": 493,
        "atlasY": 622,
        "atlasW": 20,
        "atlasH": 20
      },
      {
        "mapX": 3390,
        "mapY": 850,
        "mapW": 20,
        "mapH": 20,
        "atlasX": 514,
        "atlasY": 622,
        "atlasW": 20,
        "atlasH": 20
      },
      {
        "mapX": 4526,
        "mapY": 882,
        "mapW": 20,
        "mapH": 20,
        "atlasX": 535,
        "atlasY": 622,
        "atlasW": 20,
        "atlasH": 20
      },
      {
        "mapX": 4862,
        "mapY": 658,
        "mapW": 100,
        "mapH": 196,
        "atlasX": 1179,
        "atlasY": 0,
        "atlasW": 100,
        "atlasH": 196
      },
      {
        "mapX": 6078,
        "mapY": 520,
        "mapW": 66,
        "mapH": 366,
        "atlasX": 451,
        "atlasY": 0,
        "atlasW": 66,
        "atlasH": 366
      },
      {
        "mapX": 6144,
        "mapY": 514,
        "mapW": 18,
        "mapH": 20,
        "atlasX": 1249,
        "atlasY": 622,
        "atlasW": 18,
        "atlasH": 20
      },
      {
        "mapX": 366,
        "mapY": 1122,
        "mapW": 20,
        "mapH": 20,
        "atlasX": 556,
        "atlasY": 622,
        "atlasW": 20,
        "atlasH": 20
      },
      {
        "mapX": 4542,
        "mapY": 1522,
        "mapW": 20,
        "mapH": 14,
        "atlasX": 1287,
        "atlasY": 622,
        "atlasW": 20,
        "atlasH": 14
      },
      {
        "mapX": 4878,
        "mapY": 1202,
        "mapW": 20,
        "mapH": 20,
        "atlasX": 577,
        "atlasY": 622,
        "atlasW": 20,
        "atlasH": 20
      },
      {
        "mapX": 5870,
        "mapY": 1298,
        "mapW": 274,
        "mapH": 132,
        "atlasX": 0,
        "atlasY": 489,
        "atlasW": 274,
        "atlasH": 132
      },
      {
        "mapX": 6144,
        "mapY": 1304,
        "mapW": 2,
        "mapH": 8,
        "atlasX": 1311,
        "atlasY": 622,
        "atlasW": 2,
        "atlasH": 8
      },
      {
        "mapX": 7006,
        "mapY": 1474,
        "mapW": 20,
        "mapH": 20,
        "atlasX": 598,
        "atlasY": 622,
        "atlasW": 20,
        "atlasH": 20
      },
      {
        "mapX": 7278,
        "mapY": 1426,
        "mapW": 100,
        "mapH": 20,
        "atlasX": 245,
        "atlasY": 622,
        "atlasW": 100,
        "atlasH": 20
      },
      {
        "mapX": 9406,
        "mapY": 1138,
        "mapW": 20,
        "mapH": 20,
        "atlasX": 619,
        "atlasY": 622,
        "atlasW": 20,
        "atlasH": 20
      },
      {
        "mapX": 9886,
        "mapY": 1122,
        "mapW": 20,
        "mapH": 20,
        "atlasX": 640,
        "atlasY": 622,
        "atlasW": 20,
        "atlasH": 20
      },
      {
        "mapX": 10974,
        "mapY": 1218,
        "mapW": 20,
        "mapH": 20,
        "atlasX": 661,
        "atlasY": 622,
        "atlasW": 20,
        "atlasH": 20
      },
      {
        "mapX": 318,
        "mapY": 1554,
        "mapW": 194,
        "mapH": 196,
        "atlasX": 984,
        "atlasY": 0,
        "atlasW": 194,
        "atlasH": 196
      },
      {
        "mapX": 512,
        "mapY": 1560,
        "mapW": 450,
        "mapH": 488,
        "atlasX": 0,
        "atlasY": 0,
        "atlasW": 450,
        "atlasH": 488
      },
      {
        "mapX": 3246,
        "mapY": 1810,
        "mapW": 276,
        "mapH": 84,
        "atlasX": 1157,
        "atlasY": 489,
        "atlasW": 276,
        "atlasH": 84
      },
      {
        "mapX": 3726,
        "mapY": 1650,
        "mapW": 20,
        "mapH": 20,
        "atlasX": 682,
        "atlasY": 622,
        "atlasW": 20,
        "atlasH": 20
      },
      {
        "mapX": 4544,
        "mapY": 1536,
        "mapW": 16,
        "mapH": 6,
        "atlasX": 1317,
        "atlasY": 622,
        "atlasW": 16,
        "atlasH": 6
      },
      {
        "mapX": 4670,
        "mapY": 1858,
        "mapW": 356,
        "mapH": 84,
        "atlasX": 800,
        "atlasY": 489,
        "atlasW": 356,
        "atlasH": 84
      },
      {
        "mapX": 8654,
        "mapY": 1682,
        "mapW": 20,
        "mapH": 20,
        "atlasX": 703,
        "atlasY": 622,
        "atlasW": 20,
        "atlasH": 20
      },
      {
        "mapX": 9454,
        "mapY": 1794,
        "mapW": 20,
        "mapH": 20,
        "atlasX": 724,
        "atlasY": 622,
        "atlasW": 20,
        "atlasH": 20
      },
      {
        "mapX": 798,
        "mapY": 2048,
        "mapW": 162,
        "mapH": 182,
        "atlasX": 1280,
        "atlasY": 0,
        "atlasW": 162,
        "atlasH": 182
      },
      {
        "mapX": 1182,
        "mapY": 2050,
        "mapW": 354,
        "mapH": 100,
        "atlasX": 445,
        "atlasY": 489,
        "atlasW": 354,
        "atlasH": 100
      },
      {
        "mapX": 1536,
        "mapY": 2066,
        "mapW": 402,
        "mapH": 78,
        "atlasX": 1434,
        "atlasY": 489,
        "atlasW": 402,
        "atlasH": 78
      },
      {
        "mapX": 2382,
        "mapY": 2242,
        "mapW": 132,
        "mapH": 292,
        "atlasX": 518,
        "atlasY": 0,
        "atlasW": 132,
        "atlasH": 292
      },
      {
        "mapX": 3646,
        "mapY": 2530,
        "mapW": 20,
        "mapH": 20,
        "atlasX": 745,
        "atlasY": 622,
        "atlasW": 20,
        "atlasH": 20
      },
      {
        "mapX": 4942,
        "mapY": 2338,
        "mapW": 20,
        "mapH": 20,
        "atlasX": 766,
        "atlasY": 622,
        "atlasW": 20,
        "atlasH": 20
      },
      {
        "mapX": 5550,
        "mapY": 2354,
        "mapW": 82,
        "mapH": 180,
        "atlasX": 1443,
        "atlasY": 0,
        "atlasW": 82,
        "atlasH": 180
      },
      {
        "mapX": 5632,
        "mapY": 2360,
        "mapW": 418,
        "mapH": 142,
        "atlasX": 1526,
        "atlasY": 0,
        "atlasW": 418,
        "atlasH": 142
      },
      {
        "mapX": 6318,
        "mapY": 2370,
        "mapW": 20,
        "mapH": 20,
        "atlasX": 787,
        "atlasY": 622,
        "atlasW": 20,
        "atlasH": 20
      },
      {
        "mapX": 9182,
        "mapY": 2242,
        "mapW": 20,
        "mapH": 20,
        "atlasX": 808,
        "atlasY": 622,
        "atlasW": 20,
        "atlasH": 20
      },
      {
        "mapX": 10446,
        "mapY": 2322,
        "mapW": 36,
        "mapH": 238,
        "atlasX": 752,
        "atlasY": 0,
        "atlasW": 36,
        "atlasH": 238
      },
      {
        "mapX": 11230,
        "mapY": 2146,
        "mapW": 20,
        "mapH": 20,
        "atlasX": 829,
        "atlasY": 622,
        "atlasW": 20,
        "atlasH": 20
      },
      {
        "mapX": 78,
        "mapY": 3026,
        "mapW": 20,
        "mapH": 20,
        "atlasX": 850,
        "atlasY": 622,
        "atlasW": 20,
        "atlasH": 20
      },
      {
        "mapX": 574,
        "mapY": 2754,
        "mapW": 20,
        "mapH": 20,
        "atlasX": 871,
        "atlasY": 622,
        "atlasW": 20,
        "atlasH": 20
      },
      {
        "mapX": 10448,
        "mapY": 2560,
        "mapW": 16,
        "mapH": 6,
        "atlasX": 1334,
        "atlasY": 622,
        "atlasW": 16,
        "atlasH": 6
      },
      {
        "mapX": 11262,
        "mapY": 2856,
        "mapW": 2,
        "mapH": 8,
        "atlasX": 1314,
        "atlasY": 622,
        "atlasW": 2,
        "atlasH": 8
      },
      {
        "mapX": 11264,
        "mapY": 2850,
        "mapW": 18,
        "mapH": 20,
        "atlasX": 1268,
        "atlasY": 622,
        "atlasW": 18,
        "atlasH": 20
      },
      {
        "mapX": 590,
        "mapY": 3138,
        "mapW": 52,
        "mapH": 132,
        "atlasX": 392,
        "atlasY": 489,
        "atlasW": 52,
        "atlasH": 132
      },
      {
        "mapX": 3294,
        "mapY": 3154,
        "mapW": 20,
        "mapH": 20,
        "atlasX": 892,
        "atlasY": 622,
        "atlasW": 20,
        "atlasH": 20
      },
      {
        "mapX": 3614,
        "mapY": 3298,
        "mapW": 20,
        "mapH": 20,
        "atlasX": 913,
        "atlasY": 622,
        "atlasW": 20,
        "atlasH": 20
      },
      {
        "mapX": 462,
        "mapY": 3746,
        "mapW": 20,
        "mapH": 20,
        "atlasX": 934,
        "atlasY": 622,
        "atlasW": 20,
        "atlasH": 20
      },
      {
        "mapX": 942,
        "mapY": 3730,
        "mapW": 20,
        "mapH": 20,
        "atlasX": 955,
        "atlasY": 622,
        "atlasW": 20,
        "atlasH": 20
      },
      {
        "mapX": 2718,
        "mapY": 3586,
        "mapW": 244,
        "mapH": 52,
        "atlasX": 0,
        "atlasY": 622,
        "atlasW": 244,
        "atlasH": 52
      },
      {
        "mapX": 3678,
        "mapY": 3650,
        "mapW": 20,
        "mapH": 20,
        "atlasX": 976,
        "atlasY": 622,
        "atlasW": 20,
        "atlasH": 20
      },
      {
        "mapX": 686,
        "mapY": 4146,
        "mapW": 20,
        "mapH": 20,
        "atlasX": 997,
        "atlasY": 622,
        "atlasW": 20,
        "atlasH": 20
      },
      {
        "mapX": 1294,
        "mapY": 4098,
        "mapW": 20,
        "mapH": 20,
        "atlasX": 1018,
        "atlasY": 622,
        "atlasW": 20,
        "atlasH": 20
      },
      {
        "mapX": 4190,
        "mapY": 4578,
        "mapW": 20,
        "mapH": 20,
        "atlasX": 1039,
        "atlasY": 622,
        "atlasW": 20,
        "atlasH": 20
      },
      {
        "mapX": 4638,
        "mapY": 4418,
        "mapW": 20,
        "mapH": 20,
        "atlasX": 1060,
        "atlasY": 622,
        "atlasW": 20,
        "atlasH": 20
      },
      {
        "mapX": 5246,
        "mapY": 4306,
        "mapW": 20,
        "mapH": 20,
        "atlasX": 1081,
        "atlasY": 622,
        "atlasW": 20,
        "atlasH": 20
      },
      {
        "mapX": 5886,
        "mapY": 4338,
        "mapW": 100,
        "mapH": 270,
        "atlasX": 651,
        "atlasY": 0,
        "atlasW": 100,
        "atlasH": 270
      },
      {
        "mapX": 6558,
        "mapY": 4322,
        "mapW": 20,
        "mapH": 20,
        "atlasX": 1102,
        "atlasY": 622,
        "atlasW": 20,
        "atlasH": 20
      },
      {
        "mapX": 6718,
        "mapY": 4578,
        "mapW": 20,
        "mapH": 20,
        "atlasX": 1123,
        "atlasY": 622,
        "atlasW": 20,
        "atlasH": 20
      },
      {
        "mapX": 5888,
        "mapY": 4608,
        "mapW": 16,
        "mapH": 6,
        "atlasX": 1351,
        "atlasY": 622,
        "atlasW": 16,
        "atlasH": 6
      },
      {
        "mapX": 126,
        "mapY": 5346,
        "mapW": 20,
        "mapH": 20,
        "atlasX": 1144,
        "atlasY": 622,
        "atlasW": 20,
        "atlasH": 20
      },
      {
        "mapX": 3598,
        "mapY": 5202,
        "mapW": 20,
        "mapH": 20,
        "atlasX": 1165,
        "atlasY": 622,
        "atlasW": 20,
        "atlasH": 20
      },
      {
        "mapX": 462,
        "mapY": 5682,
        "mapW": 20,
        "mapH": 20,
        "atlasX": 1186,
        "atlasY": 622,
        "atlasW": 20,
        "atlasH": 20
      },
      {
        "mapX": 2910,
        "mapY": 5810,
        "mapW": 20,
        "mapH": 20,
        "atlasX": 1207,
        "atlasY": 622,
        "atlasW": 20,
        "atlasH": 20
      },
      {
        "mapX": 3630,
        "mapY": 5842,
        "mapW": 20,
        "mapH": 20,
        "atlasX": 1228,
        "atlasY": 622,
        "atlasW": 20,
        "atlasH": 20
      }
    ]
  },
  "hidden": {
    "atlasWidth": 2007,
    "atlasHeight": 459,
    "tiles": [
      {
        "mapX": 750,
        "mapY": 498,
        "mapW": 20,
        "mapH": 14,
        "atlasX": 1229,
        "atlasY": 439,
        "atlasW": 20,
        "atlasH": 14
      },
      {
        "mapX": 1310,
        "mapY": 226,
        "mapW": 20,
        "mapH": 20,
        "atlasX": 584,
        "atlasY": 439,
        "atlasW": 20,
        "atlasH": 20
      },
      {
        "mapX": 1950,
        "mapY": 66,
        "mapW": 20,
        "mapH": 20,
        "atlasX": 605,
        "atlasY": 439,
        "atlasW": 20,
        "atlasH": 20
      },
      {
        "mapX": 2654,
        "mapY": 34,
        "mapW": 132,
        "mapH": 20,
        "atlasX": 451,
        "atlasY": 439,
        "atlasW": 132,
        "atlasH": 20
      },
      {
        "mapX": 4798,
        "mapY": 450,
        "mapW": 20,
        "mapH": 20,
        "atlasX": 626,
        "atlasY": 439,
        "atlasW": 20,
        "atlasH": 20
      },
      {
        "mapX": 5902,
        "mapY": 2,
        "mapW": 20,
        "mapH": 20,
        "atlasX": 647,
        "atlasY": 439,
        "atlasW": 20,
        "atlasH": 20
      },
      {
        "mapX": 6254,
        "mapY": 162,
        "mapW": 20,
        "mapH": 20,
        "atlasX": 668,
        "atlasY": 439,
        "atlasW": 20,
        "atlasH": 20
      },
      {
        "mapX": 752,
        "mapY": 512,
        "mapW": 226,
        "mapH": 438,
        "atlasX": 0,
        "atlasY": 0,
        "atlasW": 226,
        "atlasH": 438
      },
      {
        "mapX": 3502,
        "mapY": 866,
        "mapW": 20,
        "mapH": 20,
        "atlasX": 689,
        "atlasY": 439,
        "atlasW": 20,
        "atlasH": 20
      },
      {
        "mapX": 5086,
        "mapY": 994,
        "mapW": 20,
        "mapH": 20,
        "atlasX": 710,
        "atlasY": 439,
        "atlasW": 20,
        "atlasH": 20
      },
      {
        "mapX": 6142,
        "mapY": 664,
        "mapW": 2,
        "mapH": 8,
        "atlasX": 1250,
        "atlasY": 439,
        "atlasW": 2,
        "atlasH": 8
      },
      {
        "mapX": 6144,
        "mapY": 658,
        "mapW": 18,
        "mapH": 20,
        "atlasX": 1172,
        "atlasY": 439,
        "atlasW": 18,
        "atlasH": 20
      },
      {
        "mapX": 238,
        "mapY": 1442,
        "mapW": 20,
        "mapH": 20,
        "atlasX": 731,
        "atlasY": 439,
        "atlasW": 20,
        "atlasH": 20
      },
      {
        "mapX": 2302,
        "mapY": 1026,
        "mapW": 20,
        "mapH": 20,
        "atlasX": 752,
        "atlasY": 439,
        "atlasW": 20,
        "atlasH": 20
      },
      {
        "mapX": 3614,
        "mapY": 1042,
        "mapW": 164,
        "mapH": 84,
        "atlasX": 1508,
        "atlasY": 0,
        "atlasW": 164,
        "atlasH": 84
      },
      {
        "mapX": 4750,
        "mapY": 1298,
        "mapW": 20,
        "mapH": 20,
        "atlasX": 773,
        "atlasY": 439,
        "atlasW": 20,
        "atlasH": 20
      },
      {
        "mapX": 5758,
        "mapY": 1362,
        "mapW": 20,
        "mapH": 20,
        "atlasX": 794,
        "atlasY": 439,
        "atlasW": 20,
        "atlasH": 20
      },
      {
        "mapX": 6766,
        "mapY": 1426,
        "mapW": 20,
        "mapH": 20,
        "atlasX": 815,
        "atlasY": 439,
        "atlasW": 20,
        "atlasH": 20
      },
      {
        "mapX": 7326,
        "mapY": 1314,
        "mapW": 244,
        "mapH": 100,
        "atlasX": 1263,
        "atlasY": 0,
        "atlasW": 244,
        "atlasH": 100
      },
      {
        "mapX": 8654,
        "mapY": 1218,
        "mapW": 20,
        "mapH": 20,
        "atlasX": 836,
        "atlasY": 439,
        "atlasW": 20,
        "atlasH": 20
      },
      {
        "mapX": 4894,
        "mapY": 1906,
        "mapW": 20,
        "mapH": 20,
        "atlasX": 857,
        "atlasY": 439,
        "atlasW": 20,
        "atlasH": 20
      },
      {
        "mapX": 8254,
        "mapY": 1602,
        "mapW": 450,
        "mapH": 20,
        "atlasX": 0,
        "atlasY": 439,
        "atlasW": 450,
        "atlasH": 20
      },
      {
        "mapX": 8704,
        "mapY": 1602,
        "mapW": 18,
        "mapH": 20,
        "atlasX": 1191,
        "atlasY": 439,
        "atlasW": 18,
        "atlasH": 20
      },
      {
        "mapX": 990,
        "mapY": 2082,
        "mapW": 20,
        "mapH": 20,
        "atlasX": 878,
        "atlasY": 439,
        "atlasW": 20,
        "atlasH": 20
      },
      {
        "mapX": 1758,
        "mapY": 2146,
        "mapW": 20,
        "mapH": 20,
        "atlasX": 899,
        "atlasY": 439,
        "atlasW": 20,
        "atlasH": 20
      },
      {
        "mapX": 2286,
        "mapY": 2514,
        "mapW": 20,
        "mapH": 20,
        "atlasX": 920,
        "atlasY": 439,
        "atlasW": 20,
        "atlasH": 20
      },
      {
        "mapX": 4030,
        "mapY": 2450,
        "mapW": 20,
        "mapH": 20,
        "atlasX": 941,
        "atlasY": 439,
        "atlasW": 20,
        "atlasH": 20
      },
      {
        "mapX": 4334,
        "mapY": 2434,
        "mapW": 20,
        "mapH": 20,
        "atlasX": 962,
        "atlasY": 439,
        "atlasW": 20,
        "atlasH": 20
      },
      {
        "mapX": 5310,
        "mapY": 2242,
        "mapW": 20,
        "mapH": 20,
        "atlasX": 983,
        "atlasY": 439,
        "atlasW": 20,
        "atlasH": 20
      },
      {
        "mapX": 6318,
        "mapY": 2242,
        "mapW": 276,
        "mapH": 244,
        "atlasX": 800,
        "atlasY": 0,
        "atlasW": 276,
        "atlasH": 244
      },
      {
        "mapX": 7326,
        "mapY": 2466,
        "mapW": 36,
        "mapH": 68,
        "atlasX": 1758,
        "atlasY": 0,
        "atlasW": 36,
        "atlasH": 68
      },
      {
        "mapX": 46,
        "mapY": 2994,
        "mapW": 84,
        "mapH": 68,
        "atlasX": 1673,
        "atlasY": 0,
        "atlasW": 84,
        "atlasH": 68
      },
      {
        "mapX": 3262,
        "mapY": 3106,
        "mapW": 20,
        "mapH": 20,
        "atlasX": 1004,
        "atlasY": 439,
        "atlasW": 20,
        "atlasH": 20
      },
      {
        "mapX": 3726,
        "mapY": 3170,
        "mapW": 52,
        "mapH": 116,
        "atlasX": 1210,
        "atlasY": 0,
        "atlasW": 52,
        "atlasH": 116
      },
      {
        "mapX": 222,
        "mapY": 3778,
        "mapW": 52,
        "mapH": 292,
        "atlasX": 646,
        "atlasY": 0,
        "atlasW": 52,
        "atlasH": 292
      },
      {
        "mapX": 3790,
        "mapY": 3618,
        "mapW": 20,
        "mapH": 20,
        "atlasX": 1025,
        "atlasY": 439,
        "atlasW": 20,
        "atlasH": 20
      },
      {
        "mapX": 10734,
        "mapY": 4034,
        "mapW": 18,
        "mapH": 20,
        "atlasX": 1210,
        "atlasY": 439,
        "atlasW": 18,
        "atlasH": 20
      },
      {
        "mapX": 10752,
        "mapY": 3650,
        "mapW": 418,
        "mapH": 398,
        "atlasX": 227,
        "atlasY": 0,
        "atlasW": 418,
        "atlasH": 398
      },
      {
        "mapX": 814,
        "mapY": 4162,
        "mapW": 20,
        "mapH": 20,
        "atlasX": 1046,
        "atlasY": 439,
        "atlasW": 20,
        "atlasH": 20
      },
      {
        "mapX": 78,
        "mapY": 5074,
        "mapW": 20,
        "mapH": 20,
        "atlasX": 1067,
        "atlasY": 439,
        "atlasW": 20,
        "atlasH": 20
      },
      {
        "mapX": 238,
        "mapY": 5266,
        "mapW": 20,
        "mapH": 20,
        "atlasX": 1088,
        "atlasY": 439,
        "atlasW": 20,
        "atlasH": 20
      },
      {
        "mapX": 3342,
        "mapY": 5266,
        "mapW": 132,
        "mapH": 228,
        "atlasX": 1077,
        "atlasY": 0,
        "atlasW": 132,
        "atlasH": 228
      },
      {
        "mapX": 3646,
        "mapY": 5186,
        "mapW": 100,
        "mapH": 260,
        "atlasX": 699,
        "atlasY": 0,
        "atlasW": 100,
        "atlasH": 260
      },
      {
        "mapX": 654,
        "mapY": 5634,
        "mapW": 212,
        "mapH": 36,
        "atlasX": 1795,
        "atlasY": 0,
        "atlasW": 212,
        "atlasH": 36
      },
      {
        "mapX": 1086,
        "mapY": 5698,
        "mapW": 20,
        "mapH": 20,
        "atlasX": 1109,
        "atlasY": 439,
        "atlasW": 20,
        "atlasH": 20
      },
      {
        "mapX": 2846,
        "mapY": 5970,
        "mapW": 20,
        "mapH": 20,
        "atlasX": 1130,
        "atlasY": 439,
        "atlasW": 20,
        "atlasH": 20
      },
      {
        "mapX": 3326,
        "mapY": 5778,
        "mapW": 20,
        "mapH": 20,
        "atlasX": 1151,
        "atlasY": 439,
        "atlasW": 20,
        "atlasH": 20
      }
    ]
  },
  "berry": {
    "atlasWidth": 2045,
    "atlasHeight": 417,
    "tiles": [
      {
        "mapX": 2984,
        "mapY": 366,
        "mapW": 80,
        "mapH": 56,
        "atlasX": 1624,
        "atlasY": 0,
        "atlasW": 80,
        "atlasH": 56
      },
      {
        "mapX": 3480,
        "mapY": 30,
        "mapW": 104,
        "mapH": 56,
        "atlasX": 1519,
        "atlasY": 0,
        "atlasW": 104,
        "atlasH": 56
      },
      {
        "mapX": 3584,
        "mapY": 34,
        "mapW": 8,
        "mapH": 48,
        "atlasX": 474,
        "atlasY": 361,
        "atlasW": 8,
        "atlasH": 48
      },
      {
        "mapX": 4600,
        "mapY": 318,
        "mapW": 8,
        "mapH": 52,
        "atlasX": 465,
        "atlasY": 361,
        "atlasW": 8,
        "atlasH": 52
      },
      {
        "mapX": 4608,
        "mapY": 30,
        "mapW": 312,
        "mapH": 344,
        "atlasX": 369,
        "atlasY": 0,
        "atlasW": 312,
        "atlasH": 344
      },
      {
        "mapX": 6296,
        "mapY": 334,
        "mapW": 64,
        "mapH": 56,
        "atlasX": 1786,
        "atlasY": 0,
        "atlasW": 64,
        "atlasH": 56
      },
      {
        "mapX": 184,
        "mapY": 702,
        "mapW": 64,
        "mapH": 56,
        "atlasX": 1851,
        "atlasY": 0,
        "atlasW": 64,
        "atlasH": 56
      },
      {
        "mapX": 1128,
        "mapY": 670,
        "mapW": 32,
        "mapH": 88,
        "atlasX": 1461,
        "atlasY": 0,
        "atlasW": 32,
        "atlasH": 88
      },
      {
        "mapX": 4936,
        "mapY": 1390,
        "mapW": 48,
        "mapH": 56,
        "atlasX": 260,
        "atlasY": 361,
        "atlasW": 48,
        "atlasH": 56
      },
      {
        "mapX": 5816,
        "mapY": 1214,
        "mapW": 144,
        "mapH": 264,
        "atlasX": 1171,
        "atlasY": 0,
        "atlasW": 144,
        "atlasH": 264
      },
      {
        "mapX": 6616,
        "mapY": 1262,
        "mapW": 40,
        "mapH": 56,
        "atlasX": 309,
        "atlasY": 361,
        "atlasW": 40,
        "atlasH": 56
      },
      {
        "mapX": 6656,
        "mapY": 1262,
        "mapW": 40,
        "mapH": 56,
        "atlasX": 350,
        "atlasY": 361,
        "atlasW": 40,
        "atlasH": 56
      },
      {
        "mapX": 7416,
        "mapY": 1454,
        "mapW": 80,
        "mapH": 56,
        "atlasX": 1705,
        "atlasY": 0,
        "atlasW": 80,
        "atlasH": 56
      },
      {
        "mapX": 488,
        "mapY": 1646,
        "mapW": 24,
        "mapH": 72,
        "atlasX": 1494,
        "atlasY": 0,
        "atlasW": 24,
        "atlasH": 72
      },
      {
        "mapX": 512,
        "mapY": 1650,
        "mapW": 488,
        "mapH": 340,
        "atlasX": 682,
        "atlasY": 0,
        "atlasW": 488,
        "atlasH": 340
      },
      {
        "mapX": 2888,
        "mapY": 2398,
        "mapW": 64,
        "mapH": 56,
        "atlasX": 1916,
        "atlasY": 0,
        "atlasW": 64,
        "atlasH": 56
      },
      {
        "mapX": 4392,
        "mapY": 2270,
        "mapW": 64,
        "mapH": 56,
        "atlasX": 1981,
        "atlasY": 0,
        "atlasW": 64,
        "atlasH": 56
      },
      {
        "mapX": 5288,
        "mapY": 2238,
        "mapW": 144,
        "mapH": 88,
        "atlasX": 1316,
        "atlasY": 0,
        "atlasW": 144,
        "atlasH": 88
      },
      {
        "mapX": 6408,
        "mapY": 2206,
        "mapW": 64,
        "mapH": 56,
        "atlasX": 0,
        "atlasY": 361,
        "atlasW": 64,
        "atlasH": 56
      },
      {
        "mapX": 6856,
        "mapY": 2398,
        "mapW": 64,
        "mapH": 56,
        "atlasX": 65,
        "atlasY": 361,
        "atlasW": 64,
        "atlasH": 56
      },
      {
        "mapX": 536,
        "mapY": 2958,
        "mapW": 64,
        "mapH": 56,
        "atlasX": 130,
        "atlasY": 361,
        "atlasW": 64,
        "atlasH": 56
      },
      {
        "mapX": 3272,
        "mapY": 2686,
        "mapW": 64,
        "mapH": 56,
        "atlasX": 195,
        "atlasY": 361,
        "atlasW": 64,
        "atlasH": 56
      },
      {
        "mapX": 40,
        "mapY": 3214,
        "mapW": 368,
        "mapH": 360,
        "atlasX": 0,
        "atlasY": 0,
        "atlasW": 368,
        "atlasH": 360
      },
      {
        "mapX": 2840,
        "mapY": 3550,
        "mapW": 64,
        "mapH": 34,
        "atlasX": 492,
        "atlasY": 361,
        "atlasW": 64,
        "atlasH": 34
      },
      {
        "mapX": 1496,
        "mapY": 3854,
        "mapW": 40,
        "mapH": 56,
        "atlasX": 391,
        "atlasY": 361,
        "atlasW": 40,
        "atlasH": 56
      },
      {
        "mapX": 1536,
        "mapY": 3858,
        "mapW": 8,
        "mapH": 48,
        "atlasX": 483,
        "atlasY": 361,
        "atlasW": 8,
        "atlasH": 48
      },
      {
        "mapX": 2846,
        "mapY": 3584,
        "mapW": 52,
        "mapH": 22,
        "atlasX": 557,
        "atlasY": 361,
        "atlasW": 52,
        "atlasH": 22
      },
      {
        "mapX": 9784,
        "mapY": 4254,
        "mapW": 32,
        "mapH": 56,
        "atlasX": 432,
        "atlasY": 361,
        "atlasW": 32,
        "atlasH": 56
      }
    ]
  },
  "npc-story": {
    "atlasWidth": 1891,
    "atlasHeight": 234,
    "tiles": [
      {
        "mapX": 938,
        "mapY": 210,
        "mapW": 28,
        "mapH": 30,
        "atlasX": 1856,
        "atlasY": 0,
        "atlasW": 28,
        "atlasH": 30
      },
      {
        "mapX": 2440,
        "mapY": 72,
        "mapW": 32,
        "mapH": 40,
        "atlasX": 1452,
        "atlasY": 0,
        "atlasW": 32,
        "atlasH": 40
      },
      {
        "mapX": 2620,
        "mapY": 278,
        "mapW": 28,
        "mapH": 40,
        "atlasX": 1584,
        "atlasY": 0,
        "atlasW": 28,
        "atlasH": 40
      },
      {
        "mapX": 5610,
        "mapY": 22,
        "mapW": 22,
        "mapH": 40,
        "atlasX": 1696,
        "atlasY": 0,
        "atlasW": 22,
        "atlasH": 40
      },
      {
        "mapX": 5632,
        "mapY": 26,
        "mapW": 360,
        "mapH": 228,
        "atlasX": 221,
        "atlasY": 0,
        "atlasW": 360,
        "atlasH": 228
      },
      {
        "mapX": 2312,
        "mapY": 952,
        "mapW": 32,
        "mapH": 38,
        "atlasX": 1719,
        "atlasY": 0,
        "atlasW": 32,
        "atlasH": 38
      },
      {
        "mapX": 2968,
        "mapY": 774,
        "mapW": 48,
        "mapH": 40,
        "atlasX": 1358,
        "atlasY": 0,
        "atlasW": 48,
        "atlasH": 40
      },
      {
        "mapX": 3402,
        "mapY": 1798,
        "mapW": 28,
        "mapH": 40,
        "atlasX": 1613,
        "atlasY": 0,
        "atlasW": 28,
        "atlasH": 40
      },
      {
        "mapX": 1368,
        "mapY": 2072,
        "mapW": 32,
        "mapH": 38,
        "atlasX": 1752,
        "atlasY": 0,
        "atlasW": 32,
        "atlasH": 38
      },
      {
        "mapX": 3320,
        "mapY": 2310,
        "mapW": 44,
        "mapH": 40,
        "atlasX": 1407,
        "atlasY": 0,
        "atlasW": 44,
        "atlasH": 40
      },
      {
        "mapX": 3656,
        "mapY": 2356,
        "mapW": 32,
        "mapH": 42,
        "atlasX": 1260,
        "atlasY": 0,
        "atlasW": 32,
        "atlasH": 42
      },
      {
        "mapX": 9768,
        "mapY": 2864,
        "mapW": 222,
        "mapH": 170,
        "atlasX": 582,
        "atlasY": 0,
        "atlasW": 222,
        "atlasH": 170
      },
      {
        "mapX": 2024,
        "mapY": 3542,
        "mapW": 24,
        "mapH": 40,
        "atlasX": 1671,
        "atlasY": 0,
        "atlasW": 24,
        "atlasH": 40
      },
      {
        "mapX": 2048,
        "mapY": 3544,
        "mapW": 8,
        "mapH": 36,
        "atlasX": 1847,
        "atlasY": 0,
        "atlasW": 8,
        "atlasH": 36
      },
      {
        "mapX": 9416,
        "mapY": 3152,
        "mapW": 208,
        "mapH": 155,
        "atlasX": 805,
        "atlasY": 0,
        "atlasW": 208,
        "atlasH": 155
      },
      {
        "mapX": 9736,
        "mapY": 3107,
        "mapW": 64,
        "mapH": 40,
        "atlasX": 1293,
        "atlasY": 0,
        "atlasW": 64,
        "atlasH": 40
      },
      {
        "mapX": 762,
        "mapY": 3844,
        "mapW": 220,
        "mapH": 234,
        "atlasX": 0,
        "atlasY": 0,
        "atlasW": 220,
        "atlasH": 234
      },
      {
        "mapX": 2042,
        "mapY": 3996,
        "mapW": 6,
        "mapH": 30,
        "atlasX": 1885,
        "atlasY": 0,
        "atlasW": 6,
        "atlasH": 30
      },
      {
        "mapX": 2048,
        "mapY": 3958,
        "mapW": 152,
        "mapH": 104,
        "atlasX": 1107,
        "atlasY": 0,
        "atlasW": 152,
        "atlasH": 104
      },
      {
        "mapX": 1992,
        "mapY": 4342,
        "mapW": 32,
        "mapH": 40,
        "atlasX": 1485,
        "atlasY": 0,
        "atlasW": 32,
        "atlasH": 40
      },
      {
        "mapX": 3642,
        "mapY": 4344,
        "mapW": 28,
        "mapH": 40,
        "atlasX": 1642,
        "atlasY": 0,
        "atlasW": 28,
        "atlasH": 40
      },
      {
        "mapX": 1992,
        "mapY": 4614,
        "mapW": 32,
        "mapH": 40,
        "atlasX": 1518,
        "atlasY": 0,
        "atlasW": 32,
        "atlasH": 40
      },
      {
        "mapX": 2104,
        "mapY": 4652,
        "mapW": 92,
        "mapH": 146,
        "atlasX": 1014,
        "atlasY": 0,
        "atlasW": 92,
        "atlasH": 146
      },
      {
        "mapX": 3272,
        "mapY": 4886,
        "mapW": 32,
        "mapH": 40,
        "atlasX": 1551,
        "atlasY": 0,
        "atlasW": 32,
        "atlasH": 40
      },
      {
        "mapX": 3528,
        "mapY": 5480,
        "mapW": 32,
        "mapH": 38,
        "atlasX": 1785,
        "atlasY": 0,
        "atlasW": 32,
        "atlasH": 38
      },
      {
        "mapX": 1146,
        "mapY": 5912,
        "mapW": 28,
        "mapH": 38,
        "atlasX": 1818,
        "atlasY": 0,
        "atlasW": 28,
        "atlasH": 38
      }
    ]
  }
};
