// AUTO-GENERATED by scripts/gen-hoenn-crop-images.mjs — do not edit by hand.
// Pre-cut walkthrough windows from public/maps/hoenn-map.png (pixel-identical to CSS crops).
// Outdoor routes with baked trainers use *-npcs.png (re-apply via
// scripts/bake-outdoor-route-trainers.mjs after regenerating crops).

/** Outdoor walkthrough area id → pre-rendered crop image under public/. */
export const HOENN_CROP_IMAGE_BY_AREA: Record<string, string> = {
  "battle-frontier": "maps/crops/battle-frontier.png",
  "dewford": "maps/crops/dewford.png",
  "ever-grande": "maps/crops/ever-grande.png",
  "fallarbor": "maps/crops/fallarbor.png",
  "fiery-path": "maps/crops/fiery-path.png",
  "fortree": "maps/crops/fortree.png",
  "lavaridge": "maps/crops/lavaridge.png",
  "lilycove": "maps/crops/lilycove.png",
  "littleroot": "maps/crops/littleroot.png",
  "marine-cave": "maps/crops/marine-cave.png",
  "mauville": "maps/crops/mauville.png",
  "mossdeep": "maps/crops/mossdeep.png",
  "mt-chimney": "maps/crops/mt-chimney.png",
  "oldale": "maps/crops/oldale.png",
  "pacifidlog": "maps/crops/pacifidlog.png",
  "petalburg": "maps/crops/petalburg.png",
  "route-101": "maps/crops/route-101.png",
  "route-102": "maps/crops/route-102-npcs.png",
  "route-103": "maps/crops/route-103-npcs.png",
  "route-104": "maps/crops/route-104-npcs.png",
  "route-105": "maps/crops/route-105.png",
  "route-106": "maps/crops/route-106.png",
  "route-107": "maps/crops/route-107.png",
  "route-108": "maps/crops/route-108.png",
  "route-109": "maps/crops/route-109.png",
  "route-110": "maps/crops/route-110-npcs.png",
  "route-111": "maps/crops/route-111-npcs.png",
  "route-112": "maps/crops/route-112-npcs.png",
  "route-113": "maps/crops/route-113.png",
  "route-114": "maps/crops/route-114.png",
  "route-115": "maps/crops/route-115.png",
  "route-116": "maps/crops/route-116-npcs.png",
  "route-117": "maps/crops/route-117-npcs.png",
  "route-118": "maps/crops/route-118-npcs.png",
  "route-119": "maps/crops/route-119.png",
  "route-120": "maps/crops/route-120.png",
  "route-121": "maps/crops/route-121.png",
  "route-122": "maps/crops/route-122.png",
  "route-123": "maps/crops/route-123.png",
  "route-124": "maps/crops/route-124.png",
  "route-125": "maps/crops/route-125.png",
  "route-126": "maps/crops/route-126.png",
  "route-127": "maps/crops/route-127.png",
  "route-128": "maps/crops/route-128.png",
  "route-129": "maps/crops/route-129.png",
  "route-130": "maps/crops/route-130.png",
  "route-131": "maps/crops/route-131.png",
  "route-132": "maps/crops/route-132.png",
  "route-133": "maps/crops/route-133.png",
  "route-134": "maps/crops/route-134.png",
  "rustboro": "maps/crops/rustboro.png",
  "safari-zone": "maps/crops/safari-zone.png",
  "sealed-chamber": "maps/crops/sealed-chamber.png",
  "sky-pillar": "maps/crops/sky-pillar.png",
  "slateport": "maps/crops/slateport.png",
  "sootopolis": "maps/crops/sootopolis.png",
  "verdanturf": "maps/crops/verdanturf.png",
};

/** Resolve a pre-cut crop image for walkthrough HoennCrop, if available. */
export function hoennCropImagePath(areaId?: string): string | null {
  if (!areaId) return null;
  return HOENN_CROP_IMAGE_BY_AREA[areaId] ?? null;
}
