/** Auto-generated by scripts/sync-item-sprites.mjs — do not edit. */
import type { PoiCategory } from "./mapPoints";

export interface CollectibleSprite {
  spriteSheet: string;
  spriteWidth: number;
  spriteHeight: number;
  spriteFrame: number;
}

export const COLLECTIBLE_SPRITES: Partial<Record<PoiCategory, CollectibleSprite>> = {
  item: {
    "spriteSheet": "sprites/items/item_ball.png",
    "spriteWidth": 16,
    "spriteHeight": 16,
    "spriteFrame": 0
  },
  berry: {
    "spriteSheet": "sprites/items/berry_tree.png",
    "spriteWidth": 16,
    "spriteHeight": 32,
    "spriteFrame": 0
  },
  hidden: {
    "spriteSheet": "sprites/items/hidden_item_ball.png",
    "spriteWidth": 16,
    "spriteHeight": 16,
    "spriteFrame": 0
  },
};

export const COLLECTIBLE_SPRITE_CATEGORIES = ["item", "hidden", "berry"] as const;
export type CollectibleSpriteCategory = (typeof COLLECTIBLE_SPRITE_CATEGORIES)[number];

export function isCollectibleSpriteCategory(
  category: PoiCategory,
): category is CollectibleSpriteCategory {
  return category === "item" || category === "hidden" || category === "berry";
}

export function getCollectibleSprite(category: PoiCategory): CollectibleSprite | null {
  return COLLECTIBLE_SPRITES[category] ?? null;
}
