// AUTO-GENERATED by scripts/gen-marts.mjs — do not edit by hand.
// Poké Mart / shop inventories from pokeemerald scripts.inc + item prices from items.h.

export interface MartItem {
  const: string;
  name: string;
  price: number;
  description: string;
}

export interface MartSection {
  id: string;
  label: string;
  /** When set, this list replaces earlier stock after a story flag. */
  unlockNote: string | null;
  items: MartItem[];
}

export type MartKind = "mart" | "department" | "specialty";

export interface MartData {
  id: string;
  name: string;
  location: string;
  kind: MartKind;
  notes: string[];
  sections: MartSection[];
}

export const MARTS: MartData[] = 
[
  {
    "id": "oldale-mart",
    "name": "Poké Mart",
    "location": "Oldale Town",
    "kind": "mart",
    "notes": [
      "Poké Balls are sold out until you start your adventure (talk to Birch / leave for Route 103)."
    ],
    "sections": [
      {
        "id": "OldaleTown_Mart_Pokemart_Basic",
        "label": "Early stock",
        "unlockNote": null,
        "items": [
          {
            "const": "ITEM_POTION",
            "name": "Potion",
            "price": 300,
            "description": "Restores the HP of a POKéMON by 20 points."
          },
          {
            "const": "ITEM_ANTIDOTE",
            "name": "Antidote",
            "price": 100,
            "description": "Heals a poisoned POKéMON."
          },
          {
            "const": "ITEM_PARALYZE_HEAL",
            "name": "Parlyz Heal",
            "price": 200,
            "description": "Heals a paralyzed POKéMON."
          },
          {
            "const": "ITEM_AWAKENING",
            "name": "Awakening",
            "price": 250,
            "description": "Awakens a sleeping POKéMON."
          }
        ]
      },
      {
        "id": "OldaleTown_Mart_Pokemart_Expanded",
        "label": "Full stock",
        "unlockNote": "After your adventure starts (Pok? Balls unlock)",
        "items": [
          {
            "const": "ITEM_POKE_BALL",
            "name": "Poké Ball",
            "price": 200,
            "description": "A tool used for catching wild POKéMON."
          },
          {
            "const": "ITEM_POTION",
            "name": "Potion",
            "price": 300,
            "description": "Restores the HP of a POKéMON by 20 points."
          },
          {
            "const": "ITEM_ANTIDOTE",
            "name": "Antidote",
            "price": 100,
            "description": "Heals a poisoned POKéMON."
          },
          {
            "const": "ITEM_PARALYZE_HEAL",
            "name": "Parlyz Heal",
            "price": 200,
            "description": "Heals a paralyzed POKéMON."
          },
          {
            "const": "ITEM_AWAKENING",
            "name": "Awakening",
            "price": 250,
            "description": "Awakens a sleeping POKéMON."
          }
        ]
      }
    ]
  },
  {
    "id": "petalburg-mart",
    "name": "Poké Mart",
    "location": "Petalburg City",
    "kind": "mart",
    "notes": [
      "Stock expands after you defeat Roxanne and return — Great Balls and Super Potions appear then."
    ],
    "sections": [
      {
        "id": "PetalburgCity_Mart_Pokemart_Basic",
        "label": "Early stock",
        "unlockNote": null,
        "items": [
          {
            "const": "ITEM_POKE_BALL",
            "name": "Poké Ball",
            "price": 200,
            "description": "A tool used for catching wild POKéMON."
          },
          {
            "const": "ITEM_POTION",
            "name": "Potion",
            "price": 300,
            "description": "Restores the HP of a POKéMON by 20 points."
          },
          {
            "const": "ITEM_ANTIDOTE",
            "name": "Antidote",
            "price": 100,
            "description": "Heals a poisoned POKéMON."
          },
          {
            "const": "ITEM_PARALYZE_HEAL",
            "name": "Parlyz Heal",
            "price": 200,
            "description": "Heals a paralyzed POKéMON."
          },
          {
            "const": "ITEM_AWAKENING",
            "name": "Awakening",
            "price": 250,
            "description": "Awakens a sleeping POKéMON."
          },
          {
            "const": "ITEM_ESCAPE_ROPE",
            "name": "Escape Rope",
            "price": 550,
            "description": "Use to escape instantly from a cave or a dungeon."
          },
          {
            "const": "ITEM_REPEL",
            "name": "Repel",
            "price": 350,
            "description": "Repels weak wild POKéMON for 100 steps."
          },
          {
            "const": "ITEM_X_SPEED",
            "name": "X Speed",
            "price": 350,
            "description": "Raises the stat SPEED during one battle."
          },
          {
            "const": "ITEM_X_ATTACK",
            "name": "X Attack",
            "price": 500,
            "description": "Raises the stat ATTACK during one battle."
          },
          {
            "const": "ITEM_X_DEFEND",
            "name": "X Defend",
            "price": 550,
            "description": "Raises the stat DEFENSE during one battle."
          },
          {
            "const": "ITEM_ORANGE_MAIL",
            "name": "Orange Mail",
            "price": 50,
            "description": "A ZIGZAGOON-print MAIL to be held by a POKéMON."
          }
        ]
      },
      {
        "id": "PetalburgCity_Mart_Pokemart_Expanded",
        "label": "Full stock",
        "unlockNote": "After Norman's Gym opens (four badges - expanded stock)",
        "items": [
          {
            "const": "ITEM_POKE_BALL",
            "name": "Poké Ball",
            "price": 200,
            "description": "A tool used for catching wild POKéMON."
          },
          {
            "const": "ITEM_GREAT_BALL",
            "name": "Great Ball",
            "price": 600,
            "description": "A good BALL with a higher catch rate than a POKé BALL."
          },
          {
            "const": "ITEM_POTION",
            "name": "Potion",
            "price": 300,
            "description": "Restores the HP of a POKéMON by 20 points."
          },
          {
            "const": "ITEM_SUPER_POTION",
            "name": "Super Potion",
            "price": 700,
            "description": "Restores the HP of a POKéMON by 50 points."
          },
          {
            "const": "ITEM_ANTIDOTE",
            "name": "Antidote",
            "price": 100,
            "description": "Heals a poisoned POKéMON."
          },
          {
            "const": "ITEM_PARALYZE_HEAL",
            "name": "Parlyz Heal",
            "price": 200,
            "description": "Heals a paralyzed POKéMON."
          },
          {
            "const": "ITEM_AWAKENING",
            "name": "Awakening",
            "price": 250,
            "description": "Awakens a sleeping POKéMON."
          },
          {
            "const": "ITEM_ESCAPE_ROPE",
            "name": "Escape Rope",
            "price": 550,
            "description": "Use to escape instantly from a cave or a dungeon."
          },
          {
            "const": "ITEM_REPEL",
            "name": "Repel",
            "price": 350,
            "description": "Repels weak wild POKéMON for 100 steps."
          },
          {
            "const": "ITEM_X_SPEED",
            "name": "X Speed",
            "price": 350,
            "description": "Raises the stat SPEED during one battle."
          },
          {
            "const": "ITEM_X_ATTACK",
            "name": "X Attack",
            "price": 500,
            "description": "Raises the stat ATTACK during one battle."
          },
          {
            "const": "ITEM_X_DEFEND",
            "name": "X Defend",
            "price": 550,
            "description": "Raises the stat DEFENSE during one battle."
          },
          {
            "const": "ITEM_ORANGE_MAIL",
            "name": "Orange Mail",
            "price": 50,
            "description": "A ZIGZAGOON-print MAIL to be held by a POKéMON."
          }
        ]
      }
    ]
  },
  {
    "id": "rustboro-mart",
    "name": "Poké Mart",
    "location": "Rustboro City",
    "kind": "mart",
    "notes": [],
    "sections": [
      {
        "id": "RustboroCity_Mart_Pokemart_Basic",
        "label": "Early stock",
        "unlockNote": null,
        "items": [
          {
            "const": "ITEM_POKE_BALL",
            "name": "Poké Ball",
            "price": 200,
            "description": "A tool used for catching wild POKéMON."
          },
          {
            "const": "ITEM_POTION",
            "name": "Potion",
            "price": 300,
            "description": "Restores the HP of a POKéMON by 20 points."
          },
          {
            "const": "ITEM_SUPER_POTION",
            "name": "Super Potion",
            "price": 700,
            "description": "Restores the HP of a POKéMON by 50 points."
          },
          {
            "const": "ITEM_ANTIDOTE",
            "name": "Antidote",
            "price": 100,
            "description": "Heals a poisoned POKéMON."
          },
          {
            "const": "ITEM_PARALYZE_HEAL",
            "name": "Parlyz Heal",
            "price": 200,
            "description": "Heals a paralyzed POKéMON."
          },
          {
            "const": "ITEM_ESCAPE_ROPE",
            "name": "Escape Rope",
            "price": 550,
            "description": "Use to escape instantly from a cave or a dungeon."
          },
          {
            "const": "ITEM_REPEL",
            "name": "Repel",
            "price": 350,
            "description": "Repels weak wild POKéMON for 100 steps."
          },
          {
            "const": "ITEM_X_SPEED",
            "name": "X Speed",
            "price": 350,
            "description": "Raises the stat SPEED during one battle."
          },
          {
            "const": "ITEM_X_ATTACK",
            "name": "X Attack",
            "price": 500,
            "description": "Raises the stat ATTACK during one battle."
          },
          {
            "const": "ITEM_X_DEFEND",
            "name": "X Defend",
            "price": 550,
            "description": "Raises the stat DEFENSE during one battle."
          }
        ]
      },
      {
        "id": "RustboroCity_Mart_Pokemart_Expanded",
        "label": "Full stock",
        "unlockNote": "After helping the Devon employee on Route 116 (expanded stock)",
        "items": [
          {
            "const": "ITEM_POKE_BALL",
            "name": "Poké Ball",
            "price": 200,
            "description": "A tool used for catching wild POKéMON."
          },
          {
            "const": "ITEM_TIMER_BALL",
            "name": "Timer Ball",
            "price": 1000,
            "description": "A BALL that gains power in battles taking many turns."
          },
          {
            "const": "ITEM_REPEAT_BALL",
            "name": "Repeat Ball",
            "price": 1000,
            "description": "A BALL that works better on POKéMON caught before."
          },
          {
            "const": "ITEM_POTION",
            "name": "Potion",
            "price": 300,
            "description": "Restores the HP of a POKéMON by 20 points."
          },
          {
            "const": "ITEM_SUPER_POTION",
            "name": "Super Potion",
            "price": 700,
            "description": "Restores the HP of a POKéMON by 50 points."
          },
          {
            "const": "ITEM_ANTIDOTE",
            "name": "Antidote",
            "price": 100,
            "description": "Heals a poisoned POKéMON."
          },
          {
            "const": "ITEM_PARALYZE_HEAL",
            "name": "Parlyz Heal",
            "price": 200,
            "description": "Heals a paralyzed POKéMON."
          },
          {
            "const": "ITEM_ESCAPE_ROPE",
            "name": "Escape Rope",
            "price": 550,
            "description": "Use to escape instantly from a cave or a dungeon."
          },
          {
            "const": "ITEM_REPEL",
            "name": "Repel",
            "price": 350,
            "description": "Repels weak wild POKéMON for 100 steps."
          },
          {
            "const": "ITEM_X_SPEED",
            "name": "X Speed",
            "price": 350,
            "description": "Raises the stat SPEED during one battle."
          },
          {
            "const": "ITEM_X_ATTACK",
            "name": "X Attack",
            "price": 500,
            "description": "Raises the stat ATTACK during one battle."
          },
          {
            "const": "ITEM_X_DEFEND",
            "name": "X Defend",
            "price": 550,
            "description": "Raises the stat DEFENSE during one battle."
          }
        ]
      }
    ]
  },
  {
    "id": "slateport-mart",
    "name": "Poké Mart",
    "location": "Slateport City",
    "kind": "mart",
    "notes": [],
    "sections": [
      {
        "id": "SlateportCity_Mart_Pokemart",
        "label": "Stock",
        "unlockNote": null,
        "items": [
          {
            "const": "ITEM_POKE_BALL",
            "name": "Poké Ball",
            "price": 200,
            "description": "A tool used for catching wild POKéMON."
          },
          {
            "const": "ITEM_GREAT_BALL",
            "name": "Great Ball",
            "price": 600,
            "description": "A good BALL with a higher catch rate than a POKé BALL."
          },
          {
            "const": "ITEM_POTION",
            "name": "Potion",
            "price": 300,
            "description": "Restores the HP of a POKéMON by 20 points."
          },
          {
            "const": "ITEM_SUPER_POTION",
            "name": "Super Potion",
            "price": 700,
            "description": "Restores the HP of a POKéMON by 50 points."
          },
          {
            "const": "ITEM_ANTIDOTE",
            "name": "Antidote",
            "price": 100,
            "description": "Heals a poisoned POKéMON."
          },
          {
            "const": "ITEM_PARALYZE_HEAL",
            "name": "Parlyz Heal",
            "price": 200,
            "description": "Heals a paralyzed POKéMON."
          },
          {
            "const": "ITEM_ESCAPE_ROPE",
            "name": "Escape Rope",
            "price": 550,
            "description": "Use to escape instantly from a cave or a dungeon."
          },
          {
            "const": "ITEM_REPEL",
            "name": "Repel",
            "price": 350,
            "description": "Repels weak wild POKéMON for 100 steps."
          },
          {
            "const": "ITEM_HARBOR_MAIL",
            "name": "Harbor Mail",
            "price": 50,
            "description": "A WINGULL-print MAIL to be held by a POKéMON."
          }
        ]
      }
    ]
  },
  {
    "id": "mauville-mart",
    "name": "Poké Mart",
    "location": "Mauville City",
    "kind": "mart",
    "notes": [],
    "sections": [
      {
        "id": "MauvilleCity_Mart_Pokemart",
        "label": "Stock",
        "unlockNote": null,
        "items": [
          {
            "const": "ITEM_POKE_BALL",
            "name": "Poké Ball",
            "price": 200,
            "description": "A tool used for catching wild POKéMON."
          },
          {
            "const": "ITEM_GREAT_BALL",
            "name": "Great Ball",
            "price": 600,
            "description": "A good BALL with a higher catch rate than a POKé BALL."
          },
          {
            "const": "ITEM_SUPER_POTION",
            "name": "Super Potion",
            "price": 700,
            "description": "Restores the HP of a POKéMON by 50 points."
          },
          {
            "const": "ITEM_ANTIDOTE",
            "name": "Antidote",
            "price": 100,
            "description": "Heals a poisoned POKéMON."
          },
          {
            "const": "ITEM_PARALYZE_HEAL",
            "name": "Parlyz Heal",
            "price": 200,
            "description": "Heals a paralyzed POKéMON."
          },
          {
            "const": "ITEM_AWAKENING",
            "name": "Awakening",
            "price": 250,
            "description": "Awakens a sleeping POKéMON."
          },
          {
            "const": "ITEM_X_SPEED",
            "name": "X Speed",
            "price": 350,
            "description": "Raises the stat SPEED during one battle."
          },
          {
            "const": "ITEM_X_ATTACK",
            "name": "X Attack",
            "price": 500,
            "description": "Raises the stat ATTACK during one battle."
          },
          {
            "const": "ITEM_X_DEFEND",
            "name": "X Defend",
            "price": 550,
            "description": "Raises the stat DEFENSE during one battle."
          },
          {
            "const": "ITEM_GUARD_SPEC",
            "name": "Guard Spec.",
            "price": 700,
            "description": "Prevents stat reduction when used in battle."
          },
          {
            "const": "ITEM_DIRE_HIT",
            "name": "Dire Hit",
            "price": 650,
            "description": "Raises the critical-hit ratio during one battle."
          },
          {
            "const": "ITEM_X_ACCURACY",
            "name": "X Accuracy",
            "price": 950,
            "description": "Raises accuracy of attack moves during one battle."
          }
        ]
      }
    ]
  },
  {
    "id": "verdanturf-mart",
    "name": "Poké Mart",
    "location": "Verdanturf Town",
    "kind": "mart",
    "notes": [],
    "sections": [
      {
        "id": "VerdanturfTown_Mart_Pokemart",
        "label": "Stock",
        "unlockNote": null,
        "items": [
          {
            "const": "ITEM_GREAT_BALL",
            "name": "Great Ball",
            "price": 600,
            "description": "A good BALL with a higher catch rate than a POKé BALL."
          },
          {
            "const": "ITEM_NEST_BALL",
            "name": "Nest Ball",
            "price": 1000,
            "description": "A BALL that works better on weaker POKéMON."
          },
          {
            "const": "ITEM_SUPER_POTION",
            "name": "Super Potion",
            "price": 700,
            "description": "Restores the HP of a POKéMON by 50 points."
          },
          {
            "const": "ITEM_ANTIDOTE",
            "name": "Antidote",
            "price": 100,
            "description": "Heals a poisoned POKéMON."
          },
          {
            "const": "ITEM_PARALYZE_HEAL",
            "name": "Parlyz Heal",
            "price": 200,
            "description": "Heals a paralyzed POKéMON."
          },
          {
            "const": "ITEM_AWAKENING",
            "name": "Awakening",
            "price": 250,
            "description": "Awakens a sleeping POKéMON."
          },
          {
            "const": "ITEM_BURN_HEAL",
            "name": "Burn Heal",
            "price": 250,
            "description": "Heals POKéMON of a burn."
          },
          {
            "const": "ITEM_ICE_HEAL",
            "name": "Ice Heal",
            "price": 250,
            "description": "Defrosts a frozen POKéMON."
          },
          {
            "const": "ITEM_REPEL",
            "name": "Repel",
            "price": 350,
            "description": "Repels weak wild POKéMON for 100 steps."
          },
          {
            "const": "ITEM_X_SPECIAL",
            "name": "X Special",
            "price": 350,
            "description": "Raises the stat SP. ATK during one battle."
          },
          {
            "const": "ITEM_FLUFFY_TAIL",
            "name": "Fluffy Tail",
            "price": 1000,
            "description": "Use to flee from any battle with a wild POKéMON."
          }
        ]
      }
    ]
  },
  {
    "id": "fallarbor-mart",
    "name": "Poké Mart",
    "location": "Fallarbor Town",
    "kind": "mart",
    "notes": [],
    "sections": [
      {
        "id": "FallarborTown_Mart_Pokemart",
        "label": "Stock",
        "unlockNote": null,
        "items": [
          {
            "const": "ITEM_GREAT_BALL",
            "name": "Great Ball",
            "price": 600,
            "description": "A good BALL with a higher catch rate than a POKé BALL."
          },
          {
            "const": "ITEM_SUPER_POTION",
            "name": "Super Potion",
            "price": 700,
            "description": "Restores the HP of a POKéMON by 50 points."
          },
          {
            "const": "ITEM_ANTIDOTE",
            "name": "Antidote",
            "price": 100,
            "description": "Heals a poisoned POKéMON."
          },
          {
            "const": "ITEM_PARALYZE_HEAL",
            "name": "Parlyz Heal",
            "price": 200,
            "description": "Heals a paralyzed POKéMON."
          },
          {
            "const": "ITEM_ESCAPE_ROPE",
            "name": "Escape Rope",
            "price": 550,
            "description": "Use to escape instantly from a cave or a dungeon."
          },
          {
            "const": "ITEM_SUPER_REPEL",
            "name": "Super Repel",
            "price": 500,
            "description": "Repels weak wild POKéMON for 200 steps."
          },
          {
            "const": "ITEM_X_SPECIAL",
            "name": "X Special",
            "price": 350,
            "description": "Raises the stat SP. ATK during one battle."
          },
          {
            "const": "ITEM_X_SPEED",
            "name": "X Speed",
            "price": 350,
            "description": "Raises the stat SPEED during one battle."
          },
          {
            "const": "ITEM_X_ATTACK",
            "name": "X Attack",
            "price": 500,
            "description": "Raises the stat ATTACK during one battle."
          },
          {
            "const": "ITEM_X_DEFEND",
            "name": "X Defend",
            "price": 550,
            "description": "Raises the stat DEFENSE during one battle."
          },
          {
            "const": "ITEM_DIRE_HIT",
            "name": "Dire Hit",
            "price": 650,
            "description": "Raises the critical-hit ratio during one battle."
          },
          {
            "const": "ITEM_GUARD_SPEC",
            "name": "Guard Spec.",
            "price": 700,
            "description": "Prevents stat reduction when used in battle."
          }
        ]
      }
    ]
  },
  {
    "id": "lavaridge-mart",
    "name": "Poké Mart",
    "location": "Lavaridge Town",
    "kind": "mart",
    "notes": [],
    "sections": [
      {
        "id": "LavaridgeTown_Mart_Pokemart",
        "label": "Stock",
        "unlockNote": null,
        "items": [
          {
            "const": "ITEM_GREAT_BALL",
            "name": "Great Ball",
            "price": 600,
            "description": "A good BALL with a higher catch rate than a POKé BALL."
          },
          {
            "const": "ITEM_SUPER_POTION",
            "name": "Super Potion",
            "price": 700,
            "description": "Restores the HP of a POKéMON by 50 points."
          },
          {
            "const": "ITEM_ANTIDOTE",
            "name": "Antidote",
            "price": 100,
            "description": "Heals a poisoned POKéMON."
          },
          {
            "const": "ITEM_PARALYZE_HEAL",
            "name": "Parlyz Heal",
            "price": 200,
            "description": "Heals a paralyzed POKéMON."
          },
          {
            "const": "ITEM_AWAKENING",
            "name": "Awakening",
            "price": 250,
            "description": "Awakens a sleeping POKéMON."
          },
          {
            "const": "ITEM_BURN_HEAL",
            "name": "Burn Heal",
            "price": 250,
            "description": "Heals POKéMON of a burn."
          },
          {
            "const": "ITEM_REVIVE",
            "name": "Revive",
            "price": 1500,
            "description": "Revives a fainted POKéMON with half its HP."
          },
          {
            "const": "ITEM_SUPER_REPEL",
            "name": "Super Repel",
            "price": 500,
            "description": "Repels weak wild POKéMON for 200 steps."
          },
          {
            "const": "ITEM_X_SPEED",
            "name": "X Speed",
            "price": 350,
            "description": "Raises the stat SPEED during one battle."
          }
        ]
      }
    ]
  },
  {
    "id": "lavaridge-herb-shop",
    "name": "Herb Shop",
    "location": "Lavaridge Town",
    "kind": "specialty",
    "notes": [
      "Herbal medicine is cheap and powerful but lowers friendship (Pokémon dislike the bitter taste).",
      "Talk to the old man once to receive Charcoal (boosts Fire-type moves when held)."
    ],
    "sections": [
      {
        "id": "LavaridgeTown_HerbShop_Pokemart",
        "label": "Stock",
        "unlockNote": null,
        "items": [
          {
            "const": "ITEM_ENERGY_POWDER",
            "name": "Energypowder",
            "price": 500,
            "description": "A bitter powder that restores HP by 50 points."
          },
          {
            "const": "ITEM_ENERGY_ROOT",
            "name": "Energy Root",
            "price": 800,
            "description": "A bitter root that restores HP by 200 points."
          },
          {
            "const": "ITEM_HEAL_POWDER",
            "name": "Heal Powder",
            "price": 450,
            "description": "A bitter powder that heals all status problems."
          },
          {
            "const": "ITEM_REVIVAL_HERB",
            "name": "Revival Herb",
            "price": 2800,
            "description": "A very bitter herb that revives a fainted POKéMON."
          }
        ]
      }
    ]
  },
  {
    "id": "fortree-mart",
    "name": "Poké Mart",
    "location": "Fortree City",
    "kind": "mart",
    "notes": [],
    "sections": [
      {
        "id": "FortreeCity_Mart_Pokemart",
        "label": "Stock",
        "unlockNote": null,
        "items": [
          {
            "const": "ITEM_GREAT_BALL",
            "name": "Great Ball",
            "price": 600,
            "description": "A good BALL with a higher catch rate than a POKé BALL."
          },
          {
            "const": "ITEM_ULTRA_BALL",
            "name": "Ultra Ball",
            "price": 1200,
            "description": "A better BALL with a higher catch rate than a GREAT BALL."
          },
          {
            "const": "ITEM_SUPER_POTION",
            "name": "Super Potion",
            "price": 700,
            "description": "Restores the HP of a POKéMON by 50 points."
          },
          {
            "const": "ITEM_HYPER_POTION",
            "name": "Hyper Potion",
            "price": 1200,
            "description": "Restores the HP of a POKéMON by 200 points."
          },
          {
            "const": "ITEM_ANTIDOTE",
            "name": "Antidote",
            "price": 100,
            "description": "Heals a poisoned POKéMON."
          },
          {
            "const": "ITEM_PARALYZE_HEAL",
            "name": "Parlyz Heal",
            "price": 200,
            "description": "Heals a paralyzed POKéMON."
          },
          {
            "const": "ITEM_AWAKENING",
            "name": "Awakening",
            "price": 250,
            "description": "Awakens a sleeping POKéMON."
          },
          {
            "const": "ITEM_REVIVE",
            "name": "Revive",
            "price": 1500,
            "description": "Revives a fainted POKéMON with half its HP."
          },
          {
            "const": "ITEM_SUPER_REPEL",
            "name": "Super Repel",
            "price": 500,
            "description": "Repels weak wild POKéMON for 200 steps."
          },
          {
            "const": "ITEM_WOOD_MAIL",
            "name": "Wood Mail",
            "price": 50,
            "description": "A SLAKOTH-print MAIL to be held by a POKéMON."
          }
        ]
      }
    ]
  },
  {
    "id": "lilycove-dept-store",
    "name": "Department Store",
    "location": "Lilycove City",
    "kind": "department",
    "notes": [
      "1F is the lobby (elevator / rooftop access). Shopping floors are 2F–4F.",
      "Rooftop has a drink stand and temporary Clear Bell / Tidal Bell events — not a standard mart list."
    ],
    "sections": [
      {
        "id": "LilycoveCity_DepartmentStore_2F_Pokemart1",
        "label": "2F · Balls & status heals",
        "unlockNote": null,
        "items": [
          {
            "const": "ITEM_POKE_BALL",
            "name": "Poké Ball",
            "price": 200,
            "description": "A tool used for catching wild POKéMON."
          },
          {
            "const": "ITEM_GREAT_BALL",
            "name": "Great Ball",
            "price": 600,
            "description": "A good BALL with a higher catch rate than a POKé BALL."
          },
          {
            "const": "ITEM_ULTRA_BALL",
            "name": "Ultra Ball",
            "price": 1200,
            "description": "A better BALL with a higher catch rate than a GREAT BALL."
          },
          {
            "const": "ITEM_ESCAPE_ROPE",
            "name": "Escape Rope",
            "price": 550,
            "description": "Use to escape instantly from a cave or a dungeon."
          },
          {
            "const": "ITEM_FULL_HEAL",
            "name": "Full Heal",
            "price": 600,
            "description": "Heals all the status problems of one POKéMON."
          },
          {
            "const": "ITEM_ANTIDOTE",
            "name": "Antidote",
            "price": 100,
            "description": "Heals a poisoned POKéMON."
          },
          {
            "const": "ITEM_PARALYZE_HEAL",
            "name": "Parlyz Heal",
            "price": 200,
            "description": "Heals a paralyzed POKéMON."
          },
          {
            "const": "ITEM_BURN_HEAL",
            "name": "Burn Heal",
            "price": 250,
            "description": "Heals POKéMON of a burn."
          },
          {
            "const": "ITEM_ICE_HEAL",
            "name": "Ice Heal",
            "price": 250,
            "description": "Defrosts a frozen POKéMON."
          },
          {
            "const": "ITEM_AWAKENING",
            "name": "Awakening",
            "price": 250,
            "description": "Awakens a sleeping POKéMON."
          },
          {
            "const": "ITEM_FLUFFY_TAIL",
            "name": "Fluffy Tail",
            "price": 1000,
            "description": "Use to flee from any battle with a wild POKéMON."
          }
        ]
      },
      {
        "id": "LilycoveCity_DepartmentStore_2F_Pokemart2",
        "label": "2F · Potions & Repels",
        "unlockNote": null,
        "items": [
          {
            "const": "ITEM_POTION",
            "name": "Potion",
            "price": 300,
            "description": "Restores the HP of a POKéMON by 20 points."
          },
          {
            "const": "ITEM_SUPER_POTION",
            "name": "Super Potion",
            "price": 700,
            "description": "Restores the HP of a POKéMON by 50 points."
          },
          {
            "const": "ITEM_HYPER_POTION",
            "name": "Hyper Potion",
            "price": 1200,
            "description": "Restores the HP of a POKéMON by 200 points."
          },
          {
            "const": "ITEM_MAX_POTION",
            "name": "Max Potion",
            "price": 2500,
            "description": "Fully restores the HP of a POKéMON."
          },
          {
            "const": "ITEM_REVIVE",
            "name": "Revive",
            "price": 1500,
            "description": "Revives a fainted POKéMON with half its HP."
          },
          {
            "const": "ITEM_REPEL",
            "name": "Repel",
            "price": 350,
            "description": "Repels weak wild POKéMON for 100 steps."
          },
          {
            "const": "ITEM_SUPER_REPEL",
            "name": "Super Repel",
            "price": 500,
            "description": "Repels weak wild POKéMON for 200 steps."
          },
          {
            "const": "ITEM_MAX_REPEL",
            "name": "Max Repel",
            "price": 700,
            "description": "Repels weak wild POKéMON for 250 steps."
          },
          {
            "const": "ITEM_WAVE_MAIL",
            "name": "Wave Mail",
            "price": 50,
            "description": "A WAILMER-print MAIL to be held by a POKéMON."
          },
          {
            "const": "ITEM_MECH_MAIL",
            "name": "Mech Mail",
            "price": 50,
            "description": "A MAGNEMITE-print MAIL to be held by a POKéMON."
          }
        ]
      },
      {
        "id": "LilycoveCity_DepartmentStore_3F_Pokemart_Vitamins",
        "label": "Vitamins",
        "unlockNote": null,
        "items": [
          {
            "const": "ITEM_PROTEIN",
            "name": "Protein",
            "price": 9800,
            "description": "Raises the base ATTACK stat of one POKéMON."
          },
          {
            "const": "ITEM_CALCIUM",
            "name": "Calcium",
            "price": 9800,
            "description": "Raises the base SP. ATK stat of one POKéMON."
          },
          {
            "const": "ITEM_IRON",
            "name": "Iron",
            "price": 9800,
            "description": "Raises the base DEFENSE stat of one POKéMON."
          },
          {
            "const": "ITEM_ZINC",
            "name": "Zinc",
            "price": 9800,
            "description": "Raises the base SP. DEF stat of one POKéMON."
          },
          {
            "const": "ITEM_CARBOS",
            "name": "Carbos",
            "price": 9800,
            "description": "Raises the base SPEED stat of one POKéMON."
          },
          {
            "const": "ITEM_HP_UP",
            "name": "HP Up",
            "price": 9800,
            "description": "Raises the base HP of one POKéMON."
          }
        ]
      },
      {
        "id": "LilycoveCity_DepartmentStore_3F_Pokemart_StatBoosters",
        "label": "Stat Boosters",
        "unlockNote": null,
        "items": [
          {
            "const": "ITEM_X_SPEED",
            "name": "X Speed",
            "price": 350,
            "description": "Raises the stat SPEED during one battle."
          },
          {
            "const": "ITEM_X_SPECIAL",
            "name": "X Special",
            "price": 350,
            "description": "Raises the stat SP. ATK during one battle."
          },
          {
            "const": "ITEM_X_ATTACK",
            "name": "X Attack",
            "price": 500,
            "description": "Raises the stat ATTACK during one battle."
          },
          {
            "const": "ITEM_X_DEFEND",
            "name": "X Defend",
            "price": 550,
            "description": "Raises the stat DEFENSE during one battle."
          },
          {
            "const": "ITEM_DIRE_HIT",
            "name": "Dire Hit",
            "price": 650,
            "description": "Raises the critical-hit ratio during one battle."
          },
          {
            "const": "ITEM_GUARD_SPEC",
            "name": "Guard Spec.",
            "price": 700,
            "description": "Prevents stat reduction when used in battle."
          },
          {
            "const": "ITEM_X_ACCURACY",
            "name": "X Accuracy",
            "price": 950,
            "description": "Raises accuracy of attack moves during one battle."
          }
        ]
      },
      {
        "id": "LilycoveCity_DepartmentStore_4F_Pokemart_AttackTMs",
        "label": "Attack Tms",
        "unlockNote": null,
        "items": [
          {
            "const": "ITEM_TM_FIRE_BLAST",
            "name": "TM38",
            "price": 5500,
            "description": "A powerful fire attack that may burn the foe."
          },
          {
            "const": "ITEM_TM_THUNDER",
            "name": "TM25",
            "price": 5500,
            "description": "Strikes the foe with a thunderbolt. It may paralyze."
          },
          {
            "const": "ITEM_TM_BLIZZARD",
            "name": "TM14",
            "price": 5500,
            "description": "A brutal snow-and- wind attack that may freeze the foe."
          },
          {
            "const": "ITEM_TM_HYPER_BEAM",
            "name": "TM15",
            "price": 7500,
            "description": "Powerful, but needs recharging the next turn."
          }
        ]
      },
      {
        "id": "LilycoveCity_DepartmentStore_4F_Pokemart_DefenseTMs",
        "label": "Defense Tms",
        "unlockNote": null,
        "items": [
          {
            "const": "ITEM_TM_PROTECT",
            "name": "TM17",
            "price": 3000,
            "description": "Negates all damage, but may fail if used in succession."
          },
          {
            "const": "ITEM_TM_SAFEGUARD",
            "name": "TM20",
            "price": 3000,
            "description": "Prevents status abnormality with a mystical power."
          },
          {
            "const": "ITEM_TM_REFLECT",
            "name": "TM33",
            "price": 3000,
            "description": "Creates a wall of light that weakens physical attacks."
          },
          {
            "const": "ITEM_TM_LIGHT_SCREEN",
            "name": "TM16",
            "price": 3000,
            "description": "Creates a wall of light that lowers SP. ATK damage."
          }
        ]
      }
    ]
  },
  {
    "id": "mossdeep-mart",
    "name": "Poké Mart",
    "location": "Mossdeep City",
    "kind": "mart",
    "notes": [],
    "sections": [
      {
        "id": "MossdeepCity_Mart_Pokemart",
        "label": "Stock",
        "unlockNote": null,
        "items": [
          {
            "const": "ITEM_ULTRA_BALL",
            "name": "Ultra Ball",
            "price": 1200,
            "description": "A better BALL with a higher catch rate than a GREAT BALL."
          },
          {
            "const": "ITEM_NET_BALL",
            "name": "Net Ball",
            "price": 1000,
            "description": "A BALL that works well on WATER- and BUG-type POKéMON."
          },
          {
            "const": "ITEM_DIVE_BALL",
            "name": "Dive Ball",
            "price": 1000,
            "description": "A BALL that works better on POKéMON on the ocean floor."
          },
          {
            "const": "ITEM_HYPER_POTION",
            "name": "Hyper Potion",
            "price": 1200,
            "description": "Restores the HP of a POKéMON by 200 points."
          },
          {
            "const": "ITEM_FULL_HEAL",
            "name": "Full Heal",
            "price": 600,
            "description": "Heals all the status problems of one POKéMON."
          },
          {
            "const": "ITEM_REVIVE",
            "name": "Revive",
            "price": 1500,
            "description": "Revives a fainted POKéMON with half its HP."
          },
          {
            "const": "ITEM_MAX_REPEL",
            "name": "Max Repel",
            "price": 700,
            "description": "Repels weak wild POKéMON for 250 steps."
          },
          {
            "const": "ITEM_X_ATTACK",
            "name": "X Attack",
            "price": 500,
            "description": "Raises the stat ATTACK during one battle."
          },
          {
            "const": "ITEM_X_DEFEND",
            "name": "X Defend",
            "price": 550,
            "description": "Raises the stat DEFENSE during one battle."
          }
        ]
      }
    ]
  },
  {
    "id": "sootopolis-mart",
    "name": "Poké Mart",
    "location": "Sootopolis City",
    "kind": "mart",
    "notes": [],
    "sections": [
      {
        "id": "SootopolisCity_Mart_Pokemart",
        "label": "Stock",
        "unlockNote": null,
        "items": [
          {
            "const": "ITEM_ULTRA_BALL",
            "name": "Ultra Ball",
            "price": 1200,
            "description": "A better BALL with a higher catch rate than a GREAT BALL."
          },
          {
            "const": "ITEM_HYPER_POTION",
            "name": "Hyper Potion",
            "price": 1200,
            "description": "Restores the HP of a POKéMON by 200 points."
          },
          {
            "const": "ITEM_MAX_POTION",
            "name": "Max Potion",
            "price": 2500,
            "description": "Fully restores the HP of a POKéMON."
          },
          {
            "const": "ITEM_FULL_HEAL",
            "name": "Full Heal",
            "price": 600,
            "description": "Heals all the status problems of one POKéMON."
          },
          {
            "const": "ITEM_REVIVE",
            "name": "Revive",
            "price": 1500,
            "description": "Revives a fainted POKéMON with half its HP."
          },
          {
            "const": "ITEM_MAX_REPEL",
            "name": "Max Repel",
            "price": 700,
            "description": "Repels weak wild POKéMON for 250 steps."
          },
          {
            "const": "ITEM_X_ATTACK",
            "name": "X Attack",
            "price": 500,
            "description": "Raises the stat ATTACK during one battle."
          },
          {
            "const": "ITEM_X_DEFEND",
            "name": "X Defend",
            "price": 550,
            "description": "Raises the stat DEFENSE during one battle."
          },
          {
            "const": "ITEM_SHADOW_MAIL",
            "name": "Shadow Mail",
            "price": 50,
            "description": "A DUSKULL-print MAIL to be held by a POKéMON."
          }
        ]
      }
    ]
  },
  {
    "id": "mauville-bike-shop",
    "name": "Bike Shop",
    "location": "Mauville City",
    "kind": "specialty",
    "notes": [
      "Rydel’s Cycles — you choose either the Mach Bike (speed) or Acro Bike (tricks) for free.",
      "You can swap bikes later by returning the one you have.",
      "The Mach Bike is required for the jagged dirt slope on Route 112 / Jagged Pass shortcuts; the Acro Bike is needed for some rail tricks (e.g. Route 119)."
    ],
    "sections": [
      {
        "id": "bikes",
        "label": "Bicycles",
        "unlockNote": null,
        "items": [
          {
            "const": "ITEM_MACH_BIKE",
            "name": "Mach Bike",
            "price": 0,
            "description": "A folding bicycle that doubles your speed or more."
          },
          {
            "const": "ITEM_ACRO_BIKE",
            "name": "Acro Bike",
            "price": 0,
            "description": "A folding bicycle capable of jumps and wheelies."
          }
        ]
      }
    ]
  }
];

/** Map entrance / pin id → mart id. */
export const MART_BY_ENTRANCE_ID: Record<string, string> = 
{
  "en6": "oldale-mart",
  "en40": "petalburg-mart",
  "en45": "mauville-mart",
  "en50": "slateport-mart",
  "en132": "rustboro-mart",
  "en167": "verdanturf-mart",
  "en267": "fallarbor-mart",
  "en273": "lavaridge-herb-shop",
  "en275": "lavaridge-mart",
  "en282": "fortree-mart",
  "en356": "lilycove-dept-store",
  "en384": "mossdeep-mart",
  "en44": "mauville-bike-shop",
  "mart-sootopolis": "sootopolis-mart"
};
