/** Auto-generated by scripts/extract-match-call-schedule.mjs — do not edit. */
export interface MatchCallScheduleRow {
  trainerId: string;
  trainerKey: string;
  name: string;
  mapId: string;
  location: string;
  isGymLeader: boolean;
}

export const MATCH_CALL_SCHEDULE_ROWS: MatchCallScheduleRow[] = [
  {
    "trainerId": "TRAINER_ABIGAIL_1",
    "trainerKey": "TRAINER_ABIGAIL",
    "name": "Abigail",
    "mapId": "MAP_ROUTE110",
    "location": "Route110",
    "isGymLeader": false
  },
  {
    "trainerId": "TRAINER_AMY_AND_LIV_1",
    "trainerKey": "TRAINER_AMY_AND_LIV",
    "name": "Amy And Liv",
    "mapId": "MAP_ROUTE103",
    "location": "Route103",
    "isGymLeader": false
  },
  {
    "trainerId": "TRAINER_ANDRES_1",
    "trainerKey": "TRAINER_ANDRES",
    "name": "Andres",
    "mapId": "MAP_ROUTE105",
    "location": "Route105",
    "isGymLeader": false
  },
  {
    "trainerId": "TRAINER_ANNA_AND_MEG_1",
    "trainerKey": "TRAINER_ANNA_AND_MEG",
    "name": "Anna And Meg",
    "mapId": "MAP_ROUTE117",
    "location": "Route117",
    "isGymLeader": false
  },
  {
    "trainerId": "TRAINER_BENJAMIN_1",
    "trainerKey": "TRAINER_BENJAMIN",
    "name": "Benjamin",
    "mapId": "MAP_ROUTE110",
    "location": "Route110",
    "isGymLeader": false
  },
  {
    "trainerId": "TRAINER_BERNIE_1",
    "trainerKey": "TRAINER_BERNIE",
    "name": "Bernie",
    "mapId": "MAP_ROUTE114",
    "location": "Route114",
    "isGymLeader": false
  },
  {
    "trainerId": "TRAINER_BRAWLY_1",
    "trainerKey": "TRAINER_BRAWLY",
    "name": "Brawly",
    "mapId": "MAP_DEWFORD_TOWN",
    "location": "Dewford Town",
    "isGymLeader": true
  },
  {
    "trainerId": "TRAINER_BROOKE_1",
    "trainerKey": "TRAINER_BROOKE",
    "name": "Brooke",
    "mapId": "MAP_ROUTE111",
    "location": "Route111",
    "isGymLeader": false
  },
  {
    "trainerId": "TRAINER_CALVIN_1",
    "trainerKey": "TRAINER_CALVIN",
    "name": "Calvin",
    "mapId": "MAP_ROUTE102",
    "location": "Route102",
    "isGymLeader": false
  },
  {
    "trainerId": "TRAINER_CAMERON_1",
    "trainerKey": "TRAINER_CAMERON",
    "name": "Cameron",
    "mapId": "MAP_ROUTE123",
    "location": "Route123",
    "isGymLeader": false
  },
  {
    "trainerId": "TRAINER_CATHERINE_1",
    "trainerKey": "TRAINER_CATHERINE",
    "name": "Catherine",
    "mapId": "MAP_ROUTE119",
    "location": "Route119",
    "isGymLeader": false
  },
  {
    "trainerId": "TRAINER_CINDY_1",
    "trainerKey": "TRAINER_CINDY",
    "name": "Cindy",
    "mapId": "MAP_ROUTE104",
    "location": "Route104",
    "isGymLeader": false
  },
  {
    "trainerId": "TRAINER_CORY_1",
    "trainerKey": "TRAINER_CORY",
    "name": "Cory",
    "mapId": "MAP_ROUTE108",
    "location": "Route108",
    "isGymLeader": false
  },
  {
    "trainerId": "TRAINER_CRISTIN_1",
    "trainerKey": "TRAINER_CRISTIN",
    "name": "Cristin",
    "mapId": "MAP_ROUTE121",
    "location": "Route121",
    "isGymLeader": false
  },
  {
    "trainerId": "TRAINER_CYNDY_1",
    "trainerKey": "TRAINER_CYNDY",
    "name": "Cyndy",
    "mapId": "MAP_ROUTE115",
    "location": "Route115",
    "isGymLeader": false
  },
  {
    "trainerId": "TRAINER_DALTON_1",
    "trainerKey": "TRAINER_DALTON",
    "name": "Dalton",
    "mapId": "MAP_ROUTE118",
    "location": "Route118",
    "isGymLeader": false
  },
  {
    "trainerId": "TRAINER_DIANA_1",
    "trainerKey": "TRAINER_DIANA",
    "name": "Diana",
    "mapId": "MAP_JAGGED_PASS",
    "location": "Jagged Pass",
    "isGymLeader": false
  },
  {
    "trainerId": "TRAINER_DRAKE",
    "trainerKey": "TRAINER_DRAKE",
    "name": "Drake",
    "mapId": "MAP_EVER_GRANDE_CITY",
    "location": "Ever Grande City",
    "isGymLeader": true
  },
  {
    "trainerId": "TRAINER_DUSTY_1",
    "trainerKey": "TRAINER_DUSTY",
    "name": "Dusty",
    "mapId": "MAP_ROUTE111",
    "location": "Route111",
    "isGymLeader": false
  },
  {
    "trainerId": "TRAINER_DYLAN_1",
    "trainerKey": "TRAINER_DYLAN",
    "name": "Dylan",
    "mapId": "MAP_ROUTE117",
    "location": "Route117",
    "isGymLeader": false
  },
  {
    "trainerId": "TRAINER_EDWIN_1",
    "trainerKey": "TRAINER_EDWIN",
    "name": "Edwin",
    "mapId": "MAP_ROUTE110",
    "location": "Route110",
    "isGymLeader": false
  },
  {
    "trainerId": "TRAINER_ELLIOT_1",
    "trainerKey": "TRAINER_ELLIOT",
    "name": "Elliot",
    "mapId": "MAP_ROUTE106",
    "location": "Route106",
    "isGymLeader": false
  },
  {
    "trainerId": "TRAINER_ERNEST_1",
    "trainerKey": "TRAINER_ERNEST",
    "name": "Ernest",
    "mapId": "MAP_ROUTE125",
    "location": "Route125",
    "isGymLeader": false
  },
  {
    "trainerId": "TRAINER_ETHAN_1",
    "trainerKey": "TRAINER_ETHAN",
    "name": "Ethan",
    "mapId": "MAP_JAGGED_PASS",
    "location": "Jagged Pass",
    "isGymLeader": false
  },
  {
    "trainerId": "TRAINER_FERNANDO_1",
    "trainerKey": "TRAINER_FERNANDO",
    "name": "Fernando",
    "mapId": "MAP_ROUTE123",
    "location": "Route123",
    "isGymLeader": false
  },
  {
    "trainerId": "TRAINER_FLANNERY_1",
    "trainerKey": "TRAINER_FLANNERY",
    "name": "Flannery",
    "mapId": "MAP_LAVARIDGE_TOWN",
    "location": "Lavaridge Town",
    "isGymLeader": true
  },
  {
    "trainerId": "TRAINER_GABRIELLE_1",
    "trainerKey": "TRAINER_GABRIELLE",
    "name": "Gabrielle",
    "mapId": "MAP_MT_PYRE_3F",
    "location": "Mt Pyre 3f",
    "isGymLeader": false
  },
  {
    "trainerId": "TRAINER_GLACIA",
    "trainerKey": "TRAINER_GLACIA",
    "name": "Glacia",
    "mapId": "MAP_EVER_GRANDE_CITY",
    "location": "Ever Grande City",
    "isGymLeader": true
  },
  {
    "trainerId": "TRAINER_HALEY_1",
    "trainerKey": "TRAINER_HALEY",
    "name": "Haley",
    "mapId": "MAP_ROUTE104",
    "location": "Route104",
    "isGymLeader": false
  },
  {
    "trainerId": "TRAINER_ISAAC_1",
    "trainerKey": "TRAINER_ISAAC",
    "name": "Isaac",
    "mapId": "MAP_ROUTE117",
    "location": "Route117",
    "isGymLeader": false
  },
  {
    "trainerId": "TRAINER_ISABEL_1",
    "trainerKey": "TRAINER_ISABEL",
    "name": "Isabel",
    "mapId": "MAP_ROUTE110",
    "location": "Route110",
    "isGymLeader": false
  },
  {
    "trainerId": "TRAINER_ISAIAH_1",
    "trainerKey": "TRAINER_ISAIAH",
    "name": "Isaiah",
    "mapId": "MAP_ROUTE128",
    "location": "Route128",
    "isGymLeader": false
  },
  {
    "trainerId": "TRAINER_JACKI_1",
    "trainerKey": "TRAINER_JACKI",
    "name": "Jacki",
    "mapId": "MAP_ROUTE123",
    "location": "Route123",
    "isGymLeader": false
  },
  {
    "trainerId": "TRAINER_JACKSON_1",
    "trainerKey": "TRAINER_JACKSON",
    "name": "Jackson",
    "mapId": "MAP_ROUTE119",
    "location": "Route119",
    "isGymLeader": false
  },
  {
    "trainerId": "TRAINER_JAMES_1",
    "trainerKey": "TRAINER_JAMES",
    "name": "James",
    "mapId": "MAP_PETALBURG_WOODS",
    "location": "Petalburg Woods",
    "isGymLeader": false
  },
  {
    "trainerId": "TRAINER_JEFFREY_1",
    "trainerKey": "TRAINER_JEFFREY",
    "name": "Jeffrey",
    "mapId": "MAP_ROUTE120",
    "location": "Route120",
    "isGymLeader": false
  },
  {
    "trainerId": "TRAINER_JENNY_1",
    "trainerKey": "TRAINER_JENNY",
    "name": "Jenny",
    "mapId": "MAP_ROUTE124",
    "location": "Route124",
    "isGymLeader": false
  },
  {
    "trainerId": "TRAINER_JERRY_1",
    "trainerKey": "TRAINER_JERRY",
    "name": "Jerry",
    "mapId": "MAP_ROUTE116",
    "location": "Route116",
    "isGymLeader": false
  },
  {
    "trainerId": "TRAINER_JESSICA_1",
    "trainerKey": "TRAINER_JESSICA",
    "name": "Jessica",
    "mapId": "MAP_ROUTE121",
    "location": "Route121",
    "isGymLeader": false
  },
  {
    "trainerId": "TRAINER_JOHN_AND_JAY_1",
    "trainerKey": "TRAINER_JOHN_AND_JAY",
    "name": "John And Jay",
    "mapId": "MAP_METEOR_FALLS_1F_2R",
    "location": "Meteor Falls 1f 2r",
    "isGymLeader": false
  },
  {
    "trainerId": "TRAINER_JUAN_1",
    "trainerKey": "TRAINER_JUAN",
    "name": "Juan",
    "mapId": "MAP_SOOTOPOLIS_CITY",
    "location": "Sootopolis City",
    "isGymLeader": true
  },
  {
    "trainerId": "TRAINER_KAREN_1",
    "trainerKey": "TRAINER_KAREN",
    "name": "Karen",
    "mapId": "MAP_ROUTE116",
    "location": "Route116",
    "isGymLeader": false
  },
  {
    "trainerId": "TRAINER_KATELYN_1",
    "trainerKey": "TRAINER_KATELYN",
    "name": "Katelyn",
    "mapId": "MAP_ROUTE128",
    "location": "Route128",
    "isGymLeader": false
  },
  {
    "trainerId": "TRAINER_KIRA_AND_DAN_1",
    "trainerKey": "TRAINER_KIRA_AND_DAN",
    "name": "Kira And Dan",
    "mapId": "MAP_ABANDONED_SHIP_ROOMS2_1F",
    "location": "Abandoned Ship Rooms2 1f",
    "isGymLeader": false
  },
  {
    "trainerId": "TRAINER_KOJI_1",
    "trainerKey": "TRAINER_KOJI",
    "name": "Koji",
    "mapId": "MAP_ROUTE127",
    "location": "Route127",
    "isGymLeader": false
  },
  {
    "trainerId": "TRAINER_LAO_1",
    "trainerKey": "TRAINER_LAO",
    "name": "Lao",
    "mapId": "MAP_ROUTE113",
    "location": "Route113",
    "isGymLeader": false
  },
  {
    "trainerId": "TRAINER_LILA_AND_ROY_1",
    "trainerKey": "TRAINER_LILA_AND_ROY",
    "name": "Lila And Roy",
    "mapId": "MAP_ROUTE124",
    "location": "Route124",
    "isGymLeader": false
  },
  {
    "trainerId": "TRAINER_LOLA_1",
    "trainerKey": "TRAINER_LOLA",
    "name": "Lola",
    "mapId": "MAP_ROUTE109",
    "location": "Route109",
    "isGymLeader": false
  },
  {
    "trainerId": "TRAINER_LYDIA_1",
    "trainerKey": "TRAINER_LYDIA",
    "name": "Lydia",
    "mapId": "MAP_ROUTE117",
    "location": "Route117",
    "isGymLeader": false
  },
  {
    "trainerId": "TRAINER_MADELINE_1",
    "trainerKey": "TRAINER_MADELINE",
    "name": "Madeline",
    "mapId": "MAP_ROUTE113",
    "location": "Route113",
    "isGymLeader": false
  },
  {
    "trainerId": "TRAINER_MARIA_1",
    "trainerKey": "TRAINER_MARIA",
    "name": "Maria",
    "mapId": "MAP_ROUTE117",
    "location": "Route117",
    "isGymLeader": false
  },
  {
    "trainerId": "TRAINER_MIGUEL_1",
    "trainerKey": "TRAINER_MIGUEL",
    "name": "Miguel",
    "mapId": "MAP_ROUTE103",
    "location": "Route103",
    "isGymLeader": false
  },
  {
    "trainerId": "TRAINER_NICOLAS_1",
    "trainerKey": "TRAINER_NICOLAS",
    "name": "Nicolas",
    "mapId": "MAP_METEOR_FALLS_1F_2R",
    "location": "Meteor Falls 1f 2r",
    "isGymLeader": false
  },
  {
    "trainerId": "TRAINER_NOB_1",
    "trainerKey": "TRAINER_NOB",
    "name": "Nob",
    "mapId": "MAP_ROUTE115",
    "location": "Route115",
    "isGymLeader": false
  },
  {
    "trainerId": "TRAINER_NORMAN_1",
    "trainerKey": "TRAINER_NORMAN",
    "name": "Norman",
    "mapId": "MAP_PETALBURG_CITY",
    "location": "Petalburg City",
    "isGymLeader": true
  },
  {
    "trainerId": "TRAINER_PABLO_1",
    "trainerKey": "TRAINER_PABLO",
    "name": "Pablo",
    "mapId": "MAP_ROUTE126",
    "location": "Route126",
    "isGymLeader": false
  },
  {
    "trainerId": "TRAINER_PHOEBE",
    "trainerKey": "TRAINER_PHOEBE",
    "name": "Phoebe",
    "mapId": "MAP_EVER_GRANDE_CITY",
    "location": "Ever Grande City",
    "isGymLeader": true
  },
  {
    "trainerId": "TRAINER_RICKY_1",
    "trainerKey": "TRAINER_RICKY",
    "name": "Ricky",
    "mapId": "MAP_ROUTE109",
    "location": "Route109",
    "isGymLeader": false
  },
  {
    "trainerId": "TRAINER_ROBERT_1",
    "trainerKey": "TRAINER_ROBERT",
    "name": "Robert",
    "mapId": "MAP_ROUTE120",
    "location": "Route120",
    "isGymLeader": false
  },
  {
    "trainerId": "TRAINER_ROSE_1",
    "trainerKey": "TRAINER_ROSE",
    "name": "Rose",
    "mapId": "MAP_ROUTE118",
    "location": "Route118",
    "isGymLeader": false
  },
  {
    "trainerId": "TRAINER_ROXANNE_1",
    "trainerKey": "TRAINER_ROXANNE",
    "name": "Roxanne",
    "mapId": "MAP_RUSTBORO_CITY",
    "location": "Rustboro City",
    "isGymLeader": true
  },
  {
    "trainerId": "TRAINER_SAWYER_1",
    "trainerKey": "TRAINER_SAWYER",
    "name": "Sawyer",
    "mapId": "MAP_MT_CHIMNEY",
    "location": "Mt Chimney",
    "isGymLeader": false
  },
  {
    "trainerId": "TRAINER_SHELBY_1",
    "trainerKey": "TRAINER_SHELBY",
    "name": "Shelby",
    "mapId": "MAP_MT_CHIMNEY",
    "location": "Mt Chimney",
    "isGymLeader": false
  },
  {
    "trainerId": "TRAINER_SIDNEY",
    "trainerKey": "TRAINER_SIDNEY",
    "name": "Sidney",
    "mapId": "MAP_EVER_GRANDE_CITY",
    "location": "Ever Grande City",
    "isGymLeader": true
  },
  {
    "trainerId": "TRAINER_STEVE_1",
    "trainerKey": "TRAINER_STEVE",
    "name": "Steve",
    "mapId": "MAP_ROUTE114",
    "location": "Route114",
    "isGymLeader": false
  },
  {
    "trainerId": "TRAINER_TATE_AND_LIZA_1",
    "trainerKey": "TRAINER_TATE_AND_LIZA",
    "name": "Tate And Liza",
    "mapId": "MAP_MOSSDEEP_CITY",
    "location": "Mossdeep City",
    "isGymLeader": true
  },
  {
    "trainerId": "TRAINER_THALIA_1",
    "trainerKey": "TRAINER_THALIA",
    "name": "Thalia",
    "mapId": "MAP_ABANDONED_SHIP_ROOMS_1F",
    "location": "Abandoned Ship Rooms 1f",
    "isGymLeader": false
  },
  {
    "trainerId": "TRAINER_TIMOTHY_1",
    "trainerKey": "TRAINER_TIMOTHY",
    "name": "Timothy",
    "mapId": "MAP_ROUTE115",
    "location": "Route115",
    "isGymLeader": false
  },
  {
    "trainerId": "TRAINER_TONY_1",
    "trainerKey": "TRAINER_TONY",
    "name": "Tony",
    "mapId": "MAP_ROUTE107",
    "location": "Route107",
    "isGymLeader": false
  },
  {
    "trainerId": "TRAINER_TRENT_1",
    "trainerKey": "TRAINER_TRENT",
    "name": "Trent",
    "mapId": "MAP_ROUTE112",
    "location": "Route112",
    "isGymLeader": false
  },
  {
    "trainerId": "TRAINER_VALERIE_1",
    "trainerKey": "TRAINER_VALERIE",
    "name": "Valerie",
    "mapId": "MAP_MT_PYRE_6F",
    "location": "Mt Pyre 6f",
    "isGymLeader": false
  },
  {
    "trainerId": "TRAINER_WALLACE",
    "trainerKey": "TRAINER_WALLACE",
    "name": "Wallace",
    "mapId": "MAP_EVER_GRANDE_CITY",
    "location": "Ever Grande City",
    "isGymLeader": true
  },
  {
    "trainerId": "TRAINER_WALLY_VR_2",
    "trainerKey": "TRAINER_WALLY_VR",
    "name": "Wally Vr",
    "mapId": "MAP_VICTORY_ROAD_1F",
    "location": "Victory Road 1f",
    "isGymLeader": false
  },
  {
    "trainerId": "TRAINER_WALTER_1",
    "trainerKey": "TRAINER_WALTER",
    "name": "Walter",
    "mapId": "MAP_ROUTE121",
    "location": "Route121",
    "isGymLeader": false
  },
  {
    "trainerId": "TRAINER_WATTSON_1",
    "trainerKey": "TRAINER_WATTSON",
    "name": "Wattson",
    "mapId": "MAP_MAUVILLE_CITY",
    "location": "Mauville City",
    "isGymLeader": true
  },
  {
    "trainerId": "TRAINER_WILTON_1",
    "trainerKey": "TRAINER_WILTON",
    "name": "Wilton",
    "mapId": "MAP_ROUTE111",
    "location": "Route111",
    "isGymLeader": false
  },
  {
    "trainerId": "TRAINER_WINONA_1",
    "trainerKey": "TRAINER_WINONA",
    "name": "Winona",
    "mapId": "MAP_FORTREE_CITY",
    "location": "Fortree City",
    "isGymLeader": true
  },
  {
    "trainerId": "TRAINER_WINSTON_1",
    "trainerKey": "TRAINER_WINSTON",
    "name": "Winston",
    "mapId": "MAP_ROUTE104",
    "location": "Route104",
    "isGymLeader": false
  }
];
