// AUTO-GENERATED by scripts/gen-shop-pins.mjs — do not edit by hand.
// Outdoor shop landmarks from pokeemerald map.json + .calib/manifest.json.
import type { MapPoint } from "./mapPoints";

export const SHOP_PINS_GENERATED: MapPoint[] = [
  { id: "shop-slateport-market", name: "Market", category: "shop", x: 26.81, y: 81.33, note: "Slateport City" }, // bg:MarketSign tile 14,51
];
